components/atoms/Search/search.tsx
Adds an "X" button that clears the search bar.
closes #345
=> feat: add X button to clear search bar

README.md
Our community is interested in contributing to this project, but do not have access to a lot of the context. To remedy this I have create a centralized place to grab issues if they are willing. We cannot entertain "good first issues" in this project due to the signal vs noise challenge. Introducing new contributors distracts from the roadmap, which is why we will suggest good first issues be opened in open-sauced/hot instead.
=> fix: outside contribution suggestions

components/organisms/TopNav/top-nav.tsx
Adds an Explore button in top navigation bar that links to `/javascript/dashboard/filter/recent`. This makes it possible to navigate between different sections of the project.
Note:
- A new issue should be opened that would make the 'Insight Hub' link red if we are in hub section, or make 'Explore' link red if we are in explore section.
fixes #661
=> feat: add Explore to nav

components/organisms/Contributors/contributors.tsx, interfaces/global-state-types.ts, lib/hooks/useContributionsList.ts, lib/hooks/useTopicContributions.ts, lib/store/index.ts
This PR:
- Adds the functionality to filter contributor calendar by "7 days", "30 days" and "3 months"
How I did:
- I have used the same date-filtering component used for the repository.
- Added an extra param "range" to the API endpoint.
- Added an extra state "contributorRange" in the store.
Fixes #663 
Before:
After:
=> feat: Add date filter to the contributor calendar

components/molecules/CardProfile/card-profile.tsx, components/molecules/ContributorTable/contributor-table.tsx, components/molecules/LatestPrTableRow/latest-pr-table-row.tsx, components/molecules/TableRepositoryName/table-repository-name.tsx, components/organisms/ContributorProfilePage/contributor-profile-page.tsx, next-types.d.ts, stories/organisms/contributor-profile-page.stories.tsx
=> Moving my branch from fork to main

pages/_app.tsx
This PR fixes caching error on page reload.
Approach:
- move `localStorage.setItem` into a `trycatch` block
- catch the error named `QuotaExceededError` 
- add a `warning` in the console
Fixes #617
=> fix: handle caching issues with local storage

components/molecules/CardProfile/card-profile.tsx, components/molecules/ContributorTable/contributor-table.tsx, components/molecules/LatestPrTableRow/latest-pr-table-row.tsx, components/molecules/TableRepositoryName/table-repository-name.tsx, components/organisms/ContributorProfilePage/contributor-profile-page.tsx, next-types.d.ts, stories/organisms/contributor-profile-page.stories.tsx
This PR links user profiles in Contributors tab to their GitHub profiles, links repositories avatars in Repositories tabs to their Github pages, and links PRs to their github links. Visual context is provided below.
Modified the PR data interface to include the new/required data fields coming from the backend.
Also added these new fields to the storybook tests.
Linked with the backend issue: https://github.com/open-sauced/gs-api.opensauced.pizza/issues/116
closes #670 
closes #620 
closes #669
=> feat: Link repos to GitHub

.github/workflows/triage.yml
Minimizes some of the recent take messages.
=> test: implement automatic notifications for foss

components/atoms/Avatar/avatar.tsx, lib/utils/cachedImages.ts, lib/utils/roundedImages.ts, next.config.js
This PR:
- creates a new helper function in the `libs` directory named `cachedImages`
- enable image caching for all avatars across pages
- adds `res.cloudinary.com` to next image domains array in `next.config.js` file to enable support for cloudinary image urls on next images.
- In the future we can now use the helper function to cache other images aside avatars
- more details of the cloudinary implementation can be found on their [docs](https://cloudinary.com/documentation/fetch_remote_images#remote_image_fetch_url)
Fixes #680
=> feat: implement image caching on avatar images

components/molecules/ContributorTable/contributor-table.tsx, components/molecules/LatestPrTableRow/latest-pr-table-row.tsx
This PR:
- Sorts the `contributorPRs` array data by the most recent `updated_at` time value
- Updates the last updated time value
Fixes #682
=> feat: filter recent contributions array by last updated time

components/organisms/ContributorProfilePage/contributor-profile-page.tsx, layouts/profile.tsx, pages/user/[username].tsx
This PR:
- creates a new `profile` layout component for the generic profile page
- updates the profile page to match UI design https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5206%3A5781&t=VyhaHubG5373bwBm-0
Fixes #692
=> fix: update generic profile page styles to match design

components/molecules/Pagination/pagination.tsx, components/molecules/PaginationGotoPage/pagination-goto-page.tsx, components/organisms/Contributors/contributors.tsx, components/organisms/Repositories/repositories.tsx
This PR includes the support for goto page functionality on the repositories and contributors page
The Ui was worked on here https://github.com/open-sauced/insights/pull/357 and the implementation was done here https://github.com/open-sauced/insights/pull/405
Fixes #675
=> feat: add support for goto page functionality

.env, components/organisms/Reports/reports.tsx, components/organisms/StripeCheckoutButton/stripe-checkout-button.tsx, lib/utils/stripe-client.ts, npm-shrinkwrap.json, package.json
This PR:
- Replaces the waitlist button on the reports page with a button to subscribe with Stripe Checkout
- The button initiates the subscription checkout flow to Stripe
- Needs [https://github.com/open-sauced/api.opensauced.pizza/pulls to ](https://github.com/open-sauced/api.opensauced.pizza/pull/74) to be merged/deployed/configured
- Needs better copy
#394
=> feat: add Stripe checkout integration

components/molecules/TableRepositoryName/table-repository-name.tsx
This PR:
- Fixes an issue with the `Link` component not having child elements
Closes #726
=> fix: add wrapper element for Link usage on table repo name

components/molecules/TableHeader/table-header.tsx
Adjusts the Search Bar's font-size in Repositories tab to be similar to it's surrounding elements
fixes #660 
Before:
After:
=> feat: adjust search font-size

components/molecules/NivoScatterChart/nivo-scatter-chart.tsx
=> feat: change name to enhace from logarithmic

components/atoms/Avatar/avatar.tsx, components/molecules/AuthSection/auth-section.tsx, components/molecules/StackedAvatar/stacked-avatar.tsx, components/molecules/TableRepositoryName/table-repository-name.tsx
This PR:
- updates the `Avatar` component to include prop `isCached` of type `boolean` to account for cached and uncached avatars 
- Updates the `StackAvatar` component to be cached based on the current `Avatar` implementation.
Fixes #733
=> fix: user profile auth avatar processing errors

components/molecules/StackedAvatar/stacked-avatar.tsx
This PR:
- Prevents pulling user insights for repositories on non-insight pages
- Needs a future refactor to pass in repositories
=> fix: only pull insights for stacked avatar on insight pages

components/organisms/ContributorProfilePage/contributor-profile-page.tsx, lib/hooks/useSingleContributor.ts, lib/hooks/useTopicContributorPRs.ts
This PR:
- Fixes issues with `undefined` being passed for the topic when pulling data for a contributor
BEFORE:
AFTER:
=> fix: fix data fetching for contributor page data

pages/pages/[userOrg]/[filterName]/[toolName].tsx, pages/pages/[userOrg]/[filterName]/[toolName]/filter/[...selectedFilter].tsx
This PR:
- Redirects back to the homepage if an insights page is private and not being viewed by its owner
Test URL: https://deploy-preview-767--oss-insights.netlify.app/pages/bdougie/4/dashboard
Fixes #763
=> fix: redirect from hub page if not authorized to view

components/molecules/InsightHeader/insight-header.tsx
This PR:
- Aligns the public/private badge with the insight name 
- Follow-up for https://github.com/open-sauced/insights/pull/735
=> fix: fix placement of badge on insight page

lib/hooks/useFetchUser.ts, next-types.d.ts, pages/user/[username].tsx, stories/molecules/insight-page-card.stories.tsx
This PR:
- Checks for username before making API request
- Fixes field name for recently merged prs
BEFORE
AFTER
=> fix: check for contributor username and update field for recent merged prs

components/molecules/ContributorHoverCard/contributor-hover-card.tsx, components/molecules/PullRequestTable/pull-request-table.tsx, components/organisms/ContributorCard/contributor-card.tsx, components/organisms/ContributorProfilePage/contributor-profile-page.tsx, stories/molecules/contributor-table.stories.tsx
Fixes #681 
Renamed the ContributorTable component to PullRequestTable component.
Tested the ContributorHoverCard and validated the Pull Request Table is working or not.
=> refactor: Renamed the ContributorTable to PullRequestTable

components/organisms/RepositoriesTable/repositories-table.tsx
Reverts open-sauced/insights#778
The check is there to show the message for a placeholder repo that isn't indexed when using the filter.
=> revert: "fix: fix for empty repo list"

.storybook/preview.js
This PR:
- Fixes an issue with Storybook introduced with the Next 13 upgrade with optimizing images
Reference:
https://github.com/vercel/next.js/issues/36417#issuecomment-1117360509
=> fix: add fix for Storybook usage with Next 13

.storybook/preview.js, components/atoms/Avatar/avatar.tsx, components/atoms/ContextThumbnail/context-thumbnail.tsx, components/atoms/FilterCard/filter-card.tsx, components/atoms/Icon/icon.tsx, components/atoms/IconButton/icon-button.tsx, components/molecules/AuthSection/auth-section.tsx, components/molecules/CardProfile/card-profile.tsx, components/molecules/CardRepoList/card-repo-list.tsx, components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, components/molecules/FavoriteRepoCard/favorite-repo-card.tsx, components/molecules/HeaderLogo/header-logo.tsx, components/molecules/HighlightCard/highlight-card.tsx, components/molecules/RepoCardProfile/repo-card-profile.tsx, components/molecules/ReposoitoryCartItem/repository-cart-item.tsx, components/molecules/SuggestedRepo/suggested-repo.tsx, components/molecules/TableRepositoryName/table-repository-name.tsx, components/organisms/Footer/footer.tsx, components/organisms/RepositoriesTable/repositories-table.tsx, components/templates/Loader/loader.tsx
This PR:
- Removes usage of `next/legacy/image` component, along with deprecated props
- Removes workaround for Storybook
=> fix: remove usage of next/legacy/image

components/organisms/Repositories/repositories.tsx
=> fix: repositories table responsiveness bug

components/organisms/InsightPage/InsightPage.tsx, interfaces/global-state-types.ts, lib/hooks/useSession.ts, lib/store/index.ts
This PR:
- Allows users with a higher role level to add more repos to an insight page
- Sets the default limit to 10 in the global store
- Needs https://github.com/open-sauced/api.opensauced.pizza/pull/86 to be merged/deployed
=> feat: set insight repo limit based on role

components/atoms/Badge/badge.tsx, components/atoms/InsightBadge/insight-badge.tsx, components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, layouts/profile.tsx, stories/atoms/badge.stories.tsx, stories/atoms/insight-badge.stories.tsx
This PR:
- Adds the `beta` tag badge to connected user profile
- creates a reusable badge component
- fixes user profile layout margin issues in #820 
Fixes #821
Fixes #820
=> feat: add profile badge to connected user profile

lib/hooks/useUserInsights.ts
This PR:
- Increases the limit for insights pages being listed
- Future improvement is to add pagination to the insights list
=> fix: increase limit for listing insight pages

pages/[filterName]/insights/[insightId]/edit.tsx
This PR:
- Fixes an issue with the insight edit page showing Unauthorized based on user id check
Notes:
- This was a good first issue but affects production usage
Closes #833
=> fix: update check for user id when editing an insight page

lib/hooks/useUserInsights.ts
=> fix: bump insight page limit higher

CHANGELOG.md, components/molecules/HighlightInput/highlight-input-form.tsx, lib/hooks/useUserInsights.ts, npm-shrinkwrap.json, package.json, stories/molecules/highlight-input.stories.tsx
=> 1.27.1-beta.1 -> production

components/molecules/HighlightsFeedCard/highlights-filter-card.tsx, stories/molecules/highlights-filter-card.stories.tsx
this PR add's UI for the Highlights feed filter card
Fixes #827
=> feat: add highlights feed filter card to design system

components/organisms/InsightPage/InsightPage.tsx, next-types.d.ts, pages/start.tsx
This PR:
- Uses the GitHub Repo ID when onboarding and managing insight repos
- Needs https://github.com/open-sauced/api.opensauced.pizza/pull/103
=> feat: add support for repo full name for onboarding/insight repos

components/atoms/LanguagePill/LanguagePill.tsx, components/molecules/FilterHeader/filter-header.tsx, lib/utils/check-camelcase-naming.ts, tests/lib/utils/check-camelcase-naming.test.ts
Converts 'Javascript' into 'JavaScript' in language pill component and in FilterLayout header
Fixes #822
=> feat: add utility function to camelcase topic value

e2e-tests/UnsignedUsersRedirects.spec.ts, interfaces/seo-type.ts, interfaces/with-page-layout.ts, jest.config.js, layouts/SEO/SEO.tsx, pages/[filterName]/[toolName].tsx, pages/[filterName]/[toolName]/[filter]/[...selectedFilter].tsx, pages/[filterName]/insights/[insightId]/edit.tsx, pages/[filterName]/insights/index.tsx, pages/[filterName]/insights/new.tsx, pages/_app.tsx, pages/index.tsx, pages/pages/[userOrg]/[filterName]/[toolName].tsx, pages/pages/[userOrg]/[filterName]/[toolName]/filter/[...selectedFilter].tsx, pages/user/[username].tsx, pages/user/settings.tsx, playwright.config.ts
- Implements a new system to ease adding SEO to pages, and provides default SEO data if not specified.
- Fills in SEO data for the pages.
Technical implementation details present in a comment below.
part of #814
=> feat: add support for custom SEO per page

lib/utils/date-utils.ts, tests/lib/utils/date-utils.test.ts, tests/lib/utils/get-filter-key.test.ts, tests/lib/utils/get-filter-query.test.ts, tests/lib/utils/get-percent.test.ts, tests/lib/utils/github.test.ts, tests/lib/utils/timezones.test.ts, tests/lib/utils/uppercase-first.test.ts, tests/lib/utils/validate-email.test.ts
- Fixes the method `getRelativeDays` in `date-utils.ts`
- Adds unit tests to the simple lib functions.
closes #546
=> feat: add unit testing for lib files

components/atoms/ContextFilterButton/context-filter-button.tsx, components/molecules/FilterHeader/filter-header.tsx, components/molecules/SuperlativeSelector/superlative-selector.tsx
PR fixes two issues on mobile resolution:
#805 
Filter button breaks out of the container on long repo names. To fix this, the text was truncated with an ellipsis. A further enhancement is possible by removing 'filtered by' or shortening it simply to 'by', if necessary. 
#806 
The drop-down was moved to the left on mobile, to prevent the content from being cut off. 
Fixes #805 
Fixes #806
Before:
https://user-images.githubusercontent.com/43274289/218179334-06e39998-4c53-4176-a917-90f7875807a3.mov
After:
https://user-images.githubusercontent.com/43274289/218180415-6457eb0b-0d69-4135-a338-19aab371e86b.mov
=> fix: truncate text on mobile (#805) & move dropdown (#806)

components/atoms/TextInput/text-input.tsx, components/organisms/InsightPage/InsightPage.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx, pages/start.tsx
This PR fixes the input reset bug by clearing the input state when the clear (`x`) button is clicked
Fixes #858
[insights-bug.webm](https://user-images.githubusercontent.com/79809121/218312324-38a8e5b2-19e7-46ab-885a-b7bd9a33691e.webm)
=> fix: reset text input fields when clear button is clicked

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, lib/utils/timezones.ts
This PR fixes the profile interest pills breaking
Fixes #887
=> fix: user profile interest pill UI fix

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
This PR hides all elements that need API updates to be functional for now
https://github.com/open-sauced/insights/issues/887
https://github.com/open-sauced/insights/issues/886
https://github.com/open-sauced/insights/issues/885
https://github.com/open-sauced/insights/issues/884
https://github.com/open-sauced/insights/issues/883
https://github.com/open-sauced/insights/issues/882
=> refactor: hide non-functional elements in highlights card

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, components/organisms/ContributorProfilePage/contributor-profile-page.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx, lib/hooks/update-user.ts, next-types.d.ts
This PR:
- Adds LinkedIn and GitHub Sponsors to the user profile for display and update
=> feat: add user profile fields for LinkedIn, GitHub sponsors

components/molecules/HighlightInput/highlight-input-form.tsx
After posting a new highlight, the success message says "uploade" instead of "uploaded." I updated the message to be "Highlight posted!"
Fixes #904
=> fix: highlight toast message

components/molecules/HighlightCard/highlight-card.tsx, components/organisms/Dashboard/dashboard.tsx
Adds a loading state to the Highlight Card component, and makes use of it in the Dashboard to display skeleton till the data is loaded.
Fixes #903
=> feat: add loading state to highlight cards

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, pages/user/[username].tsx
This PR replaces the user's `default bio` with the message `[user] has connected their GitHub but has not added a bio.` I made the message a little pale.
Fixes #922
=> feat: remove default user bio

components/atoms/Button/button.tsx, components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/HighlightInput/highlight-input-form.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx
This PR:
-  fixes the button CSS styles to match the design
- fixes highlights description layout break on mobile
Fixes #934 
Fixes #937
=> fix:  broken css on button component

lib/hooks/useTopicContributorCommits.ts
This PR:
- Fixes an issue when visiting a user profile and the contributor commit data is not resolved yet
=> fix: check for contributor commit data before updating graph

components/molecules/HighlightInput/highlight-input-form.tsx
The user is blocked for not knowing how to submit a highlight. Adding the "Click here" context as a bandaid, but we will want to rethink the UX on this.  
https://twitter.com/styfle/status/1631755476403724290?s=20
Maybe we can address this in this issue - https://github.com/open-sauced/insights/issues/943 cc @getaheaddev
=> fix: Highlights UX copy bandaid

components/molecules/HighlightInput/highlight-input-form.tsx
related https://github.com/open-sauced/insights/pull/944
=> fix: Add highlights placeholder

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
this PR makes interest clickable and navigate to the dashboard with a language filter
Fixes #942
=> feat: make interest clickable 

components/atoms/Avatar/avatar.tsx, components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
This PR:
-  replaces non-connected user's avatar with fallback initials. 
- Updates avatar props to include `initialsClassNames` for styling the initials
Fixes #964
=> refactor: update non connect user avatar 

components/molecules/InsightRow/insight-row.tsx
This PR makes the entire "next/go to insight page" button iclickable.
Fixes #701
=> feat: make the entire insight page buttons clickable

components/atoms/Search/search.tsx, components/organisms/InsightPage/InsightPage.tsx
This PR adds the functionality to search any repository and add it to the insights page.
Fixes #932
=> feat: add search to the create insights page

components/molecules/HighlightInput/highlight-input-form.tsx
I did not add this extra context to the placeholder last week. 
https://github.com/open-sauced/insights/pull/944
=> fix: adds more placeholder

components/molecules/CardProfile/card-profile.tsx, components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, components/molecules/LatestPrTableHeader/latest-pr-table-header.tsx
This PR adds the systems custom tooltip to the pr list role icons with better description text
Fixes #955
=> feat: add custom tooltip to pr list icon

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
This PR fixes the highlights update text area body overlap
Fixes #984
=> fix: input body overlaps

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
This pr fixes the permalink URL when copying a highlight link for social sharing
Fixes #997
=> fix: copy correct permalink

components/molecules/PaginationResults/pagination-result.tsx, components/molecules/TableHeader/table-header.tsx, components/organisms/ContributorProfilePage/contributor-profile-page.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, components/organisms/Contributors/contributors.tsx, components/organisms/Repositories/repositories.tsx, pages/_app.tsx, pages/feed/index.tsx, stories/molecules/pagination-result.stories.tsx
This PR adds pagination to user profile and feeds highlights list
Fixes #978
=> feat: add pagination component to feeds and profile

components/molecules/LatestPrTableRow/latest-pr-table-row.tsx, components/molecules/PullRequestTable/pull-request-table.tsx, next-types.d.ts
This PR:
- Connects pull requests for contributors to the OpenSauced API
- Needs https://github.com/open-sauced/api.opensauced.pizza/pull/124
=> feat: connect pull requests to API

components/organisms/TopNav/top-nav.tsx, pages/[filterName]/insights/index.tsx
=> feat: Add context to the Insights Page

components/molecules/RepoCardProfile/repo-card-profile.tsx, components/molecules/SuggestedRepo/suggested-repo.tsx, components/organisms/InsightPage/InsightPage.tsx, components/organisms/SuggestedRepoList/suggested-repo-list.tsx, stories/organisms/suggested-repo-list.stories.tsx
- Extends on the Repo Suggestions List component
- Inserts it in Create Insight Page
- Adds 3 static suggestions to it
closes #711
=> feat: implement repo suggestions in create insight page

components/organisms/InsightPage/DeleteInsightPageModal.tsx
Makes the `Delete` in the delete popup stand out.
Fixes #1020
=> fix: make delete standout

components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, pages/feed/index.tsx
This PR adds highlights refresh on update or delete action trigger
Fixes #1021
=> fix: update and delete highlight refresh

lib/utils/recommendation.ts, lib/utils/recommendations.ts
- Adds a predefined list for recommended repos links for each interest. This would be adjusted when the repo recommendations would be implemented to see what is really needed from the repos (like is the full url needed to be saved, or just the name, or name and description, etc.)
closes #1001
=> feat: add recommendation repo links

pages/start.tsx
This PR fixes a typo currently displaying **Authenicate** on [start](https://insights.opensauced.pizza/start) page.
Fixes #1065
=> fix: fix typo in GitHub button to authenticate

components/molecules/RepoRow/repo-row.tsx
- Changes repository activity from commit count to pull request count
Closes https://github.com/open-sauced/ops-backend/issues/41
BEFORE:
AFTER:
=> fix: use PR counts for determining repository activity levels

components/molecules/CardRepoList/card-repo-list.tsx, components/molecules/InsightHeader/insight-header.tsx, components/molecules/InsightRow/insight-row.tsx
Fixes a bug where the total number of repos is greater than the pagination count
=> fix: use total repo count for displaying repo count on insight page

components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/organisms/ContributorProfilePage/contributor-profile-page.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, lib/hooks/useFetchAllEmojis.ts, lib/hooks/useFollowUser.ts, lib/hooks/useHighlightReactions.tsx, lib/hooks/useUserHighlightReactions.ts, next-types.d.ts, npm-shrinkwrap.json, package.json, pages/feed/index.tsx
This PR: 
- Adds highlight reaction implementation
- Adds [react-emoji-render](https://github.com/tommoor/react-emoji-render) to render emojis
> User's can't react to their highlights
Closes #882
=> feat: implement highlight reaction features

pages/hub/insights/[insightId]/accept.tsx
- Adds a page to accept an invitation to join an insight as a team member
- URL path is below
`/hub/insights/{insightId}/accept?id={inviteId}`
Closes #https://github.com/open-sauced/ops-backend/issues/49
Logged In
Not logged in
=> feat: add page to accept insight member invitation

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
When navigating to a user who's not connected, they are redirected an `undefined/contributions` URL
=> fix: only redirect on contributor profile if login is defined

components/organisms/Dashboard/dashboard.tsx, lib/hooks/api/useContributors.ts, lib/hooks/api/useInsights.ts, lib/hooks/api/usePullRequests.ts, lib/hooks/api/useRepositories.ts
- Uses pull requests insights from the API
- Removes topic query when searching by specific repo(s)
- Displays non-zero values on dashboard insight cards
- Needs https://github.com/open-sauced/api.opensauced.pizza/pull/144 to be merged/deployed
Before:
After (with prod data)
=> feat: connect dashboard insights to API

components/organisms/ContributorProfilePage/contributor-profile-page.tsx
While adding the follow feature, it seems like the isConnected user check wiped out our previous to not provide all the context for non opensauced members. 
fixes #1124
=> feat: adds is_opensauced_member check

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
Issue #686 has been sitting for a while and now that we have social cards, I'd like to make it easier to share OpenSauced profiles. 
This change adds a button to the users profile that copies to the clipboard. I am not confident this is the best approach, but open to suggestions. 
re #686
=> feat: adds a share button to profile

components/molecules/ReportsHistory/csv-download.tsx, components/molecules/ReportsHistory/reports-history.tsx, components/molecules/SelectReportsFilter/select-reports-filter.tsx, lib/utils/get-current-date.ts
- Uses the API to pull data for reports
- Fixes bugs with the current date and button alignment
=> fix: connect reports to the API

components/atoms/Toast/toast.tsx
Fixing the inaccessible menu due to toast and updating the position. 
The whole conversation happened in the main issue: (fixes #1098)
Desktop: 
Mobile: 
Mobile 2:
=> fix: toast inaccessible menu (#1098)

interfaces/global-state-types.ts, lib/hooks/useSession.ts, lib/hooks/useSupabaseAuth.ts, lib/store/index.ts, pages/_app.tsx
- Moves session data into global store
- Fetches auth earlier in app lifecycle
- Decreases number of auth calls during app lifecycle
=> fix: make auth session calls earlier and less often

lib/hooks/useFollowUser.ts, pages/_app.tsx
- Skips retries when receiving an error when checking if a user is following another
=> fix: disable retry on error when checking user follow

components/atoms/NotificationsCard/notification-card.tsx, components/molecules/AuthSection/auth-section.tsx, stories/atoms/notification-card.stories.tsx, tailwind.config.js
This PR adds the notification card to the design system
This is prep work to implement #1106
A new color was also included in the tailwind config file `hsl(24, 100%, 95%)`
=> feat: add notification card to design system

components/organisms/Dashboard/dashboard.tsx
- Updates the filters to match against the lowercased pr status
BEFORE:
AFTER:
=> fix: normalize casing for PR status filters

components/atoms/Textarea/text-area.tsx, components/molecules/HighlightInput/highlight-input-form.tsx
This PR fixes the issue with the highlight input text area auto-resize behavior. Mobile behavior remains as is, and reason's can be found in the comment section of this PR.
Fixes #1081
https://user-images.githubusercontent.com/62995161/235842544-38437380-fe35-49c1-9f25-24d72ad21a7a.mov
=> fix: auto row expansion on text area

.eslintrc.json, pages/index.tsx, pages/start.tsx
- Redirects the user to their profile page after completing onboarding
- File formatting done in a separate commit
=> feat: redirect user to profile after onboarding 

components/molecules/ContextClueCard/context-clue-card.tsx, stories/molecules/context-clue-card.stories.tsx
This PR creates and add `ContextClueCard` component to the design system
Closes #804
=> feat:  add context clue card to design system

components/atoms/DashedContainer/DashContainer.tsx, components/molecules/RecommendedRepoCard/recommended-repo-card.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, lib/hooks/api/useRepositoryPullRequests.ts, lib/hooks/fetchRecommendationByRepo.ts, next-types.d.ts, stories/molecules/recommended-repo-card.stories.tsx
This PR: 
- Adds recommendations tab to a users profile page
- implements repo recommendations with user's selected topics (interests)
- refactors tab styling to match the design
- updates recommendation components props and structure
- Adds ui flow for users without interest to add one/multiple topics to their interests
Users with one interest gets `opensauced/insights` repo as an additional recommendation
Closes #802
=> feat: add repo recommendations to user profile

components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/HighlightInput/highlight-input-form.tsx
This PR makes the highlight textarea expandable
Fixes #1103
https://github.com/open-sauced/insights/assets/79809121/cd98555a-a6b2-462d-a50e-a8099a97ac2e
=> feat: make highlight textarea expandable

components/molecules/HighlightInput/highlight-input-form.tsx
Fixes https://github.com/open-sauced/insights/issues/1192
Fixes #1192 
related: https://github.com/open-sauced/insights/issues/1192
Not related but this is funny:
=> feat: limit length title in highlight

components/organisms/InsightPage/InsightPage.tsx
This PR fixes the overlap issue(bug) that was occurring from 1135px to 1024px in https://insights.opensauced.pizza/hub/insights/new page. 
Fixes #1198 . The text now doesn't overlap as the `lg:flex-row` is changed to `xl:flex-row` that keep space between the components as the page shrinks. 
Before
After
=> fix: overlap issue in InsightPage

pages/_app.tsx
Zendesk requires too much training and knowledge. 
This PR adds SiteGPT AI widget to _app.tsx.
This PR removes the Zendesk snippet and adds SiteGPT AI widget to the _app.tsx file. The widget is included by adding the script tag to the head of the document. The snippet can be found in the external script hosted at https://sitegpt.ai/widget/365440930125185604.js.
Description generated using [OpenSauced](https://opensauced.ai/).
=> feat: Replace zendesk with SiteGPT

npm-shrinkwrap.json, package.json, pages/_app.tsx
Update `posthog-js` from version `1.42.3` to `1.57.2`, remove `@sentry/types` and add PostHog tracking for page views. This PR also includes code to handle server-side rendering in Next.js.
Description generated using [OpenSauced](https://opensauced.ai/).
This is needed to get more insights on how folks are converting through onboarding and anonymous usage of the features.
https://posthog.com/docs/libraries/next-js
=> feat: Posthog next middleware

.github/workflows/development.yml, .github/workflows/release.yml, package.json
=> ci: move unit and e2e tests into separate jobs

pages/feed/index.tsx
This PR fixes the repo filter issue on the feeds page from #1212
Fixes #1212
=> fix: set default value to repo filter state

lib/utils/get-contributor-pr-velocity.ts
- Fixes a rounding issue with average PR velocity
Fixes #1219
=> fix: round velocity after calculation

.github/workflows/compliance.yml, .github/workflows/development.yml, .github/workflows/maintenance.yml, .github/workflows/release.yml
This PR updates the workflow files to use the new repository name "open-sauced/hot". 
https://github.com/open-sauced/open-sauced/issues/1491
=> feat: Remove all open-sauced/open-sauced workflows

components/organisms/FollowersHighlightWrapper/following-highlight-wrapper.tsx, components/organisms/HomeHighlightsWrapper/home-highlights-wrapper.tsx
This PR formats highlights on feed to show date based on distance from not format
Fixes #1225
=> fix: format highlight date on feeds page to distance from now

components/atoms/Search/search.tsx
This PR updates the Search component with improved styling and functionality. The suggestions dropdown now has a smaller padding and more space between suggestions. The onBlur event now has a longer timeout to prevent the dropdown from disappearing too quickly. The suggestion items now have a hover effect and improved text color. Overall, this PR enhances the user experience of the Search component.
Fixes #1226 
https://github.com/open-sauced/insights/assets/62995161/5534b3b3-e3fb-4758-a915-dce3c6dd4566
=> fix: search result suggestions click non-responsiveness

components/organisms/Reports/reports.tsx
This PR fixes the force login in the reports page
Fixes #1235 
Before
After
| | |
| ------ | ------ |
| ![reports-sol-1](https://github.com/open-sauced/insights/assets/79809121/4a7389d6-f87a-4798-9e94-5d2d4e5a86f7) | ![reports-sol-2](https://github.com/open-sauced/insights/assets/79809121/0c168c26-9f17-4743-a360-768d7f2bd24d) |
=> fix: force login in reports page

components/molecules/ContributorListTableRow/contributor-list-table-row.tsx, components/organisms/Contributors/contributors.tsx, components/organisms/ContributorsTable/contributors-table.tsx, components/organisms/Dashboard/dashboard.tsx, lib/hooks/api/useContributors.ts, next-types.d.ts
- Updates the useContributors hook to use the contributors API endpoint
- Removes duplicates from the contributors page
URL: https://beta.insights.opensauced.pizza/angular/contributors/filter/recent
BEFORE:
AFTER:
=> fix: update contributors hook to use contributor API endpoint

components/molecules/SelectReportsFilter/select-reports-filter.tsx, stories/molecules/select-reports-filter.stories.tsx
Refactor the SelectReportsFilter component to allow for dynamic rendering of filter options and display the selected filter name in the dropdown trigger. The filterList prop is now required and the onValueChange function is added to update the selectedValue state. The selected filter name is now displayed in the dropdown trigger instead of "Select a Filter".
I removed the empty state of the select filter because it is redundant for as all filters are bond to have options and not empty options
Fixes #1233 
https://github.com/open-sauced/insights/assets/62995161/eacbd2ef-829e-4ac4-b25a-56e8a65d3fe7
https://github.com/open-sauced/insights/assets/62995161/8e225ac0-7634-4551-8515-eb52ffaf7438
=> fix: reports select issue

components/molecules/RepoRow/repo-row.tsx
- Update RepoRow component's getActivity function to show "Medium" activity for repositories with total between 5 and 80 instead of 20 and 80. This change will provide a more accurate representation of repository activity.
Closes #1224
=> fix: update medium activity threshold for repositories

components/atoms/Pill/pill.tsx
Fixes the `<Pill />` component so it renders yellow text correctly. It was previously referencing a non-existent text color class which caused it to just take the text color for its parent context.
=> fix: Fix yellow color for `<Pill />` component

components/atoms/TopUserCard/top-user-card.tsx, components/molecules/TopUsersPanel/top-user-panel.tsx, stories/atoms/top-user-card.stories.tsx, stories/molecules/top-users-panel.stories.tsx
This PR adds TopUserCard and TopUsersPanel components to the project. TopUserCard is an atom that displays a user's avatar, username, and a follow/unfollow button. TopUsersPanel is a molecule that displays a list of TopUserCards. The components are fully responsive and customizable. Storybook stories are also added for both components.
closes #1293
=> feat: add top users panel component to design system

components/molecules/Billboard/billboard.tsx, npm-shrinkwrap.json, package.json, stories/molecules/bill-board.stories.tsx
Add new component BillBoard to the design system. It displays a banner image, title, description and a link to a repository. The component uses @radix-ui/react-aspect-ratio for responsive image rendering. The component is now available in the design system and can be used in any project.
Closes #1292
=> feat: add `BillBoard` component to design system

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
=> fix: hide unnecessary scrollbar in profilepage

components/atoms/UserCard/user-card.tsx, components/molecules/TopUsersPanel/top-user-panel.tsx, next-types.d.ts, pages/feed/index.tsx
This PR includes the following changes:
- Updated the global user type interface.
- Added a loading state to the userCard component.
- Added a user card component to highlight feeds.
In the future, we need to include the `highlightCount` to the user data in the API... fetching all highlights to get the count is a temporary solution for now.
=> feat: add  `UserCard` to feeds page

components/molecules/DevCard/dev-card.tsx, components/organisms/DevCardCarousel/dev-card-carousel.tsx, npm-shrinkwrap.json, package.json, pages/user/[username]/card.tsx
- Swaps out the implementation of the devcard for the [`react-parallax-tilt` library](https://www.npmjs.com/package/react-parallax-tilt). 
- This solves a weird animation bug that was seen on firefox.
https://github.com/open-sauced/insights/assets/555044/52078845-b04e-4bea-ae14-8a81ce725df8
- Also solves responsive layout issue where the buttons on mobile devices were appearing past the bottom of the screen.
| before | after |
| ---- | ---- |
| ![IMG_4281](https://github.com/open-sauced/insights/assets/555044/2e849391-37a6-49c7-a2ca-efa12f1741f8) | ![IMG_4280](https://github.com/open-sauced/insights/assets/555044/929ef254-366d-417c-bc2c-65326a791095) |
=> fix: devcard animation issue with firefox

components/organisms/UserSettingsPage/user-settings-page.tsx
This PR fixes the font color of selected interests pill in User Settings Page
Fixes #1341
Before 
After
NA
:relaxed:
=> fix: ensure font color of selected interests pill changed is white 

pages/feed/index.tsx
- Fixes handling of the newsletter form submission by adding a hidden HTML form that's rendered in the HTML. 
- This form is in addition to the interactive form included on the feed page. 
- Because the page is client-rendered, this allows Netlify to process the form and handle submissions correctly.
=> fix: fix newsletter form submission

components/atoms/UserCard/user-card.tsx, components/molecules/AnnouncementCard/announcement-card.tsx, components/molecules/TopContributorsPanel/top-contributors-panel.tsx, pages/feed/index.tsx, stories/molecules/bill-board.stories.tsx
This PR adds the open-sauced `#100DaysOfOSS` challenge announcement to the feeds page and updates component naming, props and styles to fit its use.
Closes #1388
=> feat: add `#100DayOfOSS` challenge anouncement to feeds

lib/hooks/useFetchTopContributors.ts
- Fixes the top contributors hook to use the updated response from the API
=> fix: update top contributors response data

lib/hooks/useContributorPullRequestsChart.ts, lib/utils/get-formatted-tooltip-value.ts, stories/molecules/card-line-chart.stories.tsx
This PR enhances the user experience by implementing hover and highlight functionality for the contribution graph. Now, users can easily hover over points on the graph to view PRs and visually distinguish their contributions.
Fixes #721 
Before :
After:
=> feat: implemented hover and highlight contribution graph

components/organisms/ToolsDisplay/tools-display.tsx
This PR removed the test content which flashes while loading in dashboard page
Fixes #1408 
Before :
After :
=> fix: flash of "test content" while loading in dashboard page

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
This PR reduces the font size of the user profile tab headers
=> fix: reduce tab font size in contributors profile page

components/organisms/Footer/footer.tsx
fixed bug on chatbot button overlay: The chatbot button overlays on the footer links which has now been fixed.
Fixes #1416
=> fix: fixed bug on chatbot button overlay

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
Changed highlight button to say "Delete Highlight" instead of "Delete Page" when editing a highlight.
Closes #1382
=> fix: Deleted page button changed to delete highlight

components/organisms/SuggestedRepoList/suggested-repo-list.tsx
This PR is intended to complete the UI work already in Progress by @LadegbayeStella in #1385 
Closes #1343 
Closes #1385
=> style: remove irrelevant padding in page divider

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
=> style: add width and max width for created at in contributor-profile-tab

components/molecules/AuthSection/auth-section.tsx
fixes #1434 
Changed the 'div' tag to 'button' for accessibility through pressing tab.
=> fix: issue #1434 Improve Keyboard Accessibility for Notification Icon

components/organisms/TopNav/top-nav.tsx
fixes #1433 
Replaced 'div' with 'nav' and used 'ul' with 'li' for every link
=> fix: add navigation to improve accessibility

components/molecules/ContributorHighlight/contributor-highlight-card.tsx, lib/utils/github.ts, stories/molecules/contributor-highlight-card.stories.tsx
This PR updates the contributor's highlight card UI to now support highlights for 
This PR adds highlights for
- Pull requests
- Issues 
- Blogs to the contributor's highlight card UI.
For the time being, failing to provide a type will result in a Pull request. 
This PR  also includes a story for the contributor's highlights card.
Closes #1176
=> feat: new contributor highlight card

components/molecules/OnboardingButton/onboarding-button.tsx
This PR fixes the Onborading button UI issue
Fixes #1457
=> fix: hide onboarding button on mobile

components/organisms/UserSettingsPage/user-settings-page.tsx, e2e-tests/UnsignedUsersRedirects.spec.ts, middleware.ts, pages/hub/insights/index.tsx, pages/index.tsx
This PR updates the redirect from homepage to `/feed` when a user is not authenticated
Closes #1461
=> feat: update redirect to feed page for unauthenticated users

components/atoms/LanguagePill/LanguagePill.tsx
=> fix: user interest logo error 

.github/workflows/release.yml
This updates the release workflow to use the OpenSauced GitHub App for the semantic release job to provide correct access to push release commits to the necessary branches.
This allows us to have PR approvals and still use automated versioning for release deployments
=> fix: update release workflow to use GitHub app for semantic versioning

components/organisms/UserSettingsPage/user-settings-page.tsx
Fixes a bug where user settings are not populated on load
Before:
After:
=> fix: check session when updating user settings

layouts/filter.tsx, layouts/hub-page.tsx, layouts/hub.tsx, layouts/profile.tsx, pages/feed/index.tsx
This PR fixes margin top issues in the explore, highlight and insight page
this error was from my previous PR after setting the topNav header to fix 
Fixes #1531 and Fixes #1526 
Kindly take your time to review this and let me know if this issue still persist
Thanks
=> fix: fixed margin issues on layout

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
This PR introduces optimizations to the parsing and filtering of the interests string, enhancing the efficiency and accuracy of data processing.
fixes #1454
- Before:
After: 
https://github.com/open-sauced/insights/assets/106407013/3c997c9f-d53d-499a-bc90-cb1c7f400c32
=> fix: exclude empty interests on profile page

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx, layouts/filter.tsx, layouts/hub-page.tsx, layouts/hub.tsx, layouts/profile.tsx, pages/feed/index.tsx
=> fix: release 1.59 hot fixes

components/molecules/SuggestedRepo/suggested-repo.tsx, components/organisms/InsightPage/InsightPage.tsx, components/organisms/SuggestedRepoList/suggested-repo-list.tsx
This PR disabled the button while it's loading, so it doesn't add the same repo again
Fixes #1507 
Before:
After:
:smiley:
=> fix: disabled the button while it's loading, so it doesn't add the same repo again

components/atoms/UserCard/user-card.tsx, components/molecules/AnnouncementCard/announcement-card.tsx, components/molecules/HighlightsFeedCard/highlights-filter-card.tsx, components/molecules/TopContributorsPanel/top-contributors-panel.tsx, layouts/profile.tsx, pages/feed/index.tsx
This pull request addresses the responsiveness of the feed layout to ensure a consistent and optimal user experience across different devices and screen sizes. 
https://github.com/open-sauced/insights/pull/1490#pullrequestreview-1565363428
Fixes #1543
https://github.com/open-sauced/insights/assets/106407013/42538997-e007-4f7f-b129-d15dd9f89c79
=> fix: enhance feed layout responsiveness

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
This PR adds icon buttons to the ContributorProfileHeader component for mobile breakpoints, addressing spacing issues.
Fixes #1491 
Before 
After 
- [ x] 🙅 no, because they aren't needed
- [ x] 🙅 no documentation needed
=> fix: add space between avatar and  cta menu

lib/utils/get-notification-url.ts, next-types.d.ts, pages/user/notifications.tsx
This PR refactors the logic for retrieving and displaying the username in the notifications component. 
- Added a new function `getNotificationUsername` which returns the username based on the notification type.
- Updated the avatarURL and username display logic to use the `getNotificationUsername` function.
- Removed the unused `username` variable and related code.
- Improved code readability and maintainability.
This change ensures that the correct username is displayed for each notification type and improves the overall code structure.
Fixes #1529 
Before
After
=> fix: refactor notification username retrieval and display logic

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, components/organisms/ContributorProfilePage/contributor-profile-page.tsx, next-types.d.ts
- Replaces the `beta` badge with a check of whether the user is a `maintainer` of projects
BEFORE:
AFTER: w/o badge
AFTER: w/badge
=> feat: update beta badge with maintainer badge to contributor profile

sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts
- Adjusts the sampling rates for Sentry to decrease frequency of reporting
=> chore: adjust sampling rates for Sentry

components/molecules/SelectReportsFilter/select-reports-filter.tsx
This pr adds a background color to the select filter in the reports page.
Fixes #1568 
Before
After
=> fix: add bg color to reports select filter

components/molecules/SuggestedRepo/suggested-repo.tsx
fix #1552
fixed the height of suggested repositories for mobile screen
=> fix: corrected repo card for mobile

components/organisms/TopNav/top-nav.tsx
Fixes #1511
Active class from the "Highlights" nav item was getting removed because the full path was not matching in the check. We needed to make use of the initial path only. So, I have made that change in this PR.
Fixes #1511 
<table>
<tr>
<th>Before</th>
<td><img src="https://github.com/open-sauced/insights/assets/27003616/c69aba52-5897-4d2f-9e85-fba8748093c3"/></td>
</tr>
<tr>
<th>After</th>
<td><img src="https://github.com/open-sauced/insights/assets/27003616/1698e70e-c469-463f-9a01-528c11286d8d"/></td>
</tr>
</table>
=> fix: highlights nav item unselected when there were query params in URL

components/molecules/NivoScatterChart/nivo-scatter-chart.tsx
fix #1572
Corrected Alignment for mobile users
=> fix: corrected Alignment for mobile view

components/molecules/HighlightsFeedCard/highlights-filter-card.tsx, pages/feed/index.tsx, stories/molecules/highlights-filter-card.stories.tsx
- There was unnecessary use of `useEffect` in `components\molecules\HighlightsFeedCard\highlights-filter-card.tsx` file. The variable was being set with its own value. It was actually doing nothing so I removed it (0fc3156).
- There was a comment on it which was to reset the `selectedRepo` state variable. I made sure it was done. I shifted it to a `onTabChange` function which is also given the functionality of clearing the filter from URL as well (0e93f69).
fixes #1576 
fixes #1576 
| ------ | ------ |
| [highlights-issue.webm](https://github.com/open-sauced/insights/assets/27003616/aea650fc-0de3-4723-a012-dabb8732ab99) | [highlights-flicker-fix.webm](https://github.com/open-sauced/insights/assets/27003616/649eada3-c4ca-4b42-ba58-de5c26009d2a) |
| And | And |
| …
=> fix: highlights page endless flicker on tab change (1576)

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Remove the unnecessary code that renders the `tagged_repos` element in the `ContributorProfileTab` component. 
Fixes #1592
Before:
After:
=> fix: Highlights in user profile page breaks when a repo is tagged

components/atoms/TopContributorCard/top-contributor-card.tsx, components/molecules/TopContributorsPanel/top-contributors-panel.tsx, pages/feed/index.tsx
=> fix: issue-#1418 refetch following count after following a user

components/molecules/TopContributorsPanel/top-contributors-panel.tsx, lib/hooks/useFetchTopContributors.ts, pages/feed/index.tsx
This PR sends the logged in user id to the API to filter out already followed user's from the top users list
related to #1593 and https://github.com/open-sauced/api/pull/275
###After
=> refactor: update top users implementation to remove already followed users

.github/workflows/development.yml, components/molecules/ContributorHighlight/contributor-highlight-card.tsx
- Fixes an error on beta where `reaction_users` is not defined for some of the emojis. To reproduce, go to https://beta.insights.opensauced.pizza/feed
- Bumps the node version to 18 for e2e tests
=> fix: add check for reaction users array

e2e-tests/CloseSingleHighlight.spec.ts
- Temporarily disables flaky E2E tests for checking the display of the feed dialog. From the logs, looks like the Vercel logo is capturing the clicks intended for the close button. May need a better target selector
=> chore: temp disable e2e dialog tests

components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/HighlightInput/highlight-input-form.tsx, lib/hooks/updateHighlight.ts
This PR includes the following changes:
- Added support for updating blog highlights
- Added support for updating tagged repositories
- Updated the request payload.
fixes #1614
=> fix: add support for blog highlight update

lib/utils/date-utils.ts
This PR refactors the `calcDistanceFromToday` function which is used in calculating the number of years, months, days from today.
Closes #1619 
#1619 
Not requiered
=> refactor: calcDistanceFromToday function

.husky/pre-commit, components/atoms/CartIllustration/cart-illustration.tsx, pages/feed/index.tsx
This pull request focuses on eliminating a Tailwind anti-pattern that was present in the repository's codebase. The changes made in this PR address the usage of the problematic Tailwind `w-[72px]`, replacing it with a more suitable and maintainable alternative. 
Fixes #1522
=> fix: remove tailwind anti-pattern from the repo

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
- Adds a fallback check for `tagged_repos` in the event that the cache has highlight data that hasn't been invalidated with the latest release.
Closes #1644
=> fix: add check for undefined tagged_repos

.github/workflows/release.yml, .github/workflows/storybook.yml, package.json
=> ci: update node version to 18 in workflows

lib/hooks/api/useRepositoryPullRequests.ts
- When entering a specific repo into the search box on the repositories pages, it appends the topic to the pull request endpoint, which limits the results returned.
- This removes the topic from the API endpoint when searching for a specific repo
BEFORE:
AFTER:
=> fix: remove topic from query params when a repository is provided

components/ListHeader/list-header.tsx, components/TabList/tab-list-item.tsx, components/TabList/tab-list.tsx, layouts/lists.tsx, lib/hooks/useList.ts, next-types.d.ts, pages/lists/[listId]/activity.tsx, pages/lists/[listId]/contributors.tsx, pages/lists/[listId]/index.tsx, pages/lists/[listId]/overview.tsx, pages/lists/index.tsx
- Adds layout for Lists pages
- Adds pages for routing to list overview/activity/contributors pages
- Adds List placeholder for overview 
Closes https://github.com/open-sauced/app/issues/1667
=> feat: add page layout and pages for lists overview, activity, and contributors

components/organisms/InsightPage/InsightPage.tsx, components/organisms/RepositoriesCart/repositories-cart.tsx, lib/hooks/useFetchOrgRecommendations.ts, next-types.d.ts
This PR adds new repository recommendation types, a fetch recommendation hook, and implements live recommendations. These additions enhance the functionality of the application and improve the user experience.
Fixes #1640 
https://github.com/open-sauced/app/assets/62995161/83e573ab-2cc1-468b-b240-789ee30442c2
=> feat: implement Live insights repo recommendations

components/organisms/Footer/footer.tsx
fix #1654
Corrected overlaping of footer icons
Fixes #1654
=> fix: fixed Overlay button in footer

netlify.toml
- Adds configuration for a domain-level redirect from insight.opensauced.pizza and app.opensauced.pizza to insights.opensauced.pizza
- Docs https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects
=> chore: add redirect for insight subdomain

components/molecules/AnnouncementCard/announcement-card.tsx, components/molecules/CardRepoList/card-repo-list.tsx, components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/FeaturedHighlightsPanel/featured-highlights-panel.tsx, components/molecules/GhOpenGraphImg/gh-open-graph-img.tsx, components/molecules/HighlightsFeedCard/highlights-filter-card.tsx, components/molecules/NewsletterForm/newsletter-form.tsx, components/molecules/TopContributorsPanel/top-contributors-panel.tsx, components/organisms/HomeHighlightsWrapper/home-highlights-wrapper.tsx, pages/feed/index.tsx
Couldn't find related tickets.
Before
**After**
- All panels now have the same padding
- Misaligned components are now aligned on the same vertical axis (ie avatar next to create highlight form)
- Header on the highlights card is fixed
No
=> fix: Highlights Page - Minor style fixes

.github/workflows/storybook.yml
- Fixes an issue in CI where it fails everytime we do a merge to `main`
=> ci: fix command for storybook build on release

lib/hooks/api/useRepositoryPullRequests.ts
- Fixes a bug where the repo query param isn't passed to each individual repo in the repository pull requests hook
Fixes https://github.com/open-sauced/app/issues/1689
BEFORE:
AFTER:
=> fix: apply repo query param for each repo if not using a global filter

components/molecules/ListCard/list-card.tsx, components/molecules/StackedAvatar/stacked-avatar.tsx, next-types.d.ts, stories/molecules/list-card.stories.tsx
This PR adds a new component called `ListCard` which is a molecule component. It displays a card with information about a list. The card includes the list name, whether it is public or private, the number of contributors, and avatars of the contributors. The component also includes buttons to delete the list and navigate to the list's overview page. The `StackedAvatar` component is also updated to include a `classNames` prop for custom styling.
closes #1669
=> feat: add `ListCard` component to design system

components/molecules/HighlightInput/highlight-input-form.tsx
fix #1702
Made responsive new insight button for mobile
Fix #1702
=> fix: new highlight responsiveness on mobile screens

layouts/hub.tsx
- Removes Lists item from the Insights Hub Nav as its still in progress
BEFORE:
AFTER:
=> fix: remove lists from insights hub nav

.github/CODEOWNERS
Updates the CODEOWNERS file with the engineering team.
Fixes #1713
=> chore: updated CODEOWNERS file

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
This PR updates the `ContributorHighlightCard` component. It replaces the `DropdownMenu` component with the `Popover` component for better accessibility and user experience. The dropdown menu options are now displayed in a popover content. The code also includes some minor styling changes and updates to the button elements. These changes improve the overall functionality and visual appeal of the `ContributorHighlightCard` component.
Fixes #1705
https://github.com/open-sauced/app/assets/106407013/0e225e19-83b2-4c37-9a90-db2c7318d2ec
=> fix: unlock Scroll when the Dropdown Menu is opened 

components/molecules/HighlightInput/highlight-input-form.tsx
Added some padding to the add repo dialog so it looks good on smaller screens. I'm not sure what we use for consistent padding @isabensusan, so I went with `p-2` which we appear to use at least in this component file.
Relates to #1716 #1719
=> fix: improved padding for add repo dialog

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
This PR addresses the issue of the scrollbar locking and preventing scrolling that was observed in the `ContributorProfileHeader` component. It achieves this by replacing the deprecated `DropdownMenu` component with the `Popover` component from `@radix-ui/react-popover`. Additionally, it replaces the `DropdownMenuItem` components with simple `button` elements and organizes the code by moving the `PopoverContent` component inside the `Popover` component. These changes simplify the code structure and resolve the scrolling issue reported in the issue description.
Fixes #1696
Before:
https://github.com/open-sauced/app/assets/106407013/7deaeb7b-258b-44a4-9eec-b2d4628ca820
After:
https://github.com/open-sauced/app/assets/106407013/7b1fe39b-8b72-4951-8c82-2b9da7c86f63
=> fix: opening someone's profile menu locks scrollbar and "shifts" header css

components/molecules/HighlightInput/highlight-input-form.tsx
Fixes an issue where the add repository button was missing for smaller screens. The add repo styling needs cleanup, but it's unrelated to this PR. I have a related PR up for that in #1720.
There's one thing that's a little confusing with the flow at the moment though. If the pencil icon shows up and the add highlight input up top is still available, you can still use the desktop flow. I haven't changed this yet @isabensusan because I'd like your feedback on the desktop and mobile flow.
This does unblock #1716 for now though @bdougie.
Fixes #1716
=> fix: now add repo button appears on mobile view

components/molecules/HighlightInput/highlight-input-form.tsx
Update the placeholder text in the HighlightInputForm component to include "Dev.to blog post" as an option.
Fixes #1706
Before:
After:
=> fix: Update placeholder text for Highlight creation

components/atoms/Cmd/command.tsx, components/atoms/Select/multi-select.tsx, npm-shrinkwrap.json, package.json, stories/atoms/multi-select.stories.tsx
This pull request includes the following changes:
- Created command component
- Created multiselect component
- Added multiselect component to design system documentation
I made use of stub data for this testing because I can't find a walk around to implement state updates with the storybook. But the initial idea of the component is to be stateless.
closes https://github.com/open-sauced/app/issues/1672
https://github.com/open-sauced/app/assets/62995161/62c4989e-fd84-483c-9e59-c7b5d7928aac
=> feat: add new`MultiSelect`component to design system

components/organisms/InsightPage/InsightPage.tsx, components/organisms/SuggestedRepoList/suggested-repo-list.tsx, components/organisms/TopNav/top-nav.tsx, layouts/hub.tsx, pages/start.tsx
This PR introduces a new feature that enforces the completion of the onboarding process on the insights page. 
- insights link now shows in nav links for users that have not completed onboarding
- clicking on `insights` for non-onboarded users forces them to complete their onboarding process
- refactored the step for implementation to leverage `queryParams` for more flexible control and optimization
closes #1645 
fixes https://github.com/open-sauced/app/issues/1724
fixes #1728 
https://github.com/open-sauced/app/assets/62995161/6b539e82-7e66-426f-848c-5a868e9d86a2
=> fix: allow not onboarded users to interact with `insights` page

.env, lib/hooks/useSession.ts, lib/utils/feature-access.ts, npm-shrinkwrap.json, package.json, pages/api/session.ts
- Adds feature flag integration using tier.run
- Updates the `.env` with a limited access read-only token and endpoint to tier.run
- Connects the reports feature to the feature access checks
=> feat: add feature flag integration

components/atoms/Search/search.tsx
This PR fixes the bug #1717.
https://github.com/open-sauced/app/assets/11581833/28847259-5aa2-4bf9-bbc7-8fdcbb1a7e1f
=> fix(search): fix search bar bug

next-types.d.ts, pages/hub/lists/new.tsx
- Updates the fields to match the data returned from the API when creating a list
fixes #1743
=> fix: update field mapping for contributor lists create

components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx
This PR fixes the typo. 
-  🐛 Bug Fix
Fixes #1752
=> fix: Fixed a typo 

components/atoms/Search/search.tsx
Update the search input field in the Search component to have a maximum width instead of full width. This change ensures that the input field does not take up the entire width of its container.
Fixes #1744
Before:
https://github.com/open-sauced/app/assets/106407013/4f502432-9205-47cd-8a2a-808635678493
After:
https://github.com/open-sauced/app/assets/106407013/bcff8094-a100-41cb-aef9-49f3790d009b
=> fix: adjust style to prevent shift

components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/HighlightInput/highlight-input-form.tsx
…iting Dialogs
fixed issue #1756: Date Selector not working on Highlight Creation/Editing Dialogs
added pointer-events-auto to PopoverContent's class names.
fixes #1756 
https://github.com/open-sauced/app/assets/114330931/57aca967-d6e5-4803-8611-add6f1f6b1d7
https://github.com/open-sauced/app/assets/114330931/1149b9ff-3d0d-47e1-a376-65a2855fc6b5
s
=> fix: Date Selector not working on Highlight Creation

.prettierignore
- Ignores changelog from getting formatted by prettier as its auto-generated at the moment
=> chore: add changelog to prettier ignore

components/ListHeader/list-header.tsx, components/atoms/ClientOnly/client-only.tsx, components/organisms/ContributorsList/contributors-list.tsx, components/organisms/ContributorsTable/contributors-table.tsx, helpers/fetchApiData.ts, layouts/lists.tsx, lib/hooks/api/useContributorList.ts, lib/hooks/useHasMounted.ts, lib/hooks/useList.ts, next-types.d.ts, pages/lists/[listId]/contributors.tsx, pages/lists/[listId]/overview.tsx
This add the contributors list page. If you want to try it:
1. Grab this PR, e.g. `gh co 1734`
2. Run `npm install`
3. Run `npm run dev`
4. Navigate to http://localhost:3000/lists/2afc5e31-2925-4030-8818-abfaecdbd174/contributors (the list is public)
5. You can also add your own list then navigate to it, http://localhost:3000/hub/lists/new then navigate to http://localhost:3000/lists/your_list_id/contributors
https://github.com/open-sauced/app/assets/833231/ac22edea-388e-46ee-a23c-d17889b7cf9a
* I mention this in the comments, but I wrapped the component with the `<ListPageLayout />` instead of setting it via `ContributorsListPage.Layout = ListPageLayout` because there was data it needed that I couldn't get without two calls on the client-side pre-SSR changes. Now it can receive props. …
=> feat: added contributor page for lists

components/organisms/TopNav/top-nav.tsx
This PR sets `Hacktoberfest` to default topic
=> feat: change hacktoberfest to default topic

components/organisms/ContributorsList/contributors-list.tsx, pages/lists/[listId]/contributors.tsx
A small UI tweak to bring the lists Contributors List feature card view in line with the rest of the app.
**Before**
**After**
Related to #1710
=> fix: made card view for lists contributors list uniform with rest of app

components/organisms/UserSettingsPage/coupon-form.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx, next-types.d.ts
- Adds form to user settings to apply coupon code to user account
- Adds new `coupon_code` property to `DbUser`
- Typo fixes
- Needs https://github.com/open-sauced/api/pull/338
Test codes - account must be a non-upgraded role already.
- sauced1
- sauced2
- sauced3
- sauced4
- sauced5
Closes https://github.com/open-sauced/engineering/issues/114
=> feat: add form to user settings to apply coupon code

components/molecules/CollaborationCard/collaboration-card.tsx, components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/HighlightInput/highlight-input-form.tsx, lib/utils/github.ts, stories/molecules/collaboration-card.stories.tsx, stories/molecules/collaboration-summary-card.stories.tsx
When paging through users in a grid, there was a flash of the GitHub avatar while loading a user's avatar. This isn't necessary as the user will always have an avatar.
**Before**
https://github.com/open-sauced/app/assets/833231/be4ed330-94f4-44c0-9a39-40341e631630
**After**
Fixes #1780
=> fix: removed GitHub avatar when loading user profile avatars

layouts/hub.tsx
This PR refactors the HubLayout component to use the newly added `validatePath` function for pathname validation. The `validatePath` function uses a regular expression to check if the path matches the pattern `/hub/(insights|lists)(/(new|[\d]+/edit))?`. This improves code readability and maintainability by abstracting the validation logic into a separate function. Additionally, it replaces the previous check for `router.pathname.split("/")[3] !== "new"` with the `validatePath` function for consistency.
fixes #1804
=> fix: hide weird top nav for edit insight page

components/atoms/Button/button.tsx, components/organisms/InsightPage/InsightPage.tsx
This PR introduces lazy loading for the `DeleteInsightPageModal` and `TeamMembersConfig` components in the `InsightPage` component. This optimizes the bundle size by deferring the loading of these components until they are actually needed, reducing the initial render time. Additionally, the `useSupabaseAuth` hook now also provides the `user` object, which can be used to redirect the user to the newly created page after successful creation.
closes #1802 
https://github.com/open-sauced/app/assets/62995161/77acb296-8650-43e8-a290-c8dfa59bf64f
=> refactor: redirect user to newly created insight page after creation

components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx, components/molecules/ContributorListTableRow/contributor-list-table-row.tsx, components/molecules/TableHeader/table-header.tsx, components/organisms/Contributors/contributors.tsx, components/organisms/ContributorsList/contributors-list.tsx, components/organisms/ContributorsTable/contributors-table.tsx, lib/hooks/api/useContributorList.ts, pages/lists/[listId]/contributors.tsx
I came across this while looking at the range filter rework in #1815. Now the range filter works for the grid view.
You can see it working here, https://deploy-preview-1819--oss-insights.netlify.app/lists/23c2ca69-7667-4b6a-ad2e-d402999af310/contributors
Relates to #1734
Fixes #1818
**Before**
**After**
=> fix: now range filter works on list contributors page grid view

components/molecules/HubContributorsHeader/hub-contributors-header.tsx, helpers/fetchApiData.ts, lib/hooks/useFetchAllContributors.ts, pages/hub/lists/new.tsx, pages/lists/[listId]/contributors.tsx, pages/lists/[listId]/overview.tsx
This pull request includes a refactoring of the code to utilize the getServersideProps approach, which improves performance and ensures data is fetched on the server side. 
Contributors data are now fetched serverside and available on initial load with timezones
closes #1820
https://github.com/open-sauced/app/assets/62995161/66546e48-8329-4a7b-83f5-9281ed885a8d
=> refactor: use api timezone options for contributors filter

components/organisms/TopNav/top-nav.tsx
This PR re-introduces the changes made in https://github.com/open-sauced/app/pull/1722
fixes https://github.com/open-sauced/app/issues/1645
=> fix: show insight link for not onboarded users

pages/hub/lists/new.tsx
- Updates the GitHub API request to use the users following endpoint
- Allows the unauthenticated request to be made
- Displays an error only if the user session is not present
Related to https://github.com/open-sauced/engineering/issues/162
=> fix: update GitHub API request for user following

lib/hooks/useSession.ts
- This disables the extra session check for feature access, due to perceive slowness.
- Will revisit the integration soon to check for optimizations that can be made.
Closes https://github.com/open-sauced/engineering/issues/156
=> fix: disable tier session check

components/atoms/NotificationsCard/notification-card.tsx, components/molecules/ConnectionCard/connection-card.tsx, components/molecules/ConnectionSummaryCard/connection-summary-card.tsx, components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, components/organisms/ConnectionRequestWrapper/connection-requests-wrapper.tsx, components/organisms/ContributorProfilePage/contributor-profile-page.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx, lib/hooks/updateEmailPreference.ts, lib/hooks/useUserConnections.ts, next-types.d.ts, pages/feed/index.tsx, stories/atoms/notification-card.stories.tsx, stories/molecules/collaboration-card.stories.tsx, stories/molecules/collaboration-summary-card.stories.tsx
This PR updates all `collaboration` copy to `connection`
=> refactor: update all collaboration copy to connection

.github/workflows/release.yml, README.md, components/molecules/RecommendedRepoCard/recommended-repo-card.tsx, components/organisms/InsightPage/InsightPage.tsx, package.json, pages/_app.tsx, stories/atoms/text-input.stories.tsx, stories/atoms/typography-wrapper.stories.tsx, tests/lib/utils/github.test.ts
- Updates text occurrences of `insights` to `app`
=> chore: update occurrences of insights to app

netlify.toml
- Redirects `beta.insights` page requests to `beta.app`
=> chore: add redirects for beta deployments

components/atoms/Select/multi-select.tsx, components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, lib/hooks/useList.ts
This PR:
- adds a new dropdown to add users to multiple lists
We can currently add a user multiple times to a list... but I believe @jpmcb is working on a fix for that on the API side of things. Also, the UX is not completely at it yet, but we can have follow-ups to straighten things up with the UX.
closes #1828
=> feat: add `Add to list` dropdown to user profile

npm-shrinkwrap.json, package.json
This PR enables the posthog feedback survey widget
closes #1746
=> feat: upgrade posthog version to support posthog survey feedback

layouts/hub.tsx
This PR adds the hub lists link to the hub layout nav and updates the CTA copy for add list and insight
fixes #1855 
fixes #1854
=> fix: show link to hub list page in nav

components/molecules/HubContributorsHeader/hub-contributors-header.tsx, components/organisms/ContributorsTable/contributors-table.tsx, lib/hooks/useFetchAllContributors.ts, pages/hub/lists/find.tsx
- Adds search by contributor login to contributors filters
- Needs https://github.com/open-sauced/api/pull/364
Closes https://github.com/open-sauced/app/issues/1860
=> feat: add contributor search to list contributors

components/molecules/InsightRow/insight-row.tsx, interfaces/global-state-types.ts, lib/store/index.ts, next-types.d.ts, pages/hub/insights/index.tsx
- Displays a toast dialog when visiting the insights hub and the contributor has never created an insight page
- Allows the dialog to be dismissed or visit the first featured insight page
- Depends on https://github.com/open-sauced/api/pull/361
Closes https://github.com/open-sauced/app/issues/1673
=> feat: display featured insight pages to new contributors

e2e-tests/UnsignedUsersRedirects.spec.ts
- Increases the timeout for e2e tests in case the job is slow
=> test: increase timeout for e2e tests

components/molecules/ContributionsTreemap/contributions-treemap.tsx
Now the treemap graph on the list activity page appears on small screens.
**Before**
**After**
Fixes #1871 
Relates to #1853
=> fix: now treemap on list activity page appears on small screens

lib/hooks/api/useContributionsByProject.ts, lib/hooks/api/useContributorList.ts, lib/hooks/api/useContributorsByProject.ts, lib/hooks/api/useMostActiveContributors.ts
- Adds checks for listId to hooks to prevent requests with an undefined value
=> fix: add check for listId to hooks

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
=> fix: add target for the link

pages/_app.tsx
- Attempts to clear any leftover service workers registered from previous iterations of `app.opensauced.pizza`
=> fix: attempt to clear any preset service workers

pages/hub/lists/index.tsx
removed the empty state content while loading by adding the isLoading condition.
- [*] 🐛 Bug Fix
Fixes #1884
- [*] 🙅 no, because they aren't needed
=> fix: Added isLoading condition to the title

components/organisms/ContributorProfilePage/contributor-profile-page.tsx
This PR addresses an issue related to the responsiveness of the contributor profile page. It ensures that the page adapts appropriately to different screen sizes, providing a silk experience.
Fixes #1566
Before:
https://github.com/open-sauced/app/assets/106407013/0dbb8ff0-4813-4ae9-b81d-379f3ab63bf5
After:
https://github.com/open-sauced/app/assets/106407013/4550e3df-f1a2-4d17-b728-1978a25c18fc
=> fix: add responsiveness to profile detail

layouts/hub.tsx
A small tweak to the active navigation item in the hub navigation.
**Before**
**After**
Fixes #1922
=> fix: made active tab forecolor more prominent for hub navigation

layouts/hub.tsx
This PR removes the hub header in create insights page
fixes #1922
=> fix: hide secondary header in create insights page

components/atoms/Tooltip/tooltip.tsx, components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx
@isabensusan noticed that tooltips appearing across the app were slow. Before the delay was 700ms. Now it's 300ms.
**Before**
**After**
Fixes #1924
=> fix: decreased delay time of tooltips

.github/workflows/issue.yml
=> feat: issue support

components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx
Fixed label keys appearing in the most active contributors graph bar tooltips.
You can see the fix at https://deploy-preview-1927--oss-insights.netlify.app/lists/fbaf2278-69e9-4a2f-9ccc-8dc67af5177e/activity
Fixes #1928
**Before**
**After**
=> fix: now legend labels in most active graph tooltip render properly

components/ListHeader/list-header.tsx, layouts/lists.tsx
This PR is a fix for the list header range filter overflow issue
fixes #1940
=> fix: list header misalignment now properly aligned

components/molecules/HubContributorsHeader/hub-contributors-header.tsx
Updated the text of the button to "Create List" from "Add to List +" so that it matches the button action. Previously,
when you click the "Add to list" button, it creates the list.
Closes #1935
Before 
https://github.com/open-sauced/app/assets/73622805/6c8e8e9b-2ecb-4012-b82c-5bf144be0446
After
=> fix: Modify Button Text

.github/workflows/triage.yml
Versions the take-action so that we don't get unexpected surprises like https://github.com/bdougie/take-action/pull/25.
Closes #1946
=> chore: adds a version to the take action

pages/hub/lists/new.tsx
This PR fixes the horizontal padding /spacing on smaller screens for the **Create New List** form at `/hub/lists/new` page.
Fixes #1895
**Before the change**
https://github.com/open-sauced/app/assets/27571141/cbe2731a-bccd-46c8-a273-057f18bd9200
**After the change**
https://github.com/open-sauced/app/assets/27571141/4d7d5f9c-e899-4fb5-85f1-50f0c82245b4
=> fix: Fix horizontal padding /spacing on smaller screens for the Create New List form

pages/hub/lists/index.tsx
In this PR I worked on the typo error by changing the word from `loose` to `lose` in the hub/list delete modal.
Fixes #1937
Before 
After
=> fix: remove typo error

pages/_app.tsx, styles/globals.css
Removes the chatbot from the app. No screenshots because the chatbot doesn't appear in dev, but once I removed the useEffects, I saw it appear until I removed the scripts to bootstrap it.
Fixes #1971
=> fix: removed chatbot

lib/utils/analytics.ts
Adds the missing info `is_maintainer` for Posthog.
Relates to #1794
=> fix: added missing is_maintainer info for Posthog

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, pages/start.tsx, stories/atoms/notification-card.stories.tsx
Changed the word "collaborate" to "connect" from all revelent places in the code.
Fixes #1970
=> chore: replace collaborate with connect

components/atoms/Avatar/avatar-hover-card.tsx, components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
Adds hovercards to the list contributors page.
Closes #1953
**Before**
**After**
=> feat: add hovercards to list contributors page

netlify.toml
Modified the build command to use 'npm run build'.
Fixes #1483
=> fix: add build command to Netlify `.toml` configuration

components/molecules/ContributorHighlight/contributor-highlight-card.tsx, pages/feed/index.tsx
This PR fixes the issue with multiple calls being sent to the api even when they are not currently needed. the `useFollowUser` call has been made to only fetch when a highlight dropdown is opened, and as a result the calls won't kick in as it use to before this changes until a user clicks on a single highlight more menu option.
I also removed the top users panel entirely from the DOM if we are on mobile to prevent making a call to check for user follows
Fixes #1950
https://github.com/open-sauced/app/assets/62995161/894e6f7a-7efb-400d-bf7b-697b25f3c288
https://github.com/open-sauced/app/assets/62995161/56474dd1-3dff-4241-b78f-b5949f69b8e6
=> fix: No more 404 errors in the browser console

components/atoms/UserCard/user-card.tsx
This PR links the users avatar in feeds page to their profile page
fixes #1981 
https://github.com/open-sauced/app/assets/62995161/b0b915a2-77d3-4f7f-aaa3-25ffe964a9f2
=> fix: link user avatar on feeds page to their profile

components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/HighlightInput/highlight-input-form.tsx
This PR is a hacky fix to the radix popover and dialog issue in safari
- refactored the popover to use a predefined `useState` to handle the open and close state manually
- set the open state to `true` on icon click
- added a `mousedown` event listener to the document to know detect when a user clicks outside the popover content so i can set the open state to `false`.
- also added an addition `useEffect` to set the open state to `false` when users select a date( can be reverted if it is not necessary)
fixes #1144
https://github.com/open-sauced/app/assets/62995161/cb11c435-9bf8-4e61-860b-910c8535f882
https://github.com/open-sauced/app/assets/62995161/ea14a093-a818-4da5-9bff-796b8e6ff265
=> fix: popover display issue of safari

components/organisms/ConnectionRequestWrapper/connection-requests-wrapper.tsx
This PR adds a placeholder when a user have no pending request
closes #1966
=> fix: add placeholder for 0 pending connection request

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, components/molecules/InsightPageCard/insight-page-card.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, lib/utils/copy-to-clipboard.ts
This PR adds a new experience for non-logged-in users profiles.
- adds a new jumbotron to prompt users to invite or claim an account
- refactors clipboard function to utils
closes #1675
=> feat:  implement improved UX for non-connected users profile

components/atoms/Select/multi-select.tsx, components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
This PR fixes a weird bug in the user profile CTA overlap in safari
fixes #1964
=> fix: more menu overlap issue on safari

components/atoms/TextInput/text-input.tsx
The background color of all text-input where white by default. I have changed it to inherit.
So, now every input field will have same color as its parent element.
Fixes #1994
=> fix: background color in text-input

components/molecules/HighlightInput/highlight-input-form.tsx
Error messages in the highlight form were not notifying assistive tech like a screen reader. I came across this while a new error message was added in #2007.
I'm not sure how to record my screen with Voice Over on, but I can confirm it alerts the screen reader now.
Fixes #2009
=> fix: now the error message in highlight form will alert assistive tech

components/atoms/Avatar/avatar-hover-card.tsx, components/molecules/ContributorListTableRow/contributor-list-table-row.tsx, components/molecules/DevProfile/dev-profile.tsx
This PR fixes the issue with contributors info on the contributors table not displaying
fixes #2011
=> fix: show contributors name and company in table

netlify.toml
Removed build commands from netlify.toml file.
Fixes #2017
Not needed
=> fix: remove build commands from netlify.toml

components/organisms/InsightPage/InsightPage.tsx, pages/hub/insights/new.tsx
- Adds option to sync a GitHub Organization Repos into an insight page during creation
Closes https://github.com/open-sauced/engineering/issues/187
=> feat: add GitHub Org Repository sync to insight page creation

components/organisms/UserSettingsPage/user-settings-page.tsx
Added grey background for delete account section same as danger zone in insights page. 
Fixes #2027
=> feat: add grey background for delete account

components/organisms/UserSettingsPage/user-settings-page.tsx
Changed the lable style to bold and label color similar which was in a little darker and normal font style before.
Fixes #2031
=> fix: change label style of bio to bold

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Changed alignment of avatar and highlight input.
Fixes #1952
=> fix: change avatar alignment with highlight input

components/organisms/ContributorCard/contributor-card.tsx
This PR fixes the chart tooltip cut issue with the contributors card
fixes #1912 
https://github.com/open-sauced/app/assets/62995161/f2188f4b-6ce4-4a2e-8c5d-ee70becccd4c
https://github.com/open-sauced/app/assets/62995161/120661e8-b638-4ec1-84fb-53bff87d62be
=> fix: chart tooltip cut in contributors card

components/molecules/ContributorHighlight/contributor-highlight-card.tsx, stories/atoms/toggle-switch.stories.tsx
This PR fixes the single highlight card issue with the edit dropdown
fixes #2039 
fixes https://github.com/open-sauced/app/issues/1896
https://github.com/open-sauced/app/assets/62995161/699cb4da-7014-4b5f-80c4-6275c68c1091
=> fix: dropdown flickery on single highlight card

lib/hooks/useInsightMembers.ts, lib/utils/get-insight-team-member.ts, pages/hub/insights/[insightId]/edit.tsx, pages/pages/[userOrg]/[pageId]/[toolName].tsx, pages/pages/[userOrg]/[pageId]/[toolName]/filter/[...selectedFilter].tsx
- Fixes an issue where an insight page team member can't access a private insight page unless they created it
Steps to confirm:
1. Create an insight page, marked as private
2. Edit the insight page
3. Invite a team member, accept the team member invite using `/hub/insights/{insightId}/accept?id={inviteId}`
4. After the team member accepts the invite, login as that user, go to the insights list
5. View/Edit the insight page
Closes #2048
=> fix: add check to allow team member access for private insight pages

components/molecules/HighlightCard/highlight-card.tsx
Some insights dashboard tweaks @isabensusan, @OgDev-01 and myself did during todays sync.
Fixes #2065
**Before**
**After**
=> fix: fix Insights dashboard cards styling

components/molecules/Pagination/pagination.tsx
Fixes #2072
Relates to #1977
**Before**
**After**
=> fix: fixed keyboard navigation for pagination

components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx, pages/lists/[listId]/activity.tsx
This PR fixes the issue with top contributor in list most active contributors chart
fixes #2042
https://github.com/open-sauced/app/assets/62995161/34a70a92-834c-4a06-9a24-28aa15bc6ee3
=> fix: top contributor is now updated with filters in list graph

.eslintrc.json
Adds the [no-debugger](https://eslint.org/docs/latest/rules/no-debugger) eslint rule to the project. We should probably look at using the eslint recommended rules along with what we currently have. That's a future discussion though.
Fixes #2082
=> chore: added no-debugger eslint rule

components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx
Fixes #2076
**Before**
**After**
=> fix: stats appear in tooltips now for most active contributors graph

components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx
This PR is a small add-on to @nickytonline 's changes to the most-active contributors chart tooltip, it provides some extra styling.
Fixes #2081 
Before
After
=> fix: styling details on chart tooltip

components/molecules/HighlightInput/highlight-input-form.tsx
This PR fixes a strange ui breaks with the create highlight dialog 
fixes #2086 
https://github.com/open-sauced/app/assets/62995161/83a1cada-12c4-402c-90ad-8b3e0e38dbfd
=> fix: new highlight dialog ui breaks now fixed

components/molecules/HighlightCard/highlight-card.tsx
Change Merged PRs bar color to purple.
Fixes #2104
=> fix: change red color to purple in merged pr bar

pages/hub/lists/index.tsx
Fixes #2107
**Before**
**After**
It's centered horizontally on mobile, the screenshot is just cut off.
=> fix: fixed styling of delete list modal

components/organisms/RepositoriesCart/repositories-cart.tsx, lib/hooks/api/useRepositories.ts, pages/hub/insights/[insightId]/edit.tsx
This PR adds a temporary fix to enable users see up to 50 repos when editing a list. This also adds a max width to the cart item wrapper with an over-flow scroll to enable users scroll through a large list without spoiling.g the experience
fixes #1751 
https://github.com/open-sauced/app/assets/62995161/8a7f5a52-02a3-41be-a733-4fefd2f27fba
=> fix: insights edit repo list limit

components/atoms/Dropdown/dropdown.tsx
This PR replaces hardcoded px value - `min-w-[8rem]` with appropriate tailwind class - `min-w-max` in **DropdownMenuContent** sub component of **Dropdown** component  - `components\atoms\Dropdown\dropdown.tsx`.
I did a quick analysis to find the files where **DropdownMenuContent** is used:
So, the pages that have to be tested for this change are:
1. `user/[username]/index.tsx`
2. `feed/index.tsx`
3. `lists/[listId]/activity.tsx`
Closes #2090
**Recordings of screens before the refactor**
1. `user/[username]/index.tsx`
https://github.com/open-sauced/app/assets/27571141/a853b330-eaa7-4b35-83d8-d4cbc410115c
2. `feed/index.tsx`
https://github.com/open-sauced/app/assets/27571141/2fa49333-d03f-4b7a-a3c0-2b6d700ba59e
3. `lists/[listId]/activity.tsx` …
=> refactor: Replace hardcoded px value with appropriate tailwind class in Dropdown component 

pages/lists/[listId]/activity.tsx, pages/lists/[listId]/contributors.tsx
This was initally omitted for the Product Hunt launch, but should have been added to all pages as part of #1977. Now all list pages have the Edit List button.
Fixes #2123
=> fix: added Edit List button to all list pages

components/molecules/InsightRow/insight-row.tsx, components/molecules/ListCard/list-card.tsx
Some polish to the insights and lists lists in your pages section.
Fixes #2132
**Before**
**After**
=> fix: styling updates to lists of insights/lists

components/molecules/TableHeader/table-header.tsx, components/organisms/Activity/activity.tsx, components/organisms/Dashboard/dashboard.tsx, components/organisms/Repositories/repositories.tsx, components/organisms/ToolsDisplay/tools-display.tsx, lib/hooks/useNav.ts, pages/[pageId]/[toolName].tsx, pages/pages/[userOrg]/[pageId]/[toolName].tsx
This PR replaces the dashboard scatterplot chart in the tools page to repo table and removes the repositories tab from the tab list
closes #1813
=> feat: replace dashboard scatterplot chart with repositories table

components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx
This PR fixes the wording bug in the Most Active Contributors graph. Changes "Churned" to "Alumni"
Fixes #2109
=> fix: Correct Wording 

middleware.ts, pages/index.tsx
Now redirects on the main route, i.e. `/` are handled in middleware. I've left fallbacks in the actual page to redirect to `/feed` if something goes wrong.
Scenarios:
Not logged in: Redirected to `/feed`
Logged in (not onboarded): Redirected to `/feed`
Logged in (onboarded): Redirected to `/hub/insights`.
Please take it for a test run to ensure the scenarios above work for you as well. For not onboarded you can debug and fake it or reset your onboarded status in the dev database.
Fixes #1918
=> fix: now main index page handles redirects in middleware

components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx
This PR fixes the repo table pr velocity chart display i inaccuracy issue
fixes #2097
=> fix: pr overviews in repo table now accurate

components/atoms/Avatar/avatar-hover-card.tsx
This PR fixes the issue with hovercard in the app
The `asChild` props exist in the `HoverCardTrigger`
which disables the default auto-trigger and leaves you with the ability to control the trigger yourself. In our case, we didn’t handle it ourselves, and that led to a break in the app as the hover card didn’t trigger anymore. removing the `asChild` prop in https://github.com/open-sauced/app/blob/9800f6185e6b24a6a802e8df39884201509ba8d8/components/atoms/Avatar/avatar-hover-card.tsx#L51-L53 fixed it.
fixes #2138 
https://github.com/open-sauced/app/assets/62995161/a990cc43-77e3-48db-a855-8c9b60ff2ff1
https://github.com/open-sauced/app/assets/62995161/c4dd45cb-49c7-43a0-ac6c-4ce7f8911750
=> fix: hover card now works as expected in all areas

components/ListHeader/list-header.tsx, components/molecules/FilterHeader/filter-header.tsx, components/molecules/InsightHeader/insight-header.tsx, components/molecules/OnboardingButton/onboarding-button.tsx, components/molecules/PageHeader/page-header.tsx, components/organisms/Waitlist/waitlist.tsx, pages/start.tsx, styles/globals.css
Chatted with @isabensusan this morning and we want to have h1-h6 elements have a base style of the CSS generated from `.tracking-tight`.
Fixes #2141
The before is the first few seconds then see it change to the fix. It's anywhere ther is an h1-h6. This is just one example.
=> fix: h1-h6 base style using CSS from .tracking-tight

components/atoms/Checkbox/checkbox.tsx, components/atoms/Cmd/command.tsx, components/atoms/Dropdown/dropdown.tsx, components/atoms/Tabs/tabs.tsx, components/atoms/Toast/toast.tsx, components/molecules/Calendar/calendar.tsx, components/molecules/ContributionsEvolution/contributions-evolution-card.tsx, components/molecules/ContributionsEvolutionByTypeCard/contributions-evolution-by-type-card.tsx, components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx, components/molecules/RecommendedRepoCard/recommended-repo-card.tsx, components/molecules/TeamMembersConfig/team-members-config.tsx, components/organisms/RepositoriesCart/repositories-cart.tsx, components/organisms/TopNav/top-nav.tsx, components/organisms/UserSettingsPage/coupon-form.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx, layouts/hub.tsx, pages/start.tsx, stories/molecules/treemap-prototype/contributor-node.tsx, stories/molecules/treemap-prototype/special-node.tsx, styles/globals.css
Removed redundant styling that font-medium sets.
Fixes #2145
=> fix: removed font-medium classes as the base style for all elements is font-medium

components/organisms/UserSettingsPage/user-settings-page.tsx, next-types.d.ts
- Adds email preference option to opt-out of email product updates
- Needs https://github.com/open-sauced/api/pull/412
Closes https://github.com/open-sauced/engineering/issues/191
=> feat: add ability for user to toggle receiving email product updates

components/molecules/ContributorListTableRow/contributor-list-table-row.tsx, components/molecules/DevProfile/dev-profile.tsx, stories/molecules/contributor-list-table-row.stories.tsx, stories/molecules/dev-profile.stories.tsx
This PR is responsible for moving the last contributed repo from under the contributor name to underneath the last contributed column in the insights table. 
closes #2110 
Since I made some style changes I also created stories for the new style changes.
=> feat: updating last contributed column for insights table

components/molecules/ContributorListTableRow/contributor-list-table-row.tsx, components/molecules/RepoRow/repo-row.tsx, lib/hooks/useContributorPullRequestsChart.ts, lib/utils/get-prs-to-days.ts, pages/user/[username]/index.tsx
- Reverts changes to show last 30 contributions for contributor line graphs back to last (7, 30, 90) days of contributions
BEFORE:
AFTER:
=> fix: show last 30 days for contribution line graphs

CHANGELOG.md, npm-shrinkwrap.json, package.json
=> chore: merge release 1.76.0

components/molecules/TableRepositoryName/table-repository-name.tsx
changed Table Repository Name prop naming 
Fixes #750
=> fix: refactor TableRepositoryName prop naming

components/organisms/UserSettingsPage/user-settings-page.tsx
changed the delete button color to match the UI 
fixes #2134 
Edit:
Before changes:
After changes:
=> fix: changed delete button color to match the ui

components/molecules/TableRepositoryName/table-repository-name.tsx
This reverts commit 2edfa99b21d33cb71e09f8a6c5ec215f37fd3a9c related to #2102. It was causing builds to break.
Relates to #750
=> fix: Revert "fix: refactor TableRepositoryName prop naming (#2102)"

components/atoms/Textarea/text-area.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx
Fixed design of bio section. Replaced in-built textarea with Textarea component.
Fixes #2046
=> fix: use custom text-area component for bio

components/shared/feature-flagged.ts, lib/utils/server/feature-flags.ts, npm-shrinkwrap.json, package.json
Our initial offering of feature flagging for the application. This will be used initially to feature flag a graph in the list activity page that will be in a follow up PR.
Closes #2179
I've created the feature flag `contributions_evolution_by_type` in prod and beta environment, but it'd be good to just make sure everything there is lined up correctly before going to prod.
=> feat: implemented feature flag support

components/organisms/InsightPage/DeleteInsightPageModal.tsx
Fixes #2160 
Before:
After:
After(mobile version):
=> fix: fixed styling of insights delete page modal

pages/lists/[listId]/activity.tsx
Feature flags the Contributions Evolution by Contributor Type graph on the list activity page.
Relates to #1601
=> fix: feature flagged contributions evolution by contributor type graph

layouts/filter.tsx, layouts/hub-page.tsx
This PR fixes the odd links in the app, by checking if the router is ready to push range based on that. 
fix https://github.com/open-sauced/app/issues/2185
https://github.com/open-sauced/app/assets/18273833/d39040d9-efa0-414e-821f-c59ff22b1542
Note: you could jump to 50th second to see the rendering.
https://github.com/open-sauced/app/assets/18273833/6fea6677-541d-4758-a3fd-9910d735ed18
=> fix: broken URL when you are using Range filter

components/atoms/Checkbox/checkbox.tsx, styles/globals.css
Now checkboxes have a more modern look.
Closes #2210
**Before**
**After**
=> fix: made checkbox stroke thicker

components/atoms/LanguagePill/LanguagePill.tsx, components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, components/molecules/FilterHeader/filter-header.tsx, components/organisms/UserRepositoryRecommendations/user-repository-recommendations.tsx, lib/utils/getInterestOptions.ts, lib/utils/getTopicThumbnail.ts, lib/utils/recommendations.ts
I discovered we had an `interestType` inferred type of the interests array and noticed we weren't leveraging it elsewhere and instead we were explicitly typing it elsewhere. A bug was found in #2196 that would have been caught by the TypeScript compiler if we had used the `interestType` everywhere instead of explicitly typing the type elsewhere as it got out of sync with the `interestType`.
- More context available from my blog post about this PR, [TypeScript: Infer Types to Avoid Explicit Types](https://dev.to/nickytonline/infer-types-to-avoid-explicit-types-1pnn)
- Relates to #2168 and also #2196
=> fix: improved type inference of interests and recommendations

pages/lists/[listId]/activity.tsx
Now only list info is loaded on the list activity page. All graph data is pulled on the client-side only now.
Here's a public list loading data for graphs client-side only now, https://deploy-preview-2215--oss-insights.netlify.app/lists/8b371419-6219-4448-9de1-f6293a25f98e/activity?range=30
Fixes #2213
https://github.com/open-sauced/app/assets/833231/75e7e0ae-3c7f-47f1-bff0-98b9743d06f8
=> fix: now list activity graphs only load data client-side

components/atoms/Checkbox/checkbox.tsx, styles/globals.css
Now checkboxes have focus state styling.
Fixes #2149
**Before**
**After**
=> fix: added global styles for checkbox focus state

components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx, components/organisms/ContributorsList/contributors-list.tsx, lib/hooks/api/useContributionsByEvolutionType.ts, lib/hooks/api/useContributionsByProject.ts, lib/hooks/api/useContributorsByProject.ts, pages/lists/[listId]/activity.tsx, pages/lists/[listId]/contributors.tsx
This PR fixes the rerender issue with the list activities and contributors page.
I had to remove the `useEffect` that was used to update the url with the default query when there is no query in the url. Updating the url with the default query is not important as that will always be the state when there is no query. The data where turning out to be incomplete because the range and limit filter had no fallback. I've updated all instance to include a default fallback.
fixes #2211 
https://github.com/open-sauced/app/assets/62995161/439c63d0-3e50-4264-88e3-48af1e775aef
=> fix: list activity and contirbutor page rerender issue

components/molecules/HighlightInput/highlight-input-form.tsx
Now the Highlight form only closes if you press <kbd>ESC</kbd>, click the close button, or submit a highlight successfully.
Fixes #2256
2. Go to the feed, https://deploy-preview-2257--oss-insights.netlify.app/feed
3. Create a new hightlight.
4. Click outside the modal. Notice the modal doesn't close.
5. Press the <kbd>ESC</kbd> key. The modal closes.
6. Repeat steps 1-4. Click the close button at the top right of the modal. The modal closes.
7. Repeat steps 1-4. Create a new highlight with the required fields. Click the post button.
8. The modal closes.
I don't have the Office 365 spell checker @jessehouwing, but if you don't mind taking this for a spin real quick to confirm it's all good with your spell checker, it'd be appreciated. …
=> fix: now the highlight input form closes only if you press ESC or click the close button

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
This PR fixes the design of the add to list action menu when it is empty.
Fixes #2232 
Before:
After:
=> fix: add to list action menu needs better design when empty

.eslintrc.json, components/atoms/Select/limit-select.tsx, components/molecules/TableHeader/table-header.tsx, components/organisms/ToolList/nav.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx, lib/hooks/update-user.ts, lib/hooks/useFetchAllContributors.ts, lib/hooks/useFetchAllHighlights.ts, lib/hooks/useFetchAllListContributors.ts, lib/hooks/useFetchFollowingHighlightRepos.ts, lib/hooks/useFetchFollowingHighlights.ts, lib/hooks/useFetchHiglightRepos.ts, lib/hooks/useFetchOrgRecommendations.ts, lib/hooks/useFetchSingleHighlight.ts, lib/hooks/useFetchUserHighlights.ts, lib/hooks/useUserConnections.ts, npm-shrinkwrap.json, package.json, pages/feed/index.tsx, pages/start.tsx
Now all types are Pascal cased which is pretty standard for TypeScript. We had about a dozen that weren't Pascal cased and the ESLint rule introduced will enforce that now.
**All the code changes are literally just making the types Pascal cased. Thank you TypeScript refactoring. 🫡**
Fixes #2271
Nothing to do as this is just the renaming of types. As long as the build passes, we're all good.
=> fix: now all types are Pascal cased

components/organisms/UserSettingsPage/user-settings-page.tsx
This PR adds some description to the URL field on the profile settings page.
Fixes #2279 
Visiting the profile page should show a description besides the URL input.
=> fix: update url description in profile settings

README.md, components/molecules/AuthSection/auth-section.tsx
- fix the FAQs link
- Clarify the contributors section
- Add Dev to community section
closes #2282
=> fix: add correct path to FAQ link and update readme for contribs and community

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, components/organisms/ContributorProfilePage/contributor-profile-page.tsx
- Displays the contributor URL from user settings on their profile page
BEFORE:
AFTER:
=> fix: show contributor url on profile page

.eslintrc.json, npm-shrinkwrap.json, package.json
- Removes console warnings and errors when running the npm run lint command
=> chore: update eslint dependencies and configuration

components/Graphs/shared/contributor-type-filter.tsx
The Dropdown component from Radix UI uses a library under the hood that removes the scroll-bar from the page, which also restricts scrolling on the page. To fix this we can pass a prop modal={false} to the root element.
Fixes #2252 
**Before**
https://github.com/open-sauced/app/assets/23109390/5707242e-8da3-4774-b1f0-1a814f4d741b
**After**
https://github.com/open-sauced/app/assets/114330931/65b5a71d-6403-42f7-83a4-df2d14818f77
=> fix: #2252 User list activity dropdown scrollbar causes CSS popping

components/organisms/Repositories/repositories.tsx
- Sets the default range to 30 days, and the default limit to 10 for repositories
BEFORE:
AFTER:
- Navigate to deploy preview and go to Explore
- Reload page
- Note only 10 repositories are displayed
=> fix: add default limit and range for repositories list

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
Added `modal={false}` to the root Dropdown component so the site header no longer shifts when opening reactions on a highlight card.
Fixes #2301 
**Before**
[****](https://github.com/open-sauced/app/assets/94627200/2f38f40d-c3a9-4659-8c74-bccf9479ae73)
**After**
https://github.com/open-sauced/app/assets/114330931/9e9ce3c7-402c-4271-b723-8bdc45f07946
=> fix: now site header no longer shifts when opening reactions on a highlight card

styles/globals.css
Adds focus styles for radio buttons and comboboxes.
Relates to #2194
Closes #2320
**Before**
**After**
=> fix: added focus styles for radio buttons and comboboxes

components/organisms/ContributorsTable/contributors-table.tsx
fixes #2332 
https://github.com/open-sauced/app/assets/114330931/a3fbdc64-0f75-4d39-ace5-3e94abd54198
=> fix: Issue #2332 Removed the message "Sorry couldn't find contributors" while the contributor list is loading.

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, components/molecules/ProfileLanguageChart/profile-language-chart.tsx, styles/globals.css
Kicks off some site wide colour contrast fixes starting with the contributor profile. Not that colour contrast issues in the feed in the contributor profile will be sorted in a separte PR as that component is used elsewhere.
Relates to #2342 
Fixes #2346
**Before**
**After**
=> fix: fixed colour contrast issues with contributor profile

components/molecules/NavLinks/nav-links.tsx, components/organisms/TopNav/top-nav.tsx, styles/globals.css
Fixes #2348
**Before**
**After**
1. Go to any page in the app.
2. Notice the top nav links that are not the current link are a darker slate now.
=> fix: fixed colour contrast issues with top navigation

components/atoms/Button/button.stories.tsx, components/atoms/Button/button.tsx
Now there is a `destructive` button variant.
Closes #2355
See it in storybook. It's not used in the codebase yet.
=> feat: created a destructive button variant

components/atoms/Select/single-select.tsx, components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/ContributorHoverCard/contributor-hover-card.tsx, components/molecules/ContributorListTableRow/contributor-list-table-row.tsx, components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, components/molecules/ListCard/list-card.tsx, components/molecules/NivoScatterChart/nivo-scatter-chart.tsx, components/molecules/PageHeader/page-header.stories.tsx, components/molecules/RepoRow/repo-row.tsx, components/molecules/ReposoitoryCartItem/repository-cart-item.tsx, components/molecules/SearchResults/search-results.tsx, components/molecules/WaitlistButton/waitlist-button.tsx, components/organisms/Contributors/contributors.tsx, components/organisms/ContributorsList/contributors-list.tsx, components/organisms/Repositories/repositories.tsx, components/organisms/RepositoriesCart/repositories-cart.tsx, components/organisms/TopNav/top-nav.tsx, components/templates/Loader/loader.tsx, pages/hub/lists/find.tsx, pages/user/notifications.tsx
Removes empty className props in the project.
Fixes #2350
N/A
=> fix: removed empty className props

components/atoms/LanguagePill/LanguagePill.tsx, components/atoms/TextInput/text-input.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx
Fixes colour contrast issues on the user settings page. Note that the delete button styling is still inaccesible. A separate PR for destructive CTAs is in another PR.
Fixes #2352
**Before**
**After**
1. Ensure you're logged in to the app
2. Navigate to https://deploy-preview-2351--oss-insights.netlify.app/user/settings
3. Notice the improve colour contrast.
=> fix: fixed colour contrast issues on user settings page

components/shared/LanguageSwitch/language-switch.tsx
Fixes #2369 
**Before**
**After**
2. Go to the settings page, https://deploy-preview-2370--oss-insights.netlify.app/user/settings
3. Select at least one interest.
4. Gaze in awe at that awesome colour contrast.
=> fix: fixed colour contrast issues with language switch selected state

components/shared/LanguagePill/LanguagePill.tsx, lib/utils/getTopicThumbnail.ts, lib/utils/recommendations.ts
This PR is a quick fix to the build error introduced in #2371
=> fix: quick fix for build error introduced in #2371

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Fixes #2313
**Before**
https://github.com/open-sauced/app/assets/27322879/bf50f22b-a552-44a9-9992-7e7806aaac3c
**After**
https://github.com/open-sauced/app/assets/833231/6b4825d0-8098-4014-ba51-1d9f3865017f
2. Go to a lists's contributors, e.g. http://localhost:3000/lists/14ad90aa-fba8-4521-bafd-167490091b13/contributors
3. Click on the avatar or username of the contributor in the grid.
4. Their user profile loads
5. Click the browser back button.
6. The list's contributors page loads.
=> fix: now you can navigate back to the previous page from a user profile page

components/atoms/SkeletonLoader/skeleton-wrapper.tsx, components/molecules/ContributionsTreemap/contributions-treemap.stories.tsx, components/molecules/ContributionsTreemap/contributions-treemap.tsx, lib/hooks/api/useContributionsByProject.ts, lib/hooks/api/useContributorsByProject.ts, pages/lists/[listId]/activity.tsx
Now the contributions treemap component has a loading view.
Fixes #2384
Relates to #2175
**Before**
https://github.com/open-sauced/app/assets/833231/c14741f0-b9c3-41ee-9c66-58e13d84aff1
**After**
https://github.com/open-sauced/app/assets/833231/4c1c2f0b-c19f-481e-85df-5e99dfd983f7
1. Ensure your're logged in.
2. Navigate to a list activity page, e.g. https://deploy-preview-2383--oss-insights.netlify.app/lists/8b371419-6219-4448-9de1-f6293a25f98e/activity
3. In the treemap, click on a repository.
4. A loading view loads (could be short) instead of the previous view that said Root, 0 Contributors.
=> fix: added contributions treemap loading view

components/molecules/InsightRow/insight-row.tsx, layouts/hub-page.tsx, pages/_app.tsx
This is a quick/hot fix for busting the app-cache on beta (and also production) for changes in #2368 
- Added "?" for insight member access
Related to:
Deploy previews should be 👍🏼 and local deployment 👍🏼 
Will need to do final validation on beta env
=> fix: Hotfix to bust app-cache

components/molecules/TreemapPrototype/contributor-node.tsx, components/molecules/TreemapPrototype/special-node.tsx
`<animated.div />`s have been replaced with `<animated.button />`s so that nodes in the contributions treemap are keyboard navigable and if you press enter when one is focused, it will drill down to the next level.
Fixes #2389 
Relates to #2175
2. Navigate to https://deploy-preview-2388--oss-insights.netlify.app/lists/767e8678-c092-4727-b5ce-d809e851ef53/activity
3. Use the tab key on the list activity page and you will eventually get to the contributions treemap. Keep tabbing and notice the nodes get focus.
4. Press enter and it drills down to the contributor level.
=> fix: activity list contributions treemap nodes are keyboard navigable now

next.config.js
=> fix: fixed releases breaking from SWC by turning it off

next.config.js
This reverts commit 01cb84c44cb6884eca2f676965012d7627ba06bc.
This change was breaking builds on deploy previews and builds all the way to beta. Thiswas an attempt to fix the SWC error of it missing during the 1.81.0 release.
Relates to #2393
=> fix: Revert "fix: fixed releases breaking from SWC by turning it off (#2394)"

components/Graphs/shared/graph-resizer.tsx, components/molecules/ContributionsTreemap/contributions-treemap.tsx, pages/lists/[listId]/activity.tsx
Now the contributions treemap is resizable.
Closes #2402
Relatest to #2175
https://github.com/open-sauced/app/assets/833231/375d5522-c76a-4c81-bcae-37d2321ea2b9
1. Go to a list activity page, e.g. https://deploy-preview-2401--oss-insights.netlify.app/lists/8b371419-6219-4448-9de1-f6293a25f98e/activity
2. For the contributions treemap. notice that there is a resize button in the top right.
3. Click on it and the treemap takes the space of the whole grid row and pushes the other graphs below it.
4. Click the resize button again and it returns everything in the grid to their original positions.
=> feat: now contributions treemap can resize

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
fixes #2408 
I have added a state for the reactions dropdown which checks whether the dropdown is open or closed.
https://github.com/open-sauced/app/assets/114330931/8ed3cfc2-51ba-499d-b8bd-3424b3fe3358
=> fix: Added state for reactions dropdown on highlight cards.

pages/hub/insights/index.tsx
- Fixes an issue with the modal popping up for authenticated users with insights
- The modal should only be displayed once for an unauthenticated user visiting the /hub/insights page.
Closes https://github.com/open-sauced/app/issues/2419
https://github.com/open-sauced/app/assets/42211/994e0cc9-db6f-4a62-8a76-8c705a4b70c8
1. Visit the deploy preview
2. Remove the `dismissFeaturedInsights` from localStorage if present
3. Visit the /hub/insights page as an unauthenticated user
4. See the insights modal
5. Login and redirect back to the insights hub
6. Note there is no modal popup
7. Choose Disconnect from the user settings menu
8. Not there is no modal popup
=> fix: adjust logic for showing insights popup for unauthenticated users

components/organisms/InsightPage/InsightPage.tsx
Fixes #2434
|Before|After|
|-|-|
|![image](https://github.com/open-sauced/app/assets/27003616/bcaa8ea3-16e6-44c1-b747-a441ae78c49e)|![image](https://github.com/open-sauced/app/assets/27003616/b99c148a-25e7-4f8e-b398-96618e86f541)|
=> fix: delete page button on insights edit page passes colour contrast checks now

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
Now OG images in contributor highlight cards can be clicked and take you to the referenced URL in the highlight.
Closes #2445
**Before**
**After**
=> fix: now you can click on a contributor highlight OG image to go to the referenced url

lib/utils/server/feature-flags.ts
Adds a `workspaces` feature flag to the app.
Relates to #2437
Relates to #2448
N/A
=> feat: added the worskpaces feature flag

layouts/hub-page.tsx
This PR fixes the hydration issue on the insights page caused by the layout header that fetches data client-side
fixes #2441
N/A
1. Login and go to any insights page
2. try to refresh the page and check your browsers console
=> fix: hydration error in insights page

middleware.ts
This PR fixes broken lists tab for non-authenticated user by adding lists route from being checked for user's session so that logged out users can access the demo list
fix #2457
Before
After
1. Log out
2.  Go to lists page
3. You can view the demo list and no more getting redirected to feeds page
No
=> fix(middleware): added lists route to be accessible by logged out users

components/shared/ButtonGroup.stories.tsx, components/shared/ButtonGroup.tsx, styles/globals.css
Adds the `<ButtonGroup />` and `<ButtonGroupItem />` components to the project. They're required for #2437.
Closes #2463
N/A but you can check out the [ButtonGroup in Storybook](https://deploy-preview-2464--design-insights.netlify.app/?path=/docs/components-shared-buttongroup--docs).
=> feat: created the ButtonGroup and ButtonGroupItem components

lib/utils/server/feature-flags.ts
Prior to this change, retrieving feature flags did not work in middleware, now they do
Fixes #2466
Relates to #2437
1. For @open-sauced/engineering, ensure you still see the new side bar when you're logged in.
=> fix: now feature flags can be used in middleware

components/molecules/HighlightInput/highlight-input-form.tsx
Update validCharLimit to a boolean
The function validCharLimit was unnecessarily subtracting charCount from highlightLink.length, so I updated the function in order for char limit to always validate properly.
Fixes #2450 
After using auto summary, the button for post is disabled as expected
Create a highlight with this blog post: https://dev.to/opensauced/take-the-first-step-the-open-source-game-15n5 (also, feel free to like that post first 😆)
Use the autosummarize feature
You should see it go over the limit
See the enabled post button
=> fix: update highlights character limit function to better enforce limit rules

pages/lists/[listId]/overview.tsx
This PR adds explainer tooltip to the list overview stats card
fixes #2251 
1. Login and visit https://deploy-preview-2453--oss-insights.netlify.app/lists/e49bcede-dfbc-4f04-9866-f4d06e1bfbe5/overview
2. Hover on the stats card
=> feat: add explainer tooltip to list stats card

.env, components/molecules/ReportsHistory/csv-download.tsx, lib/hooks/api/useContributorPullRequests.ts, lib/hooks/api/usePullRequests.ts, lib/hooks/api/useRepositoryPullRequests.ts, lib/hooks/useListContributions.ts, lib/utils/public-api-fetcher.ts
This upgrades API changes to v2
=> feat: upgrade to V2 API endpoints

pages/api/delete-account.ts
- Uses the correct API endpoint for requesting account deletion
Closes #2429 
1. Login to account
2. Navigate to `/user/settings`
3. Click on Delete account
4. Follow modal instructions
5. Note page redirects to `/account-deleted` page after deletion is successful
=> fix: use correct API endpoint for account deletion

lib/hooks/api/useMostActiveContributors.ts
- Connects the Most Active Contributors graph to the V2 API endpoint
- Adds Reviewed PRs, Issues Created, and Comments to the chart data
=> feat: connect most active contributors graph to API v2 endpoint

next.config.js
Enables sourcemaps for production.
Fixes #2492
Here's source maps enabled in this deploy preview
N/A aside from the build still building and the deployment preview loads up.
1. pull down this PR,`gh co 2493`
2. Run `npm install` to ensure all dependencies are installed.
3. Run `npm run build` to build a production build of the application.
4. Look in the `.next/static/chunks` folder. There are *.js and *.js.map files
=> chore: enabled production sourcemaps

components/shared/AppSidebar/AppSidebar.tsx
Now the repo insight icon is using the correct one.
Fixes #2495
**Before**
**After**
<<img src="https://media1.giphy.com/media/jnmsc0Z910FW6nawKM/giphy.gif"/>
=> fix: fixed repo insights icon in app sidebar

components/organisms/Repositories/repositories.tsx
In repositories table when searching for a repo, without selecting any repo from the search results and pressing enter while focused on the search input will route to current page without any change
This PR fixes  #988
1. Search any repo name
2. Hit enter, nothing should happen because no repo selected from the results below
3. Now select any result
4. Hit enter and it will route to the repo page
NO
=> fix(search): pressing enter when focused on search input routes the page

components/shared/AppSidebar/AppSidebar.tsx, interfaces/global-state-types.ts, lib/store/index.ts, pages/workspaces/[workspaceId]/settings.tsx, pages/workspaces/new.tsx
Fixes an infinite rerender issue in the application sidebar.
This is only in beta at the moment, so I'm going to associate it to an existing issue.
Relates to #2477
1. Ensure you're logged in to the app
2. Navigate to https://deploy-preview-2506--oss-insights.netlify.app/workspaces/new
3. The page shouldn't crash anymore
4. Create a new workspace
5. The workspace is created and the new workspace's name appears in the workspaces dropdown in the app sidebar.
6. Update the name of the newly created workspace and click the `Update Workspace` button.
7. The workspace name gets updated in the dropdown in the app sidebar.
=> fix: now the app sidebar no longer crashes the page

lib/hooks/api/useContributors.ts
This is a very small change reflecting the diff in the v2 API for the `contributors` endpoints. I did not see any hooks for `contributors/insights` so this only updates the `repo` --> `repos` made there.
Closes: https://github.com/open-sauced/app/issues/2509
Related to and followup: https://github.com/open-sauced/api/pull/507
Note the "Contributors" card:
Run locally, point to `alpha.api.opensauced.pizza`, note the "Contributors" card has fresh data.
=> fix: v2 API - Use new "repos" data points in v2 API

components/molecules/ContributionsEvolutionByTypeCard/contributions-evolution-by-type-card.tsx, components/molecules/ContributionsEvolutionByTypeCard/contributions-evolution-by-type.stories.tsx
Small update to use `bucket` instead of time start/ends with new v2 API data types.
Closes: https://github.com/open-sauced/app/issues/2510
Related to v2 API changes in: https://github.com/open-sauced/api/pull/489
Example graph from a list with OpenSauced employees.
Run locally with API pointed at `alpha.api.opensauced.pizza`. Go to a list with users.
=> feat: v2 API - contrib evolution by type integration

components/molecules/ContributionsTreemap/contributions-treemap.stories.tsx, components/molecules/ContributionsTreemap/contributions-treemap.tsx, lib/hooks/api/useContributorsByProject.ts, next-types.d.ts, pages/lists/[listId]/activity.tsx
- Updates useState / onClick to use `repoName` for v2 API's top project contributions graph
- Update contributions-by-projects graph endpoint
Closes: https://github.com/open-sauced/app/issues/2511
Closes: https://github.com/open-sauced/app/issues/2512
Related to: https://github.com/open-sauced/api/pull/488
Related to: https://github.com/open-sauced/api/pull/487
=> feat: V2 API top-project-contributions graph

pages/workspaces/[workspaceId]/settings.tsx
Prior to this PR, if a workspace did not exist or the call to get it errored out, the page would always give a 404 page. Now if it truly isn't found, it still 404s, but if it's an actual error, the error gets thrown.
Relates to #2502
N/A
1. Navigate to a non-existent workspace, e.g. /workspaces/yolo/settings.
2. The page loads with the OpenSauced 404 page.
3. Note, you can't test the crash unless there is a valid crash. 😅
=> fix: now if a workspace settings page has an error, the error page is shown

pages/lists/[listId]/edit.tsx
Addresses and resolves an issue related to navigation after saving a list.
This fix is associated with the following issue:
Fixes #2446 
https://github.com/open-sauced/app/assets/110151059/92223cf4-923f-4751-8cab-e2def1261fcc
1. Ensure you're logged into the application.
2. Navigate to hub/lists.
3. create a list and then save it.
4. after saving the list page redirects to the updated list.
=> fix: navigate to updated list after save

components/shared/AppSidebar/AppSidebar.tsx
Relates to #2437
2. Go to /workspaces/new
3. No settings link should appear, i.e. no cog icon at bottom of the sidebar
4. Create a new workspace.
5. Notice the cog icon appears at the bottom of the sidebar and if you click on it, it goes to the settings page.
=> fix: add a link to the workspace settings page in the app sidebar

pages/_app.tsx
This busts the app cache for users after our V2 API changeover in #2532 
Fixes: https://github.com/open-sauced/app/issues/2543
N/a - will validate when this lands on beta
=> fix: Bust app cache for v2 API changes

components/Workspaces/SearchReposTable.tsx, components/Workspaces/TrackedRepoWizard/SearchByReposStep.stories.tsx, components/Workspaces/TrackedRepoWizard/SearchByReposStep.tsx, components/Workspaces/TrackedRepoWizard/TrackedRepoWizard.tsx, components/Workspaces/TrackedReposModal.tsx, components/Workspaces/TrackedReposTable.stories.tsx, components/Workspaces/TrackedReposTable.tsx, pages/workspaces/[workspaceId]/settings.tsx, pages/workspaces/new.tsx
Now when searching for repositories to be tracked in the search by repositories flow, you can add or remove from your selection of pending tracked repositories.
Previously, I was using Sets (`Set<string>`) since it was just repository names, but now with the option to uncheck a potential repository to be tracked, maps (`Map<string, boolean>`) made more sense.
When the tracked repositories table is updated with pending tracked repositories, only entries that have their value set to `true` will appear in the tracked repositories table.
Relates to #2502
1. Ensure you're logged in to https://deploy-preview-2544--oss-insights.netlify.app/
2. Navigate to https://deploy-preview-2544--oss-insights.netlify.app/workspaces/new
3. Follow the flow of adding tracked repositories:
4. Click the Add …
=> fix: now checkboxes in the search for tracked repositories flow add or remove as expected

components/Workspaces/RepositoryStatCard.stories.tsx, components/Workspaces/RepositoryStatCard.tsx
Introduces the repository stat card component to the project. It can be one of three types, `"pulls"`, `"issues"`, or `"engagement"`.
Closes #2547
**Pull Requests Stats Card**
**Pull Requests Stats Card Loading**
**Issues Stats Card**
**Issues Stats Card Loading**
**Engagement Stats Card**
**Engagement Stats Card Loading**
N/A. See the [Repository Stat Card component in Storybook](https://deploy-preview-2546--design-insights.netlify.app/?path=/docs/components-workspaces-repository-stat-card--docs) as the component isn't being used in the app yet.
=> feat: created the repository stat card component

lib/utils/server/feature-flags.ts
- Fixes an issue where the feature are returned as `undefined` which can't be serialized when used with `getServerSideProps`. We're fetching feature flags for public and private pages where the feature flags would return undefined for public pages, but needs to be `null` for server side props.
=> fix: return null for feature flags server props when feature flags are undefined

components/atoms/Select/select.tsx, components/atoms/Select/single-select.tsx, components/atoms/Select/single.select.stories.tsx, components/shared/DayRangePicker.stories.tsx, components/shared/DayRangePicker.tsx
Closes #2553
N/A [currently it's only in Storybook](https://deploy-preview-2552--design-insights.netlify.app/?path=/docs/components-shared-day-range-picker--docs)
=> feat: created the day range picker component

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx
Closes https://github.com/open-sauced/engineering/issues/231
User profile share
1. Open up browser console
2. Navigate to a user profile whether logged in or logged out
3. Click the `Share` button
4. Note the posthog event with `clicked: profile copied` in the console log
User profile update
1. Open up browser console
2. Navigate to your profile settings `/user/settings`
3. Update your profile and save
4. Note the posthog event with `Updated user profile` in the console log
=> fix: add Posthog events for user profile share and update

lib/hooks/useSearchRepos.ts, lib/utils/github.ts
- Adds a fallback when using the GitHub API endpoint for repositories. If the rate limit is reach, it uses our `/repos/search` endpoint to return the data
- Also fixes some GitHub token issues with not providing the correct bearer token. This impacted the highlight form for AI generation when getting commits from GitHub
- Now the token is added to the headers only if present
Closes #1440 
1. Log in
2. Navigate to `/feed`
3. Open the highlight input form
4. Note the highlight suggestions returned below
=> feat: add fallback to GitHub API repo search and use correct auth

components/Workspaces/TrackedRepoWizard/TrackedRepoWizard.tsx, lib/hooks/useSearchRepos.ts
The search for adding tracked repositories was only sporadically working. I've set the search to debounce now, and there no longer appears to be any odd behaviour when searching for repositories to track.
Relates to #2482
1. Create a new workspace, `/workspaces/new`, or load up an existing workspace via the sidebar dropdown.
2. Click the Add Repositories button
3. Click on the Search Repositories button.
4. Start searching for repositories.
5. You should be able to search over and over and get search results.
=> fix: tracked repositories search works as expected now

sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts
Sentry was logging local development environments that were causing noise in our Sentry dashboard and it was also going against our cap of events. Now it no longer sends events in local development.
Fixes #2567
N/A
N/A
=> fix: disabled Sentry for local development

middleware.ts
Now, if you're logged in, you're redirected to the last workspace you used. If you've never been to a workspace, you'll get redirected to creating one.
Note that once personal workspaces have been implemented, we'll need to rework this to get your personal workspace as the default workspace.
This implementation uses a cookie, but we could consider in the future to store it in the DB. I think a cookie is good enough for now, though.
Closes #2583
N/A
1. Go to `/`
2. You're redirected to `/feed?redirectedFrom=%2F`
1. Go to `/`
2. You're redirected to the first workspace found via the API associated to you.
3. Switch workspaces. You may need to create a new one if you only have one.
4. Go to `/` again.
5. You're redirected to the last workspace you accessed.
=> feat: now when you go to the app home page, if logged in, you're redirected to your last workspace

.npmrc
- Attempts to fix the recurring issues with builds failing due to not installing optional dependencies
=> build: include optional dependencies when installing packages

components/organisms/TopNav/top-nav.tsx
The top navigation bar incorrectly highlights the `Explore` tab while in an Insight page. This PR fixes that with a check against the router.
Fixes #2595 
1. Go to any Insight page
2. Confirm that the top nav has `Insights` is highlighted
=> fix: TopNav highlight if in Insight pages

middleware.ts
Inside `middlware.ts`, adds a check in `getDefaultWorkspaceId()` if the workspaces returned from a fetch is not empty before trying to get the first workspace's ID. Otherwise, return undefined that `getWorkspaceUrl` will use to redirect to `/workspaces/new`
Fixes #2605 
1. Go to index page as user with access to workspaces but have none
2. Should land in `/workspaces/new`
=> fix: redirect to `/workspaces/new` if user has no workspaces

components/molecules/RepoRow/repo-row.tsx, lib/hooks/api/usePullRequestsHistogram.ts
- Connects the repository pull request graph to the v2 API using the histogram endpoint
- More accurately displays open pull requests over the time period (7, 30, 90) days
BEFORE:
AFTER:
=> feat: connect repository pull requests graph to v2 histogram endpoint

components/molecules/HighlightInput/highlight-input-form.tsx
This PR fixes bug brought up in issue #2613
Fixes #2613
https://github.com/open-sauced/app/assets/65904813/004f86bd-9bf9-46e9-bb23-6f779cc50603
=> fix: Now you can't type more than 500 characters for a highlight summary

components/molecules/HighlightInput/highlight-input-form.tsx
- Noticed a bug when checking on performance issues when switching from an insight page to the highlights feed
- If the GitHub request fails, we weren't returning an empty array, causing a runtime error
=> fix: return empty arrays on error when fetching GitHub data

components/Workspaces/TrackedRepoWizard/FilterPastedReposStep.tsx, components/Workspaces/TrackedRepoWizard/PasteReposStep.tsx, components/Workspaces/TrackedRepoWizard/PickReposOrOrgStep.tsx, components/Workspaces/TrackedRepoWizard/TrackedRepoWizard.tsx
Add a new option to `TrackedReposWizard` to allow users to add repositories by pasting them into a text area, each separated into new lines. User can then filter from the added repositories before finalizing the import.
NOTE: repositories are case sensitive when trying to fetch during `Update Workspace`. I added a note on the modal above where the text are so users can see before pasting their list. This means that if there is even only 'one' repo with the wrong cAse, it'll error out adding the entire list. How should we address this? @open-sauced/engineering 
Closes #2603 
https://github.com/open-sauced/app/assets/20603494/0bd8f8f9-6056-48cf-81dd-a0faba11d2b1
1. Go to `/workspaces/new` or `/workspaces/settings`
2. Click `Add repositories`
3. Paste a list of repositories (CASE SENSITIVE) …
=> feat: add repositories to workspace in bulk

components/organisms/Activity/activity.tsx, lib/hooks/api/usePullRequests.ts
- Adds the `distinctAuthors` flag when fetching pull requests for the activity chart
- Adjusts the filter for a merged pr
- Fixes a bug where the range is `NaN` after switching topics
=> feat: use unique contributors for pull requests activity chart

components/Workspaces/TrackedRepoWizard/PasteReposStep.tsx
Allow users to add repositories in bulk using CSV (comma separated values) pasted in the text area. This PR detects whether a comma is in the input, and splits the repositories with a comma as the delimiter.
Relates to #2608
https://github.com/open-sauced/app/assets/20603494/7193c43b-ab61-42cf-b252-4972b4670d9f
=> feat: implement CSV bulk adding

components/Workspaces/TrackedReposModal.tsx
Now the same modal behaviour of clicking outside a modal to closes is applied to the track repositories modal in a workspace.
Relates to #2505
2. Go to `/workspaces/new`
3. Click on the Add Repositories button
4. The tracked repositories modal appears
5. Click outside it.
6. It closes.
=> fix: now a click outside the tracked repositories modal closes the modal

middleware.ts
Now when you navigate to `/workspaces/new` a `workspaceId` cookie is no longer set with the value `new`.
**Note that there is no cleanup code to delete the cookie if it has this value set as this is currently feature flagged for our team only.**
Relates to #2584
1. Clear your cookies for the deployment preview are cleared (go to browser dev tools)
2. Ensure you have at least one workspace
3. Go to that workspace
4. Go to `/workspaces/new`
5. Close your browser
6. Go to `/`
7. You should be redirected to the workspace in step 2 and not `/workspaces/new/repositories
=> fix: now a new workspace (uncreated) won't store a workspaceId cookie

components/molecules/PullRequestOverview/pull-request-overview.tsx
- Updates the percentage number in the PR overview when hovering over each bar (open, closed, merged, draft)
- Sets the default number to open PRs instead of closed PRs
BEFORE:
https://github.com/open-sauced/app/assets/42211/bf88349f-d6d1-4804-bb57-ce0f0dc420bf
AFTER:
https://github.com/open-sauced/app/assets/42211/76787ea1-2f4f-47b2-ac61-51886f1c6482
1. Visit the URL in the deploy preview `pages/brandonroberts/346/dashboard`
2. Hover over the bars for a given repo
3. Note the numbers and percentage change
=> fix: update pr overview count when hovering over each bar

components/Workspaces/TrackedRepoWizard/TrackedRepoWizardLayout.tsx
Relates to #2505
Relates to #2632
2. Go to `/workspaces/new`
3. Click the Add Repositories button
4. Drag the screen around to see it resize like in the attached screenshot.
=> fix: smaller screen tweaks for workspaces tracked repositories modal

.eslintrc.json, components/atoms/Typography/text.tsx, components/atoms/Typography/title.tsx, components/atoms/Typography/typography-wrapper.stories.tsx, npm-shrinkwrap.json, package.json, pages/feed/index.tsx
=> chore: removed prettier intergrations from eslint

pages/workspaces/[workspaceId]/repositories.tsx
Relates to #2438
1. Go to to `/workspaces/new`
2. Open the browser dev tools to the console tab
3. Add some tracked repositories.
4. Create the workspace
5. The dashboard loads without any hydration errors in the console related to hydration, i.e. errors like this.
=> fix: fixed hydration error in workspaces tracked repos dashboard

tsconfig.json
Fixes the ESLint error by adding the next.config.js to the included file in the tsconfig.json
```
/Users/yo/dev/work/app/next.config.js
0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/next.config.js` using `parserOptions.project`: /users/yo/dev/work/app/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
```
Got this …
=> fix: got rid of eslint error for next.js config

components/molecules/HighlightInput/highlight-input-form.tsx
This PR adds a clear error border and message when the highlight is too long. 
Notes: 
I went with adding an extra error span to the existing one so that the too-long error does not block the other errors like the "wrong type of highlight" error when linking an issue.
This is shown in the screenshots below.
Fixes #2560 
1. Click on the "add a highlight to show your work!" input
2. Paste a description that is longer than 500 characters
3. Notice the only feedback is the char count at the bottom right corner of the text box
4. With this PR, notice the border of the text box turns red and there is a msg displayed at the top of the textbox clearly explaining what the error is
=> fix: make a valid highlight link required to post a highlight

components/molecules/FilterCardSelect/filter-card-select.tsx
1. Navigate to {{developerPreviewUrl}}/angular/dashboard/filter/recent
2. Note the custom topic in the selectbox
=> fix: add custom topic to filter select box

components/Workspaces/RepositoryStatCard.tsx
`activity_ratio` was introduced into the stats endpoint recently. Prior to adding it, the assumption was only three properties for engagement stats. Now there is a check to only display the stats we want.
Relates to #2546
Relates to https://github.com/open-sauced/api/pull/553
**Before**
**After**
1. Create or load a workspace and go to the repositories dashboard
2. Notice the stat card for engagement doesn't contain `activity_ratio`.
=> fix: now only the allowed repo stat properties are loaded into stat cards

pages/lists/[listId]/add-contributors.tsx
- Fixes an issue where adding new contributors to a list only providers contributor ids
- Now includes an array of contributor id and login for contributors not in our data
=> fix: send array of id and login when adding list contributors

lib/hooks/useGetOrgRepos.ts
This is a follow up PR for #2505. See https://github.com/open-sauced/app/pull/2630#discussion_r1486346272. Now if there are more than 100 repositories for an org, they are all pulled in via the GH API's paged data.
Relates to #2505
To test this, you need to be a part of an organization with more than 100 repositories. @jpmcb can test this with `kubernetes-sigs`. I tested it locally by changing the page limit. I tested this locally by altering the page limit to force paged data.
2. Create a new workspace or go to an existing workspace
3. Click on the Add repositories button on the settings page/new workspace page
4. Select Import a GitHub organization
5. Select the organization
6. The list of associated repositories appears.
=> fix: now more than 100 repos for an org are loaded for potential tracking

lib/utils/server/cookies.ts, pages/workspaces/[workspaceId]/repositories.tsx, pages/workspaces/[workspaceId]/settings.tsx
Fixes #2647
**Before**
**After**
1. Go to an invalid workspace page
2. Get the error
3. Go to `/`. You're redirected back to a valid workspace. (assuming you have a workspace. If not, create one)
=> fix: now if an error occurs loading a workspace page, the workspaceId cookie is deleted

components/AddContributorsHeader/add-contributors-header.tsx, components/ListHeader/list-header.tsx, components/molecules/ListCard/list-card.tsx, components/shared/AppSidebar/AppSidebar.tsx, components/shared/AppSidebar/InsightsPanel.tsx, layouts/lists.tsx, next.config.js, pages/workspaces/[workspaceId]/contributor-insights/[listId]/activity.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/add-contributors.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/edit.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/highlights.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx, pages/workspaces/[workspaceId]/contributor-insights/find.tsx, pages/workspaces/[workspaceId]/contributor-insights/index.tsx, pages/workspaces/[workspaceId]/contributor-insights/new.tsx
- Adds navigation from workspaces to contributor insights through workspace URLs
- Most of the additions are from duplicating the current hub/* pages into contributor insight pages and updating the links to navigate within workspaces
- Adds support for workspace URLs to shared components
Closes #2652
https://github.com/open-sauced/app/assets/42211/8e1a2fd4-89a9-4999-a0bb-d396fd9b595a
1. Login
2. Navigate to https://deploy-preview-2648--oss-insights.netlify.app/workspaces/new
3. Click on Contributor Insights on the side nav
4. Click on Contributor Insight from the list
5. Visit tabs
6. Create a new contributor insight
=> feat: add contributor insights to workspaces

components/Workspaces/SearchedContributorsTable.tsx, components/Workspaces/TrackedContributorsModal.tsx, components/Workspaces/TrackedContributorsTable.tsx, components/Workspaces/TrackedContributorsWizard/PickContributorStep.tsx, components/Workspaces/TrackedContributorsWizard/PickOptionStep.tsx, components/Workspaces/TrackedContributorsWizard/SearchByContributorsStep.tsx, components/Workspaces/TrackedContributorsWizard/TrackedContributorsWizard.tsx, components/Workspaces/TrackedContributorsWizard/TrackedContributorsWizardLayout.tsx, lib/hooks/api/useGetWorkspaceContributors.ts, lib/hooks/useSearchContributors.ts, lib/utils/workspace-utils.ts, pages/workspaces/[workspaceId]/contributors.tsx, pages/workspaces/[workspaceId]/settings.tsx, pages/workspaces/new.tsx
Implements tracking contributors in Workspaces. There are two parts for basic functionality:
- Add contributors when creating a workspace under `/workspaces/new`
- This will done in a future PR
- add and filter contributors, uses `/v2/users/search?username` endpoint
- other steps to be implemented in future PRs
- Text only, graphs will be implemented in a future PRs
Closes #2643
Relates to #2578 
https://github.com/open-sauced/app/assets/20603494/59712f53-983f-4b03-b248-a8c1fce89aec
=> feat: track contributors in workspaces

components/Workspaces/WorkspaceLayout.tsx, components/organisms/TopNav/top-nav.tsx, components/shared/AppSidebar/AppSidebar.tsx
Implements a button in `WorkspaceLayout` that shows/hides the sidebar. Currently put next to the logo. Placement is temporary until we have a design. By default, the sidebar is visible. Will implement a way to make sidebar state carry between pages.
Closes #2527 
https://github.com/open-sauced/app/assets/20603494/c6875065-dc69-4d46-a273-619f986957d0
1. Go to any `/workspace` page
2. Press the button on the left of the logo in the top nav bar
3. See if the sidebar shows and collapses correctly
=> feat: make app sidebar collapsible

components/Workspaces/WorkspacesTabList.tsx
Removed Activity and Highlights page links from workspaces tab navigation until those pages are implemented.
Relates to #2435
**Before**
**After**
=> fix: removed non-implemented workspace pages

lib/utils/workspace-utils.test.ts, lib/utils/workspace-utils.ts, middleware.ts, pages/workspaces/[workspaceId]/repositories.tsx, pages/workspaces/[workspaceId]/settings.tsx, vitest.config.ts
Now when you visit the root of the app, if you've never gone to a workspace, the initial workspace to be loaded will be your personal workspace.
Relates to 
1. ensure you're logged in
2. Go to https://deploy-preview-2659--oss-insights.netlify.app/
3. You're brought to your personal workspace
4. Switch workspaces
5. Go to https://deploy-preview-2659--oss-insights.netlify.app/
6. You're brought to the last workspace you switched to.
=> feat: now personal workspace is the default workspace

components/Workspaces/TrackedContributorsWizard/FilterPastedContributorsStep.tsx, components/Workspaces/TrackedContributorsWizard/PasteContributorsStep.tsx, components/Workspaces/TrackedContributorsWizard/PickContributorStep.tsx, components/Workspaces/TrackedContributorsWizard/TrackedContributorsWizard.tsx
Implements bulk adding contributors in `TrackedContributorsWizard` that parses users in new lines or as CSV (no file import, just pasting) in a text area.
Closes #2664 
https://github.com/open-sauced/app/assets/20603494/1482a76f-0ad8-4ad2-b5ce-f7a527471cd3
=> feat: bulk add contributors to workspaces

components/molecules/InsightRow/insight-row.tsx, components/organisms/InsightPage/InsightPage.tsx, components/shared/AppSidebar/AppSidebar.tsx, components/shared/AppSidebar/InsightsPanel.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/edit.tsx, pages/workspaces/[workspaceId]/repository-insights/index.tsx, pages/workspaces/[workspaceId]/repository-insights/new.tsx
- Adds creation of repository insights to workspaces
- Allows editing of repository insights from within a workspace
- Navigates to the existing `/pages/{username}/{insightId}/dashboard` route after creation until those routes are migrated over
- Copies existing `/hub/insights` pages with modifications for navigating within workspaces
Related to: https://github.com/open-sauced/app/issues/2654
1. Login
2. Navigate to `/workspaces/new`
3. Click on the + to create a repository insight
4. Create the repository insight
5. Note it navigates to the previous insight page
=> feat: add repository insight creation to workspaces

components/Workspaces/WorkspaceLayout.tsx, components/organisms/TopNav/top-nav.tsx
Now there is a link to the current workspace in the top navigation.
Closes #2675
1. Click on the workspace link in the top navigation
2. It loads the current workspace
3. Notice the Workspace link is orange (active) when the page loads.
1. The workspace link is no in the top navigation.
=> feat: added link for workspace in top nav

components/atoms/Button/button.tsx
- [ ✅] 🐛 Bug Fix
Fixes #2592 
- [ ✅] 🙅 no documentation needed
N/A
=> fix: now disabled button that becomes enabled no longer causes a content layout shift

lib/hooks/api/useGetWorkspaceContributors.ts, pages/workspaces/[workspaceId]/contributors.tsx
Adds table and grid displaying tracked contributors for a user's workspace.
https://github.com/open-sauced/app/assets/20603494/0c0ecec1-ba8f-4cae-a92e-973b642c7391
=> feat: Implement workspace contributor page

components/Workspaces/SearchReposTable.tsx
Relates to #2590
**Before**
**After**
2. Go to an existing workspace settings or create a new workspace.
3. Click the Add Repositories button
4. Select the first option, Search for Repositories
5. Search for `open-sauced` and pick a couple repositories to potentially track
6. From the repostories table, click the label Select repositories in the table header.
7. It checks or unchecks the Select repositories checkbox.
=> fix: now select repositories checkbox has label associated to it

components/atoms/ListNameHeader/list-name-header.tsx, components/molecules/HubContributorsHeader/hub-contributors-header.tsx, next.config.js, pages/workspaces/[workspaceId]/contributor-insights/[listId]/index.tsx, pages/workspaces/[workspaceId]/contributor-insights/find.tsx, pages/workspaces/[workspaceId]/contributor-insights/new.tsx
- Fixes a bug where you can't find contributors from the new contributor insight page inside a workspace
- Wraps create and find contributor pages in a workspace layout
- Adds page redirect to overview (Not sure if this is a bug in Next.js but navigating through a link locally doesn't load the `/workspaces/{workspaceId}/contributor-insights/new` page correctly)
Fixes #2683 
https://github.com/open-sauced/app/assets/42211/03bda25e-3c66-4c48-87da-247e979d801b
=> fix: wrap new contributor insight page in layout and fix redirect

pages/workspaces/[workspaceId]/contributor-insights/index.tsx, pages/workspaces/[workspaceId]/contributor-insights/new.tsx, pages/workspaces/[workspaceId]/contributors.tsx, pages/workspaces/[workspaceId]/repositories.tsx, pages/workspaces/[workspaceId]/settings.tsx
Now instead of giving an HTTP 500 (internal server error) when someone doesn't have access to a workspace page, it returns a 404 (page not found) instead.
Fixes #2693
2. Navigate to e.g. https://deploy-preview-2694--oss-insights.netlify.app/workspaces/ff1160b5-cc32-45de-8e21-dd7b64f84a74/repositories (@brandonroberts workspace). If you're testing @brandonroberts, head to mine, https://deploy-preview-2694--oss-insights.netlify.app/workspaces/3432aaf7-55db-4c2b-9fde-f61604471e21/repositories
3. A 404 page loads
=> fix: now workspace pages that crash when you don't have access to them give a page not found instead

img/icons/interests/angular-new.svg
- Adjusts the size of the Angular logo for the interests on the settings page
1. Login
2. Go to `/user/settings`
3. Note all logos are similar in size
=> fix: update size for Angular logo on user settings page

components/Workspaces/WorkspaceLayout.tsx
Stores `showingSidebar` state in local storage to persist whether the workspace sidebar is collapsed between route changes.
Fixes #2688
=> fix: make workspace sidebar state persistent between route changes

components/Workspaces/SearchedContributorsTable.tsx
I came across this while working on the contributors from tracked repositories flow. Now the select all checkbox has a label associated to it.
Relates to #2578
**Before**
**After**
1. Go to the settings of one of your workspaces, e.g. /workspaces/some-id/settings or create a new workspace.
2. Click on the Add contributors button
3. Search for a contributor and select them
4. Press the label "Selected contributors" associated to the select all checkbox.
5. Clicking the label should check/uncheck the select all checkbox.
=> fix: now select all checkbox in contributors search table has a label

components/Workspaces/WorkspacesTabList.tsx, pages/workspaces/[workspaceId]/contributors.tsx, pages/workspaces/[workspaceId]/repositories.tsx, pages/workspaces/[workspaceId]/settings.tsx
Implements buttons on workspace pages that go to the `/workspaces/[id]/settings` page.
Closes #2668 and #2690 
https://github.com/open-sauced/app/assets/20603494/4b73a438-3664-4e28-9ebf-4ef327a11691
=> feat: Add edit buttons on workspace pages

next-types.d.ts, pages/workspaces/[workspaceId]/settings.tsx
Now a user is unable to delete their personal workspace.
Closes #2653 
**Personal Workspace without Delete in Settings**
**Non-Personal Workspace with Delete in Settings**
1. Navigate to `/`
2. Go to your personal workspace, denoted by `Personal Worskpace` in the workspaces drop down in the sidebar.
3. Go to the settings page, e.g. /workspaces/you-personal-workspace-id/settings
4. Notice there is no Delete Workspace button or Danger Zone.
=> feat: now a user is unable to delete their personal workspace

middleware.ts
Now there is no longer a check in middleware to see if you have the workspaces feature flag enabled or not. Everyone gets access to it.
Fixes #2711
2. Navigate to `/`
3. You're redirected to the last workspace you used. Since this will be the first time on this deploy preview, it should be your personal workspace that loads.
See #2704
=> fix: removed feature flag check for workspaces in middleware

next-types.d.ts, pages/workspaces/[workspaceId]/settings.tsx
Currently, anybody can access a workspace's settings if they are logged in and have the workspace's ID. This PR will add a check that causes a 404 not found error if they are not listed as an owner of the workspace.
=> feat: 404 on workspace settings page if not an owner

components/molecules/AuthSection/auth-section.tsx
- Navigates back to the provided `redirectedFrom` after authenticating through the "Connect to GitHub" button
=> fix: use redirectFrom to navigate after logging in from top menu

components/molecules/WorkspaceRepositoryInsightRow/workspace-repository-insight-row.tsx, components/shared/AppSidebar/AppSidebar.tsx, components/shared/AppSidebar/InsightsPanel.stories.tsx, components/shared/AppSidebar/InsightsPanel.tsx, lib/hooks/api/useWorkspaceContributorInsights.ts, lib/hooks/api/useWorkspaceMembers.ts, lib/hooks/api/useWorkspaceRepositoryInsights.ts, next-types.d.ts, pages/workspaces/[workspaceId]/contributor-insights/find.tsx, pages/workspaces/[workspaceId]/contributor-insights/index.tsx, pages/workspaces/[workspaceId]/contributor-insights/new.tsx, pages/workspaces/[workspaceId]/repository-insights/index.tsx
- Adds new hook to fetch workspace repository insights
- Adds new hook to fetch workspace contributor insights
- Adds new hook to fetch workspace members
- Updates side bar to list repository and contributor insights only for the workspace
- Updates contributor insights list to only display ones for the workspace
- Updates repository insights list to only display ones for the workspace
- Fixes an issue where contributor insights were not being associated to the workspace on creation
BEFORE:
=> feat: only list contributor and repository insights to the workspace

components/shared/AppSidebar/AppSidebar.tsx, styles/globals.css
Now the workspaces dropdown doesn't bleed out from the application sidebar. Note the long workspaces title on pages when you test this is fixed in #2728.
Fixes #2730
**Before**
**After**
2. Go to any of your workspaces or create one.
3. Give it a really long name.
4. Notice the drop down in the sidebar for workspaces doesn't bleed out of the sidebar.
=> fix: now the workspaces dropdown doesn't bleed out from the application sidebar

lib/utils/workspace-utils.ts, middleware.ts, next-types.d.ts, next.config.js
- Adds middleware checks/redirects for `/lists/**`, `/pages/**`, and `/hub/**` URLs
- Lists are redirected to the new workspace URL with the associated workspaceId
- Insight Pages are redirected to the new workspace URL with the associated workspaceId
- /hub/** pages are redirect to the default workspace
- Needs https://github.com/open-sauced/api/pull/584
Fixes #2655 
1. Go to an existing insight page
2. https://deploy-preview-2734--oss-insights.netlify.app/pages/brandonroberts/346/dashboard
3. Note the redirect to the new workspaces URL
---
1. Navigate to an existing list page
2. https://deploy-preview-2734--oss-insights.netlify.app/lists/2ea74136-b092-41fe-a42d-ba403cda876d/overview
3. 3. Note the redirect to the new workspaces URL
=> feat: add redirects for existing insight and list pages

components/organisms/InsightPage/InsightPage.tsx
- Removes management of team members from repository insight pages
- We are going to revisit the ability to assign permissions to individual repository insights
Closes https://github.com/open-sauced/app/issues/2736
BEFORE:
AFTER:
=> fix: remove managing members from repository insights

components/Workspaces/WorkspaceLayout.tsx, components/shared/AppSidebar/AppSidebar.tsx
Now the workspaces sidebar opens over content instead of expanding/collapsing. **Post-workspaces MVP, we'll have it expanding/collpasing for larger breakpoints.**
**Before**
**After**
2. Go to any workspace
3. Notice the side bar pops over content when opened.
=> fix: workspaces sidebar opens over content now

components/molecules/RepoRow/repo-row.tsx
Now the day range is applied to repositories in the repository dashboard.
Fixes #2743
**Before**
**After**
2. Go to any of your workspaces with at least one repo with some activity
3. Change the day range in the repositories dashboard.
4. The data changes according to the day range.
=> fix: now the day range is applied to repositories in the repository dashboard

components/Workspaces/WorkspaceLayout.tsx, components/shared/AppSidebar/AppSidebar.tsx
Now sidebar no longer collapses when using the workspaces dropdown.
Fixes #2745
Relates to #2738
**Before**
**After**
2. Go to any workspace
3. Notice the side bar pops over content when opened.
4. Open the workspaces dropdown in the sidebar.
5. The sidebar no longer closes.
=> fix: now sidebar no longer collapses when using the workspaces dropdown

components/Workspaces/WorkspaceLayout.tsx
Fixes #2739
**Before**
**After**
2. Ensure the app sidebar is open
3. Refresh the page
4. The page loads with the sidebar open without a hydration error.
=> fix: fixed hydration error caused by <AppSidebar /> component

components/Workspaces/RepositoryStatCard.tsx
I chatted with @isabensusan, and she's good with these changes for smaller screens. Not that there is some page padding that needs to be improved for smaller screens, but that's not related to these changes.
Fixes #2752 
**Before**
**After**
2. Go to any workspace repository dashboard page
3. Shrink the browser window and notice that once it's below the medium breakpoint, the repository stat cards take the full width of the screen.
=> fix: small screen tweaks for repository stats cards

components/molecules/CardLineChart/card-line-chart.stories.tsx, components/molecules/CardLineChart/card-line-chart.tsx, components/organisms/ContributorCard/contributor-card.tsx, components/organisms/ContributorProfilePage/contributor-profile-page.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, lib/hooks/useContributorPullRequestsChart.ts
- Fixes a rendering issue with the pull requests chart for a contributor, causing navigation after visiting a user profile to stop working until a page refresh
Fixes https://github.com/open-sauced/app/issues/2656
Fixes https://github.com/open-sauced/app/issues/2622
BEFORE:
https://github.com/open-sauced/app/assets/42211/69fe9d36-75db-46df-82ee-61aca8310f1e
AFTER:
https://github.com/open-sauced/app/assets/42211/93c94ddf-cee4-42b7-bce1-8245832832ce
1. Navigate to the deploy preview
2. Visit a contributor profile - such as /user/brandonroberts
3. Click through the profile tabs for Highlights, Contributions
4. Navigate away from the page
=> fix: move data fetching into card line chart to prevent rendering loop on contributor profile

package.json
- Recommended fix for flakiness when doing releases with semantic-release after the repository was renamed
=> chore: update repository information in package.json

components/Workspaces/WorkspaceVisibilityModal.tsx, lib/utils/workspace-utils.ts, pages/workspaces/[workspaceId]/settings.tsx
Implements a confirmation modal that will allow an owner of a workspace to toggle the workspace's visibility between public and private.
Closes #2700 
Needs https://github.com/open-sauced/api/pull/576
Confirmation modal:
If available:
If not unlocked:
=> feat: toggle workspace visibility in settings

components/Workspaces/WorkspacesTabList.tsx, pages/workspaces/[workspaceId]/settings.tsx
- Removes the tracked contributors tab and settings from the workspace
- Will revisit the tracked contributors tab in the future
Related to: https://github.com/open-sauced/app/issues/2713
BEFORE:
AFTER:
=> fix: remove tracked contributors from workspace dashboard and settings

pages/workspaces/[workspaceId]/contributor-insights/[listId]/add-contributors.tsx
This PR fixes the `addContributorsToList` function needed for the workspace contributors insight's `/add-contributors` page.
Fixes #2754
=> fix: working `addContributorsToList` for contributors insight

components/Workspaces/WorkspaceLayout.tsx, components/shared/AppSidebar/AppSidebar.tsx, next-types.d.ts
Cleans up the styling for the application sidebar.
This should get merged before #2760.
Fixes #2759
**Before**
**After**
2. Go to any workspace.
3. Open the sidebar.
4. Notice the bottom spacing is the sam as the spacing on the left of the sidebar.
=> fix: sidebar style tweaks

pages/workspaces/[workspaceId]/contributor-insights/find.tsx, pages/workspaces/[workspaceId]/contributor-insights/new.tsx
- Fixes an issue where after creating a new contributor insight using GitHub Follow Import or GitHub Contributor Search, a 404 page would be displayed
Fixes https://github.com/open-sauced/app/issues/2765
1. Login
2. Create a new contributor insight
3. Choose GitHub Following Import
4. Import following
5. Note that the navigation happens to the newly created contributor insight instead of a 404
=> fix: use user_list_id from newly created workspace contributor insight

components/molecules/HubContributorsHeader/hub-contributors-header.tsx, components/organisms/InsightPage/InsightPage.tsx, pages/workspaces/[workspaceId]/contributor-insights/find.tsx, pages/workspaces/[workspaceId]/contributor-insights/new.tsx
- Removes visibility toggle from contributor and repository insights
- Fixes a bug with redirecting after creating a repository insight
BEFORE:
AFTER:
=> fix: remove visibility toggle from contributor/repository insight creation

components/TabList/tab-list.tsx, components/Workspaces/WorkspaceHeader.tsx, components/Workspaces/WorkspaceLayout.tsx, components/organisms/RepositoriesTable/repositories-table.tsx, layouts/hub-page.tsx, layouts/lists.tsx, pages/workspaces/[workspaceId]/repositories.tsx
Now workspaces work well for smaller screen experiences.
High-level what was done:
- now 30% width for the first column of the repositories table for large screens only
- Fixed some styling for the tabs list
- Workspaces header was causing issues with long text for workspace names even though it was being truncated already and used ellipsis. Now, the font is smaller on medium and below screens and the max length is smaller on smaller screens.
Fixes #2632
**Before**
**After**
2. Go to any workspace and try it on smaller screens.
3. Notice there is no horizontal scrolling and all the content is visible.
=> fix: smaller screen fixes for workspaces

components/molecules/WorkspaceRepositoryInsightRow/workspace-repository-insight-row.tsx, lib/hooks/api/useWorkspaceRepositoryInsight.ts, pages/workspaces/[workspaceId]/repository-insights/[insightId]/activity.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/contributors.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/dashboard.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/edit.tsx, pages/workspaces/[workspaceId]/repository-insights/index.tsx
Allows for public workspaces with repo insight pages to be public and prevents an additional call to "v2/insights/{id}/repos" (since repos are returned on the insight within the server side props - I don't anticipate this being an issues on the server side since repos are returned really quickly in a left join from the `repos` table. But maybe someone will have an astronomical number of repos in an insight page at some point, then we may reconsider).
Related to and followup for: https://github.com/open-sauced/api/pull/602
Run through the following in 3 scenerios:
1. Run locally
2. Go to a public workspace
3. Go to a insight page in that workspace
Logged in, not logged in, and private workspace
=> feat: Use insight repos already on insights

components/Workspaces/WorkspaceLayout.tsx, components/shared/AppSidebar/AppSidebar.tsx, pages/workspaces/new.tsx
Now when you create a new workspace, the sidebar still will no longer have the home and insights links.
Fixes #2784
Resolves https://opensauced.sentry.io/issues/4947391719/?project=4505082236960768&query=is%3Aunresolved+null&referrer=issue-stream&statsPeriod=90d&stream_index=0
**Before**
**After**
2. Select create a new workspace from the drop down in the sidebar.
3. Notice the home and insights links are not present.
=> fix: fixes the workspace ID being null issue

components/Workspaces/WorkspaceHeader.tsx
- Hides the Edit Workspace button from being displayed unless the logged in user is an assigned owner
Closes https://github.com/open-sauced/app/issues/2787
BEFORE:
AFTER:
1. Login
2. Go to workspaces
3. Switch to a workspace where you aren't the owner
4. Note the edit button is not shown
=> fix: only show workspace edit button for workspace owner

components/organisms/TopNav/top-nav.tsx, middleware.ts
It was discovered that if you weren't onboarded we always redirected to `/feed` from `/` so the redirect to the last accessed workspace would never happen.
Now we no longer redirect to `/feed` if you haven't onboarded.
Fixes #2789
1. Log in
2. Click on the Workspace link in the top nav.
3. You're redirected to the last accessed workspace, even if you haven't completed onboarding.
=> fix: now workspace top nav link works as expected

components/Workspaces/TrackedContributorsTable.tsx, components/Workspaces/TrackedRepoWizard/PickReposOrOrgStep.tsx, components/Workspaces/TrackedReposTable.tsx, components/shared/AppSidebar/AppSidebar.tsx, pages/404.tsx
@bdougie noticed a few locations where the copy for "Github" should be "GitHub". This PR updates the copy. If we want to also update the in function/ in code names, we can also do that.
N/a - followup to release todays workspace release: https://github.com/open-sauced/app/pull/2791
```
rg Github
```
shows only usage of in-code things. Also tried:
```
rg " github "
rg " Github "
rg "github "
rg "Github "
```
=> fix: Corrects copy for Github -> GitHub

components/organisms/TopNav/top-nav.tsx
Fixes #2795
**Before**
**After**
1. Ensure you're logged in and your screen width is at least 1024px wide.
2. Make sure you haven't onboarded or set `onboarded === true` to test in top-nav.tsx
```typescript
{user && onboarded === true && (
<div className="relative lg:hidden">
<Tooltip content="Complete the onboarding" defaultOpen={true}>
<OnboardingButton ariaLabel="Complete the onboarding" />
</Tooltip>
</div>
)}
```
3. The tooltip doesn't appear.
4. Resize your browser window to less than 1024px and refresh the page. The tooltip appears.
=> fix: now the complete the onboarding tooltip only appears on screens smaller than 1024px

pages/workspaces/[workspaceId]/contributor-insights/[listId]/edit.tsx
- Fixes an issue where editing a contributor insight page has two footers
BEFORE:
AFTER:
=> fix: remove duplicate layout on contributor insight edit page

middleware.ts, next-types.d.ts
- Fixes redirects from legacy URLs for insight pages and lists by using the workspace id from the requested resource
Fixes https://github.com/open-sauced/app/issues/2807
1. Open deploy preview
2. Navigate to `pages/brandonroberts/346/dashboard`
3. Note the redirect is successful without a 404
-- 
1. Navigate to `/lists/fbcc8983-a87e-4d9a-b19e-9ac89b171771/overview`
2. Note the redirect is successful without a 404
=> fix: use workspace_id field when redirecting legacy insights and lists

components/Workspaces/InsightUpgradeModal.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx, pages/workspaces/[workspaceId]/settings.tsx
Moves the visibility setting above the upgrade card in the workspace settings. It will show the upgrade modal if the user is not in a PRO workspace.
Closes #2777 
https://github.com/open-sauced/app/assets/20603494/e1e0cfc6-b7ef-4cea-8ed6-cbf83db9dc72
=> fix: Rework workspace visibility flow

components/molecules/AuthSection/auth-section.tsx, components/organisms/TopNav/top-nav.tsx, middleware.ts
~This was not reproducible in a local development and environment. Now, if `redirectFrom` is in the querystring, it redirects to it.~
We're no longer redirecting from `/` for the Workspaces link in the top navigation. I've created `/workspaces` that now redirects to your last accessed workspace.
Fixes #2792
Fixes #2723
1. Log out
2. Log in
3. Go to the feed / "Highlights"
4. Click on the Workspace link in the top navigation.
5. You're redirected to the last workspace accessed or your personal workspace if none was accessed before.
The
=> fix: top navigation workspace link works as expected now

components/molecules/ContributorListTableRow/contributor-list-table-row.tsx, lib/hooks/api/usePullRequestsHistogram.ts
- Updates the contributor pull request chart to use the pr histogram data for showing the last 30 days of contributions
BEFORE:
AFTER:
1. Go to explore page
2. Choose a topic
3. Click on contributors tab
4. Note graphs are populated
=> fix: use pr histogram for contributor pull request activity line chart

pages/workspaces/[workspaceId]/contributor-insights/index.tsx, pages/workspaces/[workspaceId]/repository-insights/index.tsx
Adds a button on an empty workspace insights page that redirects to the relevant `new` page.
Closes #2828
=> fix: add CTA for empty workspace insights page

components/shared/AppSidebar/AppSidebar.tsx
Now the sidebar uses `dvh` units to adjust it's size for parts of the browser viewport that resize dynamically, e.g. address bar disappearing/appearing, etc.
I've tested this on an iPhone, but not Android. @adiati98, or someone with an Android phone, let me know if it resolves the issue. Thanks in advance!
Fixes the height issue in #2834.
https://github.com/open-sauced/app/assets/833231/2fb8be88-4a94-4442-ace4-e7d88cd3bf3d
1. You need to test the deploy preview on an actual phone. Use the QR Code for the deploy preview.
2. Log in.
3. Click on the Workspace link up top.
4. The sidebar should adjust as you scroll and it should also take 100% height.
=> fix: now the sidebar uses dvh for dynamic resizing of the browser

components/shared/AppSidebar/InsightsPanel.tsx
Show All link for insights in the application sidebar had a double left border, fixed it to be aligned with other items.
Fixes #2838
=> fix(insightspanel): fixed border for Show All link in InsightsPanel

lib/utils/caching.ts, lib/utils/server/cookies.test.ts, lib/utils/server/cookies.ts, lib/utils/workspace-utils.test.ts, lib/utils/workspace-utils.ts, middleware.ts, pages/_app.tsx, pages/workspaces/[workspaceId]/contributor-insights/index.tsx, pages/workspaces/[workspaceId]/contributor-insights/new.tsx, pages/workspaces/[workspaceId]/contributors.tsx, pages/workspaces/[workspaceId]/index.tsx, pages/workspaces/[workspaceId]/settings.tsx
Now the workspace ID cookie is only set when a workspace page successfully loads.
Fixes #2822
Ensure you're logged in.
1. Go to a non existent workspace page, https://deploy-preview-2835--oss-insights.netlify.app/workspaces/21c5e583-f1fd-40q3-9ec9-7801f67ff727/yolo
2. The page loads gives a 404
3. Go to a https://deploy-preview-2835--oss-insights.netlify.app/workspaces
5. The last accessed workspace loads fine.
You can compare beta with the same steps and you will get a crash when you go to /workspaces
1. Go to a non existent workspace page, e.g. https://beta.app.opensauced.pizza/workspaces/21c5e583-f1fd-40q3-9ec9-7801f67ff727/yolo
2. The page loads gives a 404
3. Go to a https://beta.app.opensauced.pizza/workspaces
4. The site gives an error.
=> fix: now the workspace ID cookie is set only when a valid workspace page is loaded

components/organisms/InsightPage/InsightPage.tsx
- Fixes an issue where creating a repository insight doesn't redirect to that page afterward
- Removes leftover checks for workspaceId
Fixes #2827
1. Login
2. Go to Repository Insight Page
3. Add Title and Repo
4. Create Insight
5. Note page is redirected to new insight after creation
=> fix: use insight_id when redirecting after creating an insight

components/shared/AppSidebar/InsightsPanel.tsx
Implements copy and button to tell the user that they don't have any contributor/repository insights and to create one, redirect to the `/new` page for their respective sections.
Closes #2852 
1. Go to a workspace with no insights, either contributor or repository
2. Click the `Create` button for that section
3. Ensure that it redirects to the appropriate `/new` page based on the section
=> feat: CTA for empty insight sections in sidebar

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, components/organisms/Contributors/contributors.tsx, lib/hooks/useList.ts
- Fixes an issue where adding a contributor to an existing list fails
- Updates the data payload sent to the API from an array of contributor IDs to and array of objects with `id` and/or `login`
Fixes #2815
1. Login
2. Go to a repository insight
3. Go to the contributors tab
4. Select some contributors
5. Click the Add to List button
6. Select a list
7. Note the contributors are added when visiting the updated list
--
1. Navigate to a contributor profile
2. Click on the menu
3. Click Add to List
4. Selected list(s)
5. Note the contributor is added to the lists
=> fix: update data format when adding contributors to a contributor insight

components/Workspaces/TrackedReposTable.tsx, components/Workspaces/WorkspaceWelcomeModal.tsx, pages/workspaces/[workspaceId]/index.tsx, pages/workspaces/[workspaceId]/settings.tsx
Displays a welcome modal that will greet all users once, implemented with local storage to avoid reshowing once dismissed.
Closes #2724 
1. Open workspace page
2. See modal, and dismiss
3. Reload and confirm the modal NOT showing
=> feat: Welcome modal for new Workspace users

lib/hooks/api/usePullRequestsHistogram.ts
- Fixes the line chart now showing correctly for repos on the explore page
BEFORE:
AFTER:
1. Go the a topic on the explore page `/react`
2. Note the repos on each row have a line chart of the last 30 days that is not a flat line
=> fix: remove topic and filter from histogram requests for specific repos

components/Workspaces/TrackedReposTable.tsx
- Fixes issue where `Add Repositories` button can no longer be clicked
Fixes https://github.com/open-sauced/app/issues/2871
1. Login
2. Go to workspace
3. Click edit
4. Click Add Repositories button under Tracked Repositories section
=> fix: remove z-index from tracked repositories table

README.md, components/molecules/DevCard/dev-card.tsx, components/molecules/HeaderLogo/header-logo.tsx, components/molecules/RepositoryResult/repository-result.tsx, components/molecules/ReposoitoryCartItem/repository-cart-item.stories.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, components/organisms/Footer/footer.tsx, components/organisms/RepositoriesCart/repositories-cart.stories.tsx, components/organisms/Waitlist/waitlist.tsx, pages/[pageId]/[toolName].tsx, pages/[pageId]/[toolName]/filter/[...selectedFilter].tsx, pages/hub/insights/[insightId]/accept.tsx, pages/hub/insights/[insightId]/edit.tsx, pages/hub/insights/index.tsx, pages/hub/insights/new.tsx, pages/hub/lists/index.tsx, pages/pages/[userOrg]/[pageId]/[toolName].tsx, pages/pages/[userOrg]/[pageId]/[toolName]/filter/[...selectedFilter].tsx, pages/start.tsx, pages/workspaces/[workspaceId]/contributor-insights/index.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/activity.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/contributors.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/dashboard.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/edit.tsx, pages/workspaces/[workspaceId]/repository-insights/index.tsx, pages/workspaces/[workspaceId]/repository-insights/new.tsx, pages/workspaces/[workspaceId]/settings.tsx
There were some typos and OpenSauced wasn't camelCased everywhere.
closes #2891
=> fix: typo on modal and create consistency with OpenSauced spacing

pages/workspaces/[workspaceId]/settings.tsx
- Increases z-index of workspace members config so text input and button can be clicked
- Confirmed that other elements on workspace settings are still clickable
- May need to revisit the Upgrade Workspace button as we want to keep it floating but not behind other elements on the page
Fixes https://github.com/open-sauced/app/issues/2893
1. Login
2. Go to workspace settings
3. Go to workspace members section
4. Find a user
5. Click add member
=> fix: increase z-index for workspace members config

middleware.ts
- Fixes an issue where public workspaces were being forwarded to the highlight feed
- This was due to the workspaces URLs flowing through the middleware and falling back to the feed redirect
- This short circuits the response for paths that begin with `/workspaces` through the middleware, letting the permission checks be handled in the page route
Fixes https://github.com/open-sauced/app/issues/2899
1. Visit https://beta.app.opensauced.pizza/pages/brandonroberts/346/dashboard
2. Note the redirect
3. Navigate to https://deploy-preview-2900--oss-insights.netlify.app/pages/brandonroberts/346/dashboard
4. Note the repository insight is displayed
=> fix: short circuit workspace paths through the middleware

components/ListHeader/list-header.tsx, components/Workspaces/StackedOwners.tsx, components/molecules/InsightHeader/insight-header.tsx, layouts/hub-page.tsx, layouts/lists.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/activity.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/highlights.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/activity.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/contributors.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/dashboard.tsx
Adds UI to show the workspace owners' avatars to indicate who has ownership of the contributor/repository insights.
Closes #2851 
https://github.com/open-sauced/app/assets/20603494/5494e735-4a0a-49b1-8fa3-c501b8087d45
=> feat: show owners of insight pages

components/Workspaces/TrackedRepositoryFilter.tsx, components/atoms/Select/multi-select.tsx, components/organisms/Repositories/repositories.tsx, lib/hooks/api/useGetWorkspaceRepositories.ts, lib/hooks/api/useWorkspacesRepoStats.ts, lib/hooks/useSearchTrackedRepos.ts, pages/workspaces/[workspaceId]/index.tsx
Implements a multi select dropdown to the tracked repositories page to filter the table and stats based on selected repositories.
Closes #2581 
https://github.com/open-sauced/app/assets/20603494/5216450f-dd8f-4f47-a8e2-9cc62245ddc3
=> feat: filter tracked repositories in workspace

components/TabList/tab-list.tsx, components/Workspaces/WorkspacesTabList.tsx, layouts/lists.tsx
- Adds a configurable `path` to the tab list to separate the title from the path used in the URL
- Repositories has an empty path on the workspaces dashboard
- Made consistent in contributor list tabs also
Fixes: https://github.com/open-sauced/app/issues/2890
1. Login
2. Go to workspace
3. Click on Repositories
4. Go to workspace settings
5. Click on Repositories
6. Note no 404 happens on navigation
=> fix: add path to tab list array for separate title/URL combinations

components/organisms/InsightPage/InsightPage.tsx, components/organisms/ToolsDisplay/tools-display.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx, interfaces/global-state-types.ts, lib/hooks/useSession.ts, lib/store/index.ts, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/dashboard.tsx
- Removes the `Upgrade Settings` button from the user settings page and associated checks for upgrades based on the role
- Removes the `Manage Subscriptions` button as we'll update those subscriptions manually through Stripe.
- Removes the limit on repos when creating/updating a repository insight. This soft limit is handled at the workspace level now for Pro workspaces
Closes https://github.com/open-sauced/app/issues/2877
BEFORE:
AFTER:
1. Login on a non-upgraded account
2. Go to user settings
3. Note the Upgrade Access button is not present
=> feat: remove upgrade access button from user settings

layouts/hub-page.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/activity.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/contributors.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/dashboard.tsx
- Fixes an issue where the edit button for a repository insight page was not shown to editors and owners of a workspace
- Adds upgrade banner and modal to contributors and activity tabs for an insight
BEFORE:
AFTER:
=> fix: display edit button on repository insights for workspace members

components/organisms/InsightPage/InsightPage.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/activity.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/add-contributors.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/edit.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/highlights.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx, pages/workspaces/[workspaceId]/contributor-insights/index.tsx
This is a followup to https://github.com/open-sauced/api/pull/635
It uses the moved `v2/workspaces` endpoints. These endpoints should more or less be 1:1 with their previous endpoints. I think I got everything covered by the API pr.
Related to https://github.com/open-sauced/api/issues/634
Loads locally and looks good:
1. Workspace works
2. Workspace repo insight works
3. Workspace contrib insight works
=> feat: Use new workspace API workspace access control endpoints

components/organisms/InsightPage/InsightPage.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/edit.tsx
- Removes insight members access check in favor of workspace members access checks for editing a repository insight
1. Go to https://beta.app.opensauced.pizza
2. Login
3. Navigate to https://beta.app.opensauced.pizza/workspaces/286c8ba3-1b1e-4579-b7c5-bb9fd8329f1f/repository-insights/397/edit
4. Note the Unauthorized message
--
1. Go to deploy preview
2. Login
3. Navigate to https://deploy-preview-2905--oss-insights.netlify.app/workspaces/286c8ba3-1b1e-4579-b7c5-bb9fd8329f1f/repository-insights/397/edit
4. Note the repository insight edit page is displayed
=> fix: use workspace members for checking repository insight edit access

components/shared/AppSidebar/AppSidebar.tsx, components/shared/AppSidebar/InsightsPanel.tsx
Adds `overflow-hidden` to prevent long insight titles to overflow, which also moves the "new insight" dropdown button and the "hide sidebar" button over the panel
Closes #2810 
Closes #2882 
Before:
After:
=> fix: prevent overflow when insights have long titles

pages/workspaces/[workspaceId]/settings.tsx
- Redirects to the workspace dashboard page after successfully updating the workspace settings
Fixes https://github.com/open-sauced/app/issues/2865
1. Login
2. Navigate to a workspace
3. Click the edit button to go to workspace settings
4. Update something on the workspace
5. Click Update Workspace
6. Note the toast message is displayed and navigation goes back to the workspace dashboard
=> fix: redirect to workspaces dashboard after settings update

components/Workspaces/TransferInsightModal.tsx, components/organisms/InsightPage/InsightPage.tsx, lib/hooks/api/useGetUserWorkspaces.ts, pages/workspaces/[workspaceId]/repository-insights/[insightId]/edit.tsx
Implements a new option in the repository insights `/edit` page. Under the "Danger Zone", there will be a new single search select that have all of the user's workspaces that they have owner/editor roles on. User can then choose between them and click transfer to move the current insight to the selected workspace.
Related to #647 
https://github.com/open-sauced/app/assets/20603494/aae437d9-6754-44d5-a748-4dec95d17363
1. Ensure you have a workspace to move to
2. Go to a repository insight's edit page
3. Choose a workspace to move to and click `Transfer`
4. Check that you are redirected to the insight's dashboard
5. Open to sidebar and ensure you are in the destination workspace
=> feat: transfer repository insights to other workspace

lib/utils/caching.ts
Busts app cache for workspaces MVP release to prod
Related to various tickets modifying local storage
=> chore: Bust app cache for workspaces MVP

components/organisms/InsightPage/InsightPage.tsx
Add empty string else if insight is undefined when passing its name to `TransferInsightModal`
Closes #2920
=> fix: transfer hitting undefined

lib/hooks/api/useGetUserWorkspaces.ts, pages/workspaces/[workspaceId]/contributor-insights/[listId]/edit.tsx
Implements a new option in the contributor insights /edit page. Under the "Danger Zone", there will be a new single search select that have all of the user's workspaces that they have owner/editor roles on. User can then choose between them and click transfer to move the current insight to the selected workspace.
Closes #647 
https://github.com/open-sauced/app/assets/20603494/5fbe4b62-95e5-4a17-99c9-98cd420d5a44
1. Ensure you have a workspace to move to
2. Go to a contributor insight's edit page
3. Choose a workspace to move to and click Transfer
4. Check that you are redirected to the insight's dashboard
5. Open to sidebar and ensure you are in the destination workspace
=> feat: transfer contributor insights to different workspaces

components/Workspaces/InsightUpgradeModal.tsx, components/Workspaces/WorkspaceBanner.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/activity.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/contributors.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/dashboard.tsx
- Captures a PostHog event whenever the workspace upgrade banner is shown
- Captures a PostHog event whenever the workspace upgrade modal is shown
Closes https://github.com/open-sauced/app/issues/2895
1. Login
2. Go to a non-upgraded workspace
3. Create a contributor insight with more than 10 contributors
4. Note the banner displayed
5. See the PostHog event logged in the browser console
=> fix: capture PostHog event for workspace upgrade banner shown and modal clicked

npm-shrinkwrap.json
The shrinkwrap file was out of date.
Closes #2937
N/A aside from the build and deploy for the deploy preview passing successfully.
=> fix: updated npm-shrinkwrap.json with new package name

pages/workspaces/[workspaceId]/repository-insights/index.tsx
Implements a button on the repository insight list page the leads to the `/new` page, directing users to create an insight.
Closes #2887 
Closes #2881
=> feat: add create button on repo insight list page

CHANGELOG.md
* capture PostHog event for workspace upgrade banner shown and modal clicked ([#2927](https://github.com/open-sauced/app/issues/2927)) ([05d168f](https://github.com/open-sauced/app/commit/05d168f22efcedfa255ec456bb58459b4a020a80))
* updated npm-shrinkwrap.json with new package name ([#2936](https://github.com/open-sauced/app/issues/2936)) ([afcfdc2](https://github.com/open-sauced/app/commit/afcfdc29dcb3c7205e23fb265c003a6e9842075d))
* allow URLs when pasting repos ([#2933](https://github.com/open-sauced/app/issues/2933)) ([ede987f](https://github.com/open-sauced/app/commit/ede987f8dee905c3adcbb8a778e35a6d9c665e36))
=> chore: merge main to beta

components/Workspaces/WorkspaceOgImage.tsx, netlify/edge-functions/workspaces-card.tsx
Workspace open graph (OG) image contents load fine now even when a description is missing.
Relates to #2939
**Before**
**After**
=> fix: workspace OG image renders correctly when a description is not present

netlify/edge-functions/workspaces-card.tsx
Now the activity ratio type for mid activity ratio is returned as mid instead of medium which loads the appropriate image and prevents the OG image from crashing.
Relates to #2939
**Before**
**After**
1. Go to https://beta.app.opensauced.pizza/og-images/workspace/6d6d5f96-29af-439a-9d81-a18fa8860295/30?wname=My+Workspace&description=Cool+description on beta.
2. A blank image or white screen loads.
3. Go to https://deploy-preview-2958--oss-insights.netlify.app/og-images/workspace/6d6d5f96-29af-439a-9d81-a18fa8860295/30?wname=My+Workspace&description=Cool+description (the deploy preview)
4. A workspace OG image card for mid activity loads.
=> fix: now activity ratio is named mid instead of medium so OG image for workspace loads

pages/workspaces/[workspaceId]/contributor-insights/[listId]/add-contributors.tsx
This pr fixes an issue where the `add-contributor` page has two footers and some weird padding due to nested layouts.
fixes #2826 
BEFORE:
AFTER:
=> fix: remove duplicate layout on add-contributor in workspaces

components/Workspaces/WorkspaceLayout.tsx
This PR removes the footer from the workspaces paths, enhancing the user experience. I haven't touched the hub layout since visiting those pages redirects me to the workspaces
Fixes #2948 
BEFORE
https://github.com/open-sauced/app/assets/79809121/a03f0b0e-b2ed-405d-bcba-3e9871259356
AFTER
https://github.com/open-sauced/app/assets/79809121/4e928414-0f22-4a6a-9df3-fc822923c43a
1. Log in to the app.
2. Visit your workspaces.
3. Ensure that there is no footer displayed on the workspaces page.
=> refactor: remove footer from workspaces

pages/500.tsx
Adds a custom 500 page to the project. I removed the DEV cards that the custom 404 page has because if there are issues with the site, we don't want the error page to crash.
I went with this copy. Feel free to slice and dice.
`uh oh! looks like there's an issue with the pizza oven`
Closes #2819
1.  Go to this page which contains an invalid workspace ID in the URL, https://deploy-preview-2969--oss-insights.netlify.app/workspaces/332aaf7-55db-4c2b-9fde-f61604471e21
2. You get the custom 500 error page,
=> feat: created the custom 500 page

components/Workspaces/TrackedRepoWizard/SelectOrgReposStep.tsx, components/Workspaces/TrackedRepoWizard/TrackedRepoWizard.tsx
Now, you can search for organizations you don't belong to. If the org does not exist, the search result will not return anything. Existing user organizations remain available and filterable.
Fixes #2874
[![Loom recording for Non-User Org Repo Tracking working](https://github.com/open-sauced/app/assets/833231/cba8b009-acdb-4f4d-8564-d01233b9ddc7)](https://www.loom.com/share/8188983204b5471cae29496eaabf3363?sid=c0049bb6-6d77-4e66-881b-9e689fa2a38d)
1. Go to a workspace you can edit
2. Go to the settings.
3. Click on the add repositories button.
4. Notice the user organizations are available right away.
5. Type in an organization you are not a part of.
6. Notice that if the organization does not exist, no search results appear.
7. If the organization exists, it will be the only organization …
=> fix: now you can use free text to select an organization for tracking repos

components/ListHeader/list-header.tsx, components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, components/molecules/InsightHeader/insight-header.tsx, lib/utils/copy-to-clipboard.ts, lib/utils/shorten-url.ts, pages/workspaces/[workspaceId]/contributor-insights/find.tsx
- Use URL shortener in OpenSauced API to generate a short URL whenever the `Share` button is used before copying to the clipboard
Closes https://github.com/open-sauced/app/issues/522
1. Go to a page with a Share button (contributor insight, repository insight, contributor profile)
2. Click the Share button
3. Upon success the short URL is copied to the clipboard instead of the full page URL
4. If the API request fails for any reason, the original URL is returned
=> feat: use URL shortener when Share button is used

components/primitives/drawer-primitives.tsx, components/shared/Drawer.stories.tsx, components/shared/Drawer.tsx, npm-shrinkwrap.json, package.json, styles/globals.css
Introduces a new drawer component that can be used on it's own for smaller screen size experiences. It will also be used for a new dialog component in #2853.
Relates to #2853
You can swipe the drawer away, click close to close it, or click or tap outside the drawer to close it.
https://github.com/open-sauced/app/assets/833231/e622ba46-7eca-4ae6-9be7-f222604d2d4f
1. Visit https://deploy-preview-2992--design-insights.netlify.app/?path=/docs/components-shared-drawer--docs to take the component for a test drive.
=> feat: drawer component

npm-shrinkwrap.json, package.json
=> feat: bump to 2.10.0

components/atoms/Icon/icon.tsx
This PR fixes the bug of ```Icon``` component that has default alt text "Icon", this PR removes the default alt text.
Fixes #3010
There are no visual changes
=> fix: Icon image has a default alt text "Icon"

components/molecules/AnnouncementCard/announcement-card.tsx, components/molecules/FeaturedHighlightsPanel/featured-highlights-panel.tsx, components/molecules/HighlightsFeedCard/highlights-filter-card.tsx, components/molecules/NewsletterForm/newsletter-form.tsx, components/molecules/TopContributorsPanel/top-contributors-panel.tsx
This fix came about while writing some E2E tests. Now that they have semantic meaning, it's easier to find them in an E2E test.
Fixes #3016
1. Go to the home page and you should still see all the relevant areas like Top Contributors, Repositories etc.
=> fix: now some divs on main page are aside elements

components/Workspaces/WorkspaceHeader.tsx
Implements a share button in the `WorkspaceHeader` that will copy a shortened URL to the user's clipboard
Closes #3024 
1. Go to a workspace
2. Click the share button
3. Paste somewhere and confirm it's a shortened link
=> feat: add share button to workspaces

components/Workspaces/TrackedRepoWizard/TrackedRepoWizard.tsx
Now a valid searched org appears all the time for org import for tracked repositories. In cases where it matches with your user orgs, they will all appear. See screen recordings.
Fixes https://github.com/open-sauced/app/issues/3035
**Before**
**After**
1. Go to a workspace settings page for a workspace you own, e.g. /workspaces/some-workspace-id/settings
2. Click on the add tracked repositories button.
3. Click on the Import at GitHub Organization button in the modal.
4. Search for a valid org that contains part of the name of one of your user orgs.
5. Notice your user org appears along with the org you were looking for.
=> fix: now valid searched org appears all the time for org import for tracked repositories

pages/workspaces/[workspaceId]/contributor-insights/new.tsx
- Switches the name input field to a controlled input to capture the query param or manual entry
- Fixes #3043
1. Login
2. Create a contributor insight
3. Enter some text in the input field
4. Note the input field receives text
=> fix: use controlled input on new contributor insight

components/Workspaces/TrackedContributorsTable.tsx, components/Workspaces/TrackedReposTable.tsx, pages/workspaces/[workspaceId]/contributor-insights/new.tsx, pages/workspaces/[workspaceId]/repository-insights/new.tsx
This pr disables the buttons `create insight`,`add repo/contrib` and `trash icon` for both create new repository/contributor insight. This change helps prevent duplicate entries.
Fixes #3056 
BEFORE
https://github.com/open-sauced/app/assets/79809121/cf2f9ce2-5d34-4988-a6c5-86bd3a27c0ab
AFTER
https://github.com/open-sauced/app/assets/79809121/af45ff2f-f39d-4e14-98e5-904941da7850
1. Visit your workspaces
2. Create a new repo/contributor insight page
3. Fill the inputs and hit the create button
4. Buttons and text input should be disabled while the request is not done
=> fix: disable create insight button on request

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
- Always displays the Share button on contributor profiles
- Moves the follow/unfollow into the menu
Surfacing the Share button directly on all profiles encourages use of the button along with our new URL shortener which can be customized further and capture analytics on popular profiles.
Closes https://github.com/open-sauced/app/issues/2991
Closes https://github.com/open-sauced/app/pull/3065
BEFORE:
AFTER:
=> fix: always show share button on contributor profiles

components/Workspaces/WorkspaceLayout.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/activity.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/highlights.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/activity.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/contributors.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/dashboard.tsx
- Renders the workspace upgrade banner only on the client to remove hook rendering errors
- Fixes an issue reported by Xebia who has a large list of contributors where they couldn't see their contributor insights list
- Also fixes logic and adds workspace upgrade banner to contributor insight pages
1. Visit https://beta.app.opensauced.pizza/workspaces/b72dcf17-dc51-44f4-ac9c-2c0e483e76f2/contributor-insights/2ea74136-b092-41fe-a42d-ba403cda876d/overview
2. Note the application error
--
1. Visit https://deploy-preview-3067--oss-insights.netlify.app/workspaces/b72dcf17-dc51-44f4-ac9c-2c0e483e76f2/contributor-insights/2ea74136-b092-41fe-a42d-ba403cda876d/overview
2. Note no error is shown
=> fix: move the workspace upgrade banner to render only on the client

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
dub.sh is powering oss.fyi and provides a lot of analytics for how folks discover OpenSauced. Today inviting is not common, but I figured I would go ahead fix this to see how often it is leveraged. 
Visit a user profile who has not signed up and click the either the X or email icon.
i.e. https://deploy-preview-3068--oss-insights.netlify.app/user/dayhaysoos
=> feat: add oss.fyi links for invites

pages/_app.tsx
This reverts commit 027248e60aa6a36ab8a83e16551de565080f5ade. The code to hide the chatbot is no longer required. This was some remaining code for it.
I came across this while looking at some caching issues.
Relates to #1217
Relates to #1218
Nothing to test as this remaining code's variable that was created was never used.
=> fix: revert "feat: hide chatbot on non-prod environment and mobile screens (#1218)"

components/Graphs/MetricCard.tsx, components/Graphs/StarsChart.tsx, lib/utils/repo-page-utils.ts, pages/s/[org]/[repo]/index.tsx
Implements a "cumulative" category for the Stars Chart, where it shows the repository's total each day (eg Day 1: 1200, Day 2: 1208, etc.)
Closes #3025 
https://github.com/open-sauced/app/assets/20603494/46b9d417-13c6-4f47-9dd9-ce51cc00b375
=> feat: cumulative category for Stars Chart

components/Graphs/MetricCard.tsx, components/Graphs/StarsChart.tsx, pages/s/[org]/[repo]/index.tsx
Fixes responsive issues with the repository page including smaller fonts on smaller screens.
Closes #3078
**Before**
https://github.com/open-sauced/app/assets/833231/0a10638a-512f-4ea2-8741-b9190d85f5c4
**After**
https://github.com/open-sauced/app/assets/833231/e0928cd8-ba41-4539-8357-bed91e28d88c
1. Visit `/s/open-sauced/app`
2. Try it out on various screen sizes.
=> fix: fixed responsive issues on repo page

pages/s/[org]/[repo]/index.tsx
Now the repository page header aligns with the content
Fixes #3089
**Before**
**After**
=> fix: now repository page header aligns with the content of the page

components/Workspaces/WorkspaceOgImage.tsx, pages/workspaces/[workspaceId]/index.tsx
- Generates a full URL for the workspace OG image instead of just the path
Fixes #2994 
1. Find a public workspace URL
2. Paste the deploy preview into X to compose a post
3. Note that OG image is displayed in the preview
=> fix: use full URL for workspace OG image

components/Graphs/MetricCard.stories.tsx, components/Graphs/MetricCard.tsx, pages/s/[org]/[repo]/index.tsx
Fixes #3095
**Before**
**After**
1. Visit `/s/analogjs/analog`
2. Notice the metric cards have the ellipse button menu and percentage in the bottom left corner removed.
=> fix: removed unused parts of metric card for now

components/shared/DayRangePicker.tsx
- Adds additional ranges for 6 months and 1 year for selecting time ranges
- Also stress tests some points in our API for repositories
- Needs https://github.com/open-sauced/api/pull/708
1. Login
2. Go to a workspace
3. Change the Range filter from 30d to 6mo or 1yr
4. Notice the data refresh
=> feat: extend range picker to 6 months and 1 year

components/molecules/RecommendedRepoCard/recommended-repo-card.tsx
In preparation for the #2961 and the recently opened issue #3070, I am updating the 404 links in the recommendations tab to render the repo pages. The 404 was a side effect of removing the insight page filters last year but was only caught recently by a new user. 
Closes #3070
1. Navigate to your profile
2. Click the recommendations tab
3. Click a recommendation.
=> feat: link to repo recommendations to a repo page

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Closes #2918 
1. Go to a user's profile page
2. Check that the contributions tab shows up first
=> feat: make Contributions tab default on user profile pages

components/Workspaces/WorkspaceHeader.tsx
Implements a pill display in `WorkspaceHeader` that shows whether a workspace is public or private.
Closes #2981
=> feat: add visibility pill to WorkspaceHeader

pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx
- Fixes an issue where the `WorkspaceBanner` was being called as a function instead of returned as a component, throwing an error on a re-render.
- Error surfaced on Xebia workspaces with over 400 contributors
Fixes https://github.com/open-sauced/app/issues/3120
1. Login
2. Go to a non-upgraded workspace
3. Create a contributor insight with more than 10 contributors
4. View the new contributor insight
5. Note no crash occurs and the upgrade banner is displayed
=> fix: use workspace banner component on contributor insights overview

components/Graphs/ForksChart.stories.tsx, components/Graphs/ForksChart.tsx, lib/utils/repo-page-utils.ts, next-types.d.ts, pages/s/[org]/[repo]/index.tsx
Implements a chart for repo pages that shows the daily and cumulative forks based on the range, similar to the StarsChart. Both are synced so when hovering over one graph, the same time period will be highlighted in the other.
Closes #3034
Closes #2961 
https://github.com/open-sauced/app/assets/20603494/5abe591f-2e10-4332-97b7-98cc44b7e874
=> feat: ForksChart for repo pages

pages/404.tsx
- Removes unnecessary login button from 404 page
Fixes https://github.com/open-sauced/app/issues/3064
BEFORE:
AFTER:
1. Navigate to bad URL `/not-found`
2. Note no login button is displayed in the top right corner
=> fix: remove login button from 404 page

netlify/edge-functions/repo-page-card.tsx
Fixes an issue I introduced while making some changes to the repository OG image yesterday. Before totals being shown were always 0, now the totals are correct.
Fixes #3135
**Before**
https://beta.app.opensauced.pizza/og-images/repository/open-sauced/app/30?description=%F0%9F%8D%95+The+path+to+your+next+contribution.
**After**
https://deploy-preview-3133--oss-insights.netlify.app/og-images/repository/open-sauced/api/30?description=API+built+in+NestJS+and+SupaBase+designed+to+remove+client+complexity+and+provide+a+structured+graph+of+all+%40open-sauced+integrations
=> fix: now repo page star and fork totals load up instead of returning 0

e2e/repo-page.spec.ts, e2e/workspace-dashboard.spec.ts, netlify/edge-functions/repo-page-card.tsx, netlify/edge-functions/workspaces-card.tsx, netlify/og-image-utils.ts, playwright.config.ts
This is just a bit of cleanup now that the workspace and repository OG images are live.
Relates to #3117
1. Go to a workspace dashboard
2. Copy the link
3. Paste it in Slack, the OG image appears like it did before.
4. Do the same for any repo page.
=> fix: now common OG image functions are in a utility file

pages/user/[username]/index.tsx
- Removes the OpenGraph image request from getServerSideProps
- Returns the OpenGraph image directly as the OpenGraph request is fast enough
Related to: https://github.com/open-sauced/app/issues/3066
1. Visit user profile in OpenGraph image viewer
2. Note OpenGraph image is displayed
3. Note no function timeout
=> fix: use OpenGraph image URL and remove server request from user profile

netlify/edge-functions/repo-page-card.tsx
- Flips the text for stars/forks on the open graph image
Before:
After:
1. View OpenGraph image from deploy preview for repo page
2. Note Stars/Forks text matches image
=> fix: swap text for stars/forks in repo page OG image

netlify/edge-functions/card.tsx
- Fixes the URL for pulling contributor pull requests in the card edge function
- Noticed the error in the Netlify edge function logs
=> fix: update API URL in contributor card edge function for pull requests

components/organisms/Repositories/repositories.tsx, pages/workspaces/[workspaceId]/repository-insights/new.tsx
- Fixes an issue where selecting repos and clicking `Add to Insight Page` does not transfer the selected repos
1. Login
2. Go to a workspace 
3. Select some repositories
4. Click `Add to Insight Page`
5. Note the `Repositories` is populated for the name, and the repos are selected
=> fix: pass selected repositories to new repository insight creation

components/PullRequests/PrStateAuthorIcon.stories.tsx, components/PullRequests/PrStateAuthorIcon.tsx
Adds the Author/PR State icon to the project.
Closes #3156
Zoomed in to give a better idea.
Check the different states out in Storybook, https://deploy-preview-3155--design-insights.netlify.app/?path=/docs/components-pullrequests-prstateauthoricon--docs
=> feat: created the Author/PR State Icon component

components/molecules/AnnouncementCard/announcement-card.tsx, components/molecules/CardRepoList/card-repo-list.tsx, components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, components/molecules/FavoriteRepoCard/favorite-repo-card.tsx, components/molecules/LatestPrTableRow/latest-pr-table-row.tsx, components/molecules/RecommendedRepoCard/recommended-repo-card.tsx, components/molecules/TableRepositoryName/table-repository-name.tsx, components/organisms/Footer/footer.tsx, pages/user/[username]/card.tsx
- Removes occurrences of rel="noreferrer" for improved SEO performance
Closes https://github.com/open-sauced/app/issues/3168
=> fix: remove occurrences of rel="noreferrer" for SEO

public/_headers
- Adds Netlify configuration for headers to be built to ignore non-production domains including beta and deploy previews
- Should improve our SEO presence to only index only production URLs
Closes https://github.com/open-sauced/engineering/issues/296
=> chore: add headers configuration to ignore non-production domains

pages/s/[org]/[repo]/index.tsx
Changes the repo pages' title into a link to its GitHub page that opens in a new tab.
Closes #3153 
https://github.com/open-sauced/app/assets/20603494/1a778cef-f520-44ff-91e2-b754206beeed
1. Go to any repo page
2. Click the repository's name and see new tab to its GitHub page.
=> feat: add link from Repo pages to GitHub

public/robots.txt
Allowing crawler to hang with us.
=> feat: Create robots.txt

components/Graphs/ForksChart.tsx, components/Graphs/StarsChart.tsx, lib/utils/repo-page-utils.ts
The term "cumulative" is confusing. This PR changes any instance of it to "history" to be clearer to users and developers.
Closes #3193
=> feat: rename cumulative to history in Repo pages

npm-shrinkwrap.json, pages/starsearch.tsx
Better parsing for StarSearch response.
BEFORE
AFTER
=> fix: quick fix StarSearch response

npm-shrinkwrap.json, package.json, pages/starsearch.tsx
StarSearch responses return markdown; this PR implements `remark-react` to render it.
Closes #3200 
BEFORE 
AFTER
1. Go to `/starsearch`
2. Ask `Who knows Tailwind and is interested in Rust?` to guarantee markdown.
3. Ensure that it renders bold, inline code, and italics.
=> feat: render markdown for `/starsearch` responses

pages/workspaces/[workspaceId]/contributor-insights/index.tsx
This PR fixes the workspace contributor insights index page to allow for multiple list deleting without the need of a refresh. Uses the `deleteContributorInsight` function from `workspace-utils`.
Closes #2849 
https://github.com/open-sauced/app/assets/20603494/bc555d67-0ed5-4fc3-996a-1c9decdb9eff
1. Go to a workspace with multiple contributor insights
2. Click `Contributor Insights` title from the sidebar to go to list page
3. Try deleting multiple insights
=> fix: delete multiple workspace contributor insights

pages/s/[org]/[repo]/index.tsx
Implements `share` button to repo pages.
Closes #3160
=> feat: add share button to repo pages

pages/star-search/index.tsx
Now StarSearch responses have styled hyperlinks.
Fixes #3237
**Before**
**After**
1. Go to `/star-search`
2. Use this prompt, `Who are the most prevalent contributors to the Typescript ecosystem?`
3. Notice hyperlinks in the response are styled now.
=> fix: now StarSearch responses with links have styled links

components/shared/AppSidebar/AppSidebar.tsx
Now he StarSearch link is in the sidebar for smaller screens.
Fixes #3262
**Before**
**After**
1. Go to any workspace page on a smaller screen so the StarSearch link up in the top navigation disappears.
2. Open the side bar.
3. Notice the StarSearch link under the explore and highlights links.
4. Click the link and you're taken to StarSearch.
=> fix: now StarSearch link is in sidebar for smaller screens

.github/workflows/playwright.yml
Adds the name `E2E Tests` to the Playwright GitHub action job test so it's easier to surface in required checks in branch protection. `test` as a name was too generic.
Relates to #3267
N/A
=> chore: added a name to job for Playwright GH action

components/molecules/SuperlativeSelector/superlative-selector.tsx, lib/hooks/api/useContributors.ts, lib/hooks/api/useRepositoryPullRequests.ts, lib/hooks/useFilterPrefetch.ts
- Removes the API calls and associated numbers from the filter dropdown field
- This reduces the number of blocking API calls on the explore page by 5 requests, allowing the page to load faster as much as 50%
- This removes any extra filters when searching by specific repositories, so the API request is much more scoped down
Related to #1284 
1. Navigate to an explore page `/explore/topic/typescript`
2. Note page loads
3. Switch topics `/explore/topic/kubernetes`
4. Note page loads
5. Refresh page
=> fix: remove filter prefetch and additional filters when searching by repository

pages/s/[org]/[repo]/index.tsx
- Updates the Posthog even when a repo page is shared to use a single event with associated metadata
Closes https://github.com/open-sauced/app/issues/3279
1. Go to a repo page
2. Click share
3. Note the event is `clicked: repo page share button` in Posthog
=> fix: capture repo page share as unique event with repo name as metadata

pages/star-search/waitlist.tsx
This PR adds social share buttons for X/Twitter and LinkedIn
Closes #3283
https://github.com/open-sauced/app/assets/833231/5d16fe4f-0789-4ea4-ade8-bced4dcc4d32
Twitter share
LinkedIn share
Note that on LinkedIn, the OG image won't be that big once it's in a post.
Note, only the core team can really QA this as they need to reset their user profile in the development database.
To reset being on the waitlist, you'll need to run the following:
```SQL
UPDATE
users
SET
is_waitlisted = FALSE
WHERE
ID = 833231; # put your user ID here instead
SELECT
is_waitlisted,
id
FROM
users
WHERE
ID = 833231; # put your user ID here instead
```
Core team members will also need to ensure these properties are false (temporarily) in Posthog. You can ask @isabensusan or myself to change it temporarily if you do …
=> feat: now you can share the StarSearch waitlist on socials

components/Repositories/AddToWorkspaceDrawer.tsx, components/Repositories/AddToWorkspaceModal.tsx, pages/s/[org]/[repo]/index.tsx
Implements a button to allow a user from a repo page to add the current repo to one of their workspaces, or create one from scratch. Users who are not logged in are given a copy of the `WorkspaceWelcomeModal` and a CTA to connect with GitHub. Desktop users are shown a modal with a single select and a confirm button; mobile users are shown the same as a drawer.
Closes #3251 
https://github.com/open-sauced/app/assets/20603494/b283684e-d576-4d53-b1c2-fb23ad4677a8
1. Go to a repo page while NOT logged in
2. Check that you get a CTA to log in
3. Go to a repo page while logged in
4. Check that you can select between making a new workspace or an existing one
5. Either go through the creation process or go to the workspace you have selected and confirmed
6. Ensure that the repository added is …
=> feat: implement 'Add to workspace' in repo pages

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx, components/shared/AppSidebar/AppSidebar.tsx
Notices this while sharing via mobile IRL. I was usually deep in conversation during a demo would hit this. Never opened an issue.
=> fix: explore links 404

lib/hooks/useStarSearchFeedback.ts, pages/star-search/index.tsx
This PR implements the StarSearch feedback feature.
Closes #3296 
Closes https://github.com/open-sauced/engineering/issues/295
https://github.com/open-sauced/app/assets/833231/6f6d7262-d27b-49d5-85a3-718b26068a3e
1. You need to part of the cohort for the StarSearch feature flag to test this.
2. Go to `/star-search`
3. Ask a question.
4. Notice the new feedback buttons (thumbs up, thumbs down) at the end of the conversation.
5. Click either one.
6. A toast message thanks you for your feedback.
7. Open the devtools console in the browser and find the posthog events and expand them
8. Notice a new posthog event called `star_search_feedback`. (see video above to see it in action)
=> feat: implemented the StarSearch feedback component

components/organisms/TopNav/top-nav.tsx
- Removes alt text from icon in favour of an empty alt attribute
- fixes #3264 
- Not applicable
=> fix(#3264): remove alt text

components/Workspaces/RepositoryStatCard.tsx, components/atoms/Pill/pill.tsx, components/molecules/RepoRow/repo-row.tsx
Now low activity ratio pills are slate for the workspace engagement card and repository table rows.
Closes #3345
**Before**
**After**
1. Go to a workspace overview page with low activity ratio.
2. Notice the pill component for low activity ratio is slate now instead of read.
3. You might need to page through the repository table, but the low activity ratio is slate there as well now too.
=> feat: now low activity ratio pills are slate

layouts/lists.tsx, lib/hooks/api/useContributionsByEvolutionType.ts, lib/hooks/api/useContributorsByProject.ts, lib/hooks/api/useMostActiveContributors.ts, pages/workspaces/[workspaceId]/contributor-insights/[listId]/activity.tsx
- Adds the ability to filter activity on a contributor insight by repositories
- This allows maintainers to more easily create a contributor insight of their "core team" or "triage team" and filter down to the repositories they're interested in for activity on contributions
Closes #2875
https://github.com/open-sauced/app/assets/42211/ecd46fe7-b951-4ba7-98cd-a52817234a14
1. Navigate to a workspace
2. Go to a contributor insight
3. Go to the activity tab
4. Choose repositories from the filter on the far right
5. Note the graphs update based on the repositories chosen
=> feat: add repository filtering to contributor insight activity page

components/atoms/Select/multi-select.tsx
Some style tweaks for the multi-select component that I came across while working on #3334
Relates to #3340
**Before**
**After**
1. Navigate to, `/workspaces/60c3ee25-2bc6-41fd-babf-d4e294332298/activity`
2. Notice the change to the filter that says All Repositories
=> fix: style tweaks for MultiSelect component

components/Graphs/PRChart.tsx
This PR fixes the title text for pull request charts.
fixes #3349
1. Visit a repository page
2. Hover over the PR-Chart
3. Validate you see the right title
=> fix: title for PR chart tooltip

components/organisms/ContributorCard/contributor-card.tsx, lib/hooks/useFetchUser.ts
- Fixes the contributors tab on repo pages where only the maintainers for that repository are given the maintainer badge
Related to: https://github.com/open-sauced/api/issues/793
BEFORE:
AFTER:
1. Navigate to repo page contributors on beta - https://beta.app.opensauced.pizza/s/analogjs/analog/contributors
2. Note multiple people marked as maintainers in the contributors list
3. Navigate to deploy preview https://deploy-preview-3395--oss-insights.netlify.app/s/analogjs/analog/contributors
4. Note brandonroberts is marked as a maintainer in the contributors list
Validate no slow down of page load occurs also
=> feat: only tag maintainers for the specific repo on repo pages

components/Issues/IssueStateAuthorIcon.tsx
Previously, the merged issue color was red. To maintainer uniformity, this uses purple.
closes #3396 
Deploy Preview: https://deploy-preview-3406--oss-insights.netlify.app/workspaces/3e97a217-2216-4d65-b7f6-846d181b9e83/issues?page=1
Running locally:
1. Go to a workspace
2. Click Activity
3. Click Issues
=> fix: Change closed issue state to purple on issues table

lib/hooks/useStarSearchFeedback.ts, pages/star-search/index.tsx
- Captures every StarSearch prompt and response as a unique PostHog event
- This lets us see which prompts are the most popular for insights on how to better improve the experience
Closes #3401 
1. Login
2. Go to StarSearch
3. Enter a prompt
4. Go to PostHog dashboard -> Activity
5. Search for the `star_search_prompt` event.
=> feat: capture all StarSearch prompts in PostHog

pages/star-search/index.tsx
The css modules example was flawed because that is not something matters or changes often in turbo. Instead, I'd rather include a question that highlights th work @nickytonline just shipped.
1. Click the lottery factor prompt.
=> fix: swap out css module prompt with lottery factor

components/shared/AppSidebar/AppSidebar.tsx
Disables the search on the workspace dropdown in the sidebar if there's no user logged in. Clicking the "Create new workspace" option will automatically log the user in using GitHub and redirect to `/workspace/new`
Closes #3377 
Relates to #2812
https://github.com/open-sauced/app/assets/20603494/2fca1f50-3f44-445f-9d0e-709fe8cd4778
1. Go to a page with the `WorkspaceLayout` (ie repo pages) while NOT logged in
2. Click on the workspace dropdown
3. Ensure there is no search input
4. Click on the `Create new workspace` option
5. Ensure that it redirects you to `/workspace/new` AND logged you in via GitHub.
=> fix: disable search for workspace dropdown if not logged in

components/Repositories/LotteryFactorChart.stories.tsx, components/Repositories/LotteryFactorChart.tsx
Fixes the lottery chart when there are less than 4 contributors. Prior to the fix you'd see some broken avatar images and other contributors being consider as a contributor.
Currently if no contributions have been made, it shows as a low lottery factor. This will change to high once @jpmcb's work in the API is merged (see https://github.com/open-sauced/api/issues/808).
Fixes #3402
The numbers might look a little off for one, two, and three contributors but that's because it's not real data.
=> fix: fixed rendering of lottery chart when less than 4 contributors

components/ListHeader/list-header.tsx, components/Workspaces/WorkspaceHeader.tsx, components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, components/molecules/InsightHeader/insight-header.tsx, lib/utils/write-to-clipboard.ts, pages/s/[org]/[repo]/contributors.tsx, pages/s/[org]/[repo]/index.tsx
- Fixes a bug with copying text to the clipboard in Safari-based browsers
- Adds a utility function to copy text to the clipboard that works in Chrome and Safari
Closes #3385 
1. Go to any page with a share button (repo page, workspace, etc) in Safari on Desktop or iOS
2. Click the `Share` button
3. Note the short URL is copied to the clipboard and the toast message is displayed
=> fix: add support for clipboard copy in Safari and use utility function

pages/star-search/index.tsx
Updates StarSearch copy on the StarSearch page to "Copilot, but for git history".
Fixes #3441
**Before**
**After**
1. Go to StarSearch
2. Notice the new copy
=> fix: updated StarSearch copy

pages/star-search/index.tsx
Just a small copy update for the star search suggested queries: the LLMs know about `@` prepended to usernames which can help during search.
N/a
N/a
=> feat: Small update to copy for suggested starsearch queries

components/StarSearch/LoginModal.tsx, e2e/star-search.spec.ts, pages/star-search/index.tsx
Adds end to end (E2E) tests for the StarSearch logged out experience. Writing the tests also uncovered some accesibility issues with StarSearch that have been addressed.
Relatest to https://github.com/open-sauced/engineering/issues/294
N/A
E2E tests go green
=> test: added E2E tests for StarSearch logged out experience

pages/star-search/index.tsx
Adds small copy under the StarSearch input box that disclaims the possibility of hallucinations.
Closes #3407
=> feat: add hallucination disclaimer to `/star-search`

e2e/user-profile.spec.ts, next.config.js
Now /u/some_username redirects to /user/some_username
Closes #3457
1. Go to https://deploy-preview-3458--oss-insights.netlify.app/u/bdougie
2. It redirects to https://deploy-preview-3458--oss-insights.netlify.app/user/bdougie
3. Go to https://deploy-preview-3458--oss-insights.netlify.app/u/bdougie?tab=contributions&range=180
4. It redirects to https://deploy-preview-3458--oss-insights.netlify.app/user/bdougie?tab=contributions&range=180
=> feat: now /u/some_username redirects to /user/some_username

pages/star-search/index.tsx
Now the avatar for the logged in user appears for the prompt sent to StarSearch.
Fixes #3453
**Before**
**After**
=> fix: now avatar for logged in user appears for StarSearch prompt

components/atoms/Avatar/avatar-hover-card.tsx, pages/star-search/index.tsx
Closes #3462
**Before**
**After**
1. Go to StarSearch, `/star-search`
2. Select the suggested prompt, "Get information on contributor activity"
3. Notice @brandonroberts avatar beside the link `@brandonroberts`.
4. Hover over the avatar.
5. Information about Brandon appears.
=> feat: added hover cards to StarSearch results that return links to GitHub users

pages/star-search/index.tsx
Style tweaks for height.
Relates to #3456
=> fix: height style tweaks for StarSearch

components/molecules/DevToSocialImage/dev-to-social-img.tsx, lib/hooks/fetchDevToBlogInfo.ts, lib/utils/dev-to.ts, lib/utils/github.ts, lib/utils/url-validators.ts, pages/user/[username]/card.tsx
Adds URL parameter validators - in the very unlikely case that there is an invalid, malicious, or malformed input URL param from a third party provider, we simply throw out the stack.
N/a
=> feat: Adds URL parameter validators to fetch requests

pages/feed/index.tsx
- Add padding pb-14 to the highlights feed container to ensure spacing from the footer.
Fixes #3482 
```
npm info using npm@9.6.7
npm info using node@v18.17.0
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
npm info ok 
[fix/highlights-footer-spacing 6407b656] fix(update padding to pb-14 for highlights feed container on app/pages/feed/index.ts): upd line 179
1 file changed, 1 insertion(+), 1 deletion(-)
npm info ok 
npm info ok 
```
🙂
=> fix: added more padding between footer and highlights

components/organisms/SearchDialog/search-dialog.tsx
Conclude error messages for both users and repos into a single message
fix #3411
1. Go to user and repo search on the top nav bar
2. Try searching for any no existing repo and user 
3. You should get only one not found message
=> fix(search): only show one not found message

pages/star-search/index.tsx
Updates the error copy for StarSearch:
Closes: https://github.com/open-sauced/app/issues/3493
=> feat: Updates error copy StarSearch

layouts/filter.tsx
Implements the `WorkspaceLayout` in the `Tool` component used to render the `/explore` page.
Closes #3513
https://github.com/open-sauced/app/assets/20603494/e436039f-dcc2-4b1d-881b-be7c8d6f4015
=> feat: add workspace sidebar to `/explore`

components/Workspaces/WorkspaceLayout.tsx, pages/feed/index.tsx
Implemented `WorkspaceLayout` in the highlights `/feed` page, replacing the `ProfileLayout` used before.
Closes #3512 
https://github.com/open-sauced/app/assets/20603494/7f86c750-ef81-4285-8625-6d892ef29bf1
=> feat: add workspace sidebar to `/feed`

pages/s/[org]/[repo]/index.tsx
On smaller screen sizes, DevStats (`ContributorConfidenceChart` & `LotteryFactorChart`) are put above the Contributor and Issues/PR charts.
Closes #3550
=> feat: Repo Pages - move devstats to top of mobile view

components/Workspaces/WorkspaceLayout.tsx
If the user is NOT logged in, the sidebar should not be showing by default. Vice versa if the user is logged in and in a large screen size.
Closes #3573 
1. Go to the deploy preview
2. Ensure you are logged out AND you are in a large screen size
3. Remove the `showingSidebar` variable from the local storage via browser tools
4. Refresh and see the sidebar isn't showing
5. Do the same with a logged in user and see that the sidebar shows
=> feat: don't show sidebar by default for non-logged in user

lib/utils/server/feature-flags.ts
Adds the `starsearch-workspaces` feature flag to the project.
Closes #3589
N/A
=> feat: added the starsearch-workspaces feature flag to the app

.github/workflows/issue.yml
This pull request includes a minor change to the `issue.yml` file in the `.github/workflows/` directory. The change modifies the automatic response body for new issues, specifically the instructions for contributors who have questions. The instructions have been changed from reaching out on Discord or following up on the issue, to simply commenting on the issue.
This is an effort to eventually wind down discord this fall, and point folks to use GItHub instead.
=> fix: remove discord link from issue.yml

.storybook/main.js, components/StarSearch/StarSearchButton.tsx, components/StarSearch/StarSearchCompactHeader.stories.tsx, components/StarSearch/StarSearchCompactHeader.tsx, components/StarSearch/StarSearchLogo.tsx
This PR introduces the StarSearch compact header component to be used wherever StarSearch is embedded.
Closes #3588
You can [view and try out the component in Storybook](https://deploy-preview-3591--design-insights.netlify.app/?path=/story/components-starsearch-starsearchcompactheader--default).
=> feat: implemented the StarSearchCompactHeader component

pages/feed/index.tsx
Adds `mx-auto` to the `/feed` container div to center the highlights page on the screen.
Closes #3585
**Before**
**After**
=> fix: center highlights page

components/StarSearch/StarSearchChat.tsx, components/StarSearch/StarSearchCompactHeader.tsx, components/StarSearch/StarSearchEmbed.tsx, components/StarSearch/SuggestedPrompts.tsx, components/shared/Drawer.tsx, lib/utils/star-search.ts, pages/workspaces/[workspaceId]/activity.tsx, pages/workspaces/[workspaceId]/index.tsx
This PR introduces StarSearch for Workspaces. It is currently behind a feature flag with only the core team having access to it. If you need to  add a design partner or someone else to the feature flag, see #3590.
Sharing of StarSearch conversations is currently not implemented.
Closes #3508
**Smaller Screen Experience**
https://github.com/open-sauced/app/assets/833231/1e45148b-20bf-484d-984a-d10ea4d7e597
**Larger Screen Experience**
=> feat: StarSearch for Workspaces

components/Repositories/LotteryFactorChart.tsx, pages/s/[org]/[repo]/index.tsx
The `LotteryFactorChart` already have hover cards for the "Other Contributors" sections using the `StackedOwners` component. This PR will show the hover cards for the bigger contributors if the `showHoverCards` prop is passed to the component. 
Closes #3608
1. Go to any repo page
2. Hover over contributors on the Lottery Factor Chart and see the card
=> feat: add `showHoverCards` optional prop to `LotteryFactorChart`

components/StarSearch/StarSearchChat.tsx, e2e/repo-page.spec.ts, styles/globals.css
Now scrolling overflow on the body is set to hidden only on the StarSearch page and not for pages that have an embedded StarSearch.
Fixes #3618
**Before**
**After**
Note, the core team are the only ones that can test this as they have the feature flag for StarSearch for Workspaces.
1. Go to `/star-search`
2. Ask a question.
3. Only the chat area scrolls and not the body.
4. Go to a workspace on a medium or larger screen size.
5. Shrink the browser window so that the content can be scrolled.
6. Notice the scroll bar for the body and it's scrollable.
7. Open StarSearch.
8. Ask a question.
9. The body remains scrollable, but notice in the StarSearch embed that only the chat area is scrollable.
=> fix: now workspace pages with StarSearch are scrollable

lib/hooks/useSearchRepos.ts
- Adds a fallback to the GitHub API if no results are found or an error occurs in our API search
Closes https://github.com/open-sauced/app/issues/3552
1. Go to deploy preview
2. Open Browser Devtools
3. Click on the Users/Repo Search
4. Search for a repo not in our data but on GitHub
5. Note the network requests for our API and the GitHub API
6. See the repo in the search results
=> feat: add fallback to GitHub API for repository search hook

img/icons/interests/swift.svg, pages/start.tsx
- Redirects new user to workspaces after completing onboarding
- They are then displayed the workspaces modal with the introductory video
- Also fixes a size issue with the swift icon on the interests section of onboarding
Closes #3506
1. Go to deploy preview in an incognito window
2. Connect with a new account
3. Go to through onboarding
4. Note after onboarding, you're redirected to your personal workspace
5. The workspaces intro modal is displayed
=> feat: redirect user to workspaces after onboarding

lib/utils/server/feature-flags.ts
Introduces the `oscr-rating` feature flag to the codebase. Note that the feature flag has already been created in PostHog.
Closes #3641
N/A
N/A
=> feat: created the OSCR rating feature flag

components/organisms/ListPage/DeleteListPageModal.tsx
Now the input is being reset when a contributor insight list is deleted before it was keeping the latest deleted contributor insight list name
Fixes #3553 
Before
https://github.com/open-sauced/app/assets/106425076/71e4628f-247d-4879-bf77-4b690f634e69
After
https://github.com/open-sauced/app/assets/106425076/bf5c103e-fa8a-4a28-9213-aa581a9ec162
1. Go to your workspaces
2. delete one of the list
3. try deleting another
4. notice now input is empty
=> fix: reset input after deleting contributor insight list

components/molecules/InsightHeader/insight-header.tsx, components/organisms/ToolList/nav.tsx, layouts/hub-page.tsx, layouts/lists.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/activity.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/highlights.tsx
Adds padding to contributor insights. Also match padding for insight headers to the workspace home page's.
Closes #3595 
**Before**
**After**
=> fix: workspace insight header paddings

components/Graphs/IssuesChart.tsx, components/Graphs/PRChart.tsx
This PR removes dots per data point in the `IssueChart` & `PRChart` since it gets muddy in small screens, especially on mobile or when loaded for longer ranges.
**Before**
**After**
=> fix: remove dots from `IssueChart` & `PRChart`

components/Workspaces/TrackedRepoWizard/SelectOrgReposStep.tsx, components/Workspaces/TrackedRepoWizard/TrackedRepoWizard.tsx, lib/hooks/useGetOrgRepos.ts, next-types.d.ts
- Adds a day range filter when importing repos for a GitHub org
- Filters the imported repo list by the range based on the repo `pushed_at` date
- Also fixes an issue with importing large orgs like `microsoft`
Closes https://github.com/open-sauced/app/issues/3607
1.  Login
2. Go to settings for a workspace
3. Click Add Repositories
4. Click on Import GitHub Organization
5. Select an Org
6. Note the repos is filtered to the date range
=> feat: add range filter when importing GitHub repos for an org

components/Workspaces/TrackedContributorsTable.tsx
The contributor insights edit page/new page is now responsive on smaller screens. Note that the add contributors modal is still not responsive. This will get addressed in a separate issue as this component is used elsewhere as well and needs to be responsive for all those use cases.
Fixes #3668
**Before**
**After**
Note that when the grid is populated, it was always responsive.
1. Open the deploy preview on your phone
2. Create or edit a contributor insight in any workspace that you can edit.
3. Notice the layout no longer bleeds out horizontally.
=> fix: now the contributor insights new/edit page fits in smaller screens

components/Repositories/LotteryFactorChart.tsx
fixes #3680 
fixes #3681 
1. Go to a repo page
2. Look at the lottery factor and click the tooltip
=> fix: lottery factor copy

e2e/feed.spec.ts, middleware.ts
- Redirects fallback URLs for non-authed users to the public explore page
Current behavior:
- Authenticated users who go to `/` are being redirected to their personal workspace
- Authenticated users who go to a URL other than `/` continue on to that page
Closes https://github.com/open-sauced/app/issues/3507
1. Go to deploy preview without logging in
2. Note you're redirected to `/explore/topic/typescript` instead of `/feed`
=> fix: use explore page with typescript topic as fallback instead of feed page

components/Graphs/RadarChart.stories.tsx, components/Graphs/RadarChart.tsx, components/primitives/chart-primitives.tsx
Introduces a Radar chart component to the project. Note that the colour, and tooltip are completely customizable.
We can still iterate on this, but this first iteration is to get the ball rolling.
Closes #3703
See the [Radar chart Storybook stories](https://deploy-preview-3704--design-insights.netlify.app/?path=/docs/components-graphs-radarchart--docs)
=> feat: implemented the Radar chart component

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Now the contributions tab is the first tab on the user profile page
Relates to #2918
**Before**
**After**
=> fix: now the contributions tab is the first tab on the user profile page

components/molecules/ContributorHighlight/contributor-highlight-card.tsx, components/molecules/HighlightInput/highlight-input-form.tsx, lib/utils/github.ts
- Adds the ability to enter/display a GitHub release as a higlight
- Needs https://github.com/open-sauced/api/pull/941 to be deployed to enter a release highlight
Closes https://github.com/open-sauced/app/issues/3555
1. Login to deploy preview
2. Enter a new highlight using a release URL
3. Note the correct tag/repo is applied
4. Submit the highlight
=> feat: allow input and display of GitHub releases as highlights

pages/s/[org]/[repo]/contributors.tsx, pages/s/[org]/[repo]/index.tsx
Implement `<Activity />` component to show contributor distribution chart in repo pages under the "Contributor" tab. 
Closes #3711 
1. Go to any repo page's "Contributor" tab
2. Check the Contribution Distribution chart.
=> feat: add Contributor Distribution to repo page

components/Repositories/RossChart.tsx, next-types.d.ts, pages/s/[org]/[repo]/index.tsx
Filter `RossChart` data between different contributor types ("Outside" = `new`, "Recurring", "Internal").
- Bar chart & tooltip show/hide options
- Calculate total based on filters
- Calculate average per week based on range and filtered total
Closes #3695 
https://github.com/open-sauced/app/assets/20603494/fda1e0ab-7178-49a2-b44b-57357e998bed
1. Go to any repo page (see `neovim/neovim`)
2. Check any filter combinations
3. Ensure chart and numbers change on filter change
=> feat: filter `RossChart` by contributor type

components/organisms/Contributors/contributors.tsx, components/organisms/Repositories/repositories.tsx, components/organisms/ToolsDisplay/tools-display.tsx, lib/hooks/useList.ts
- Fixes flow where repositories can be added to a new workspace from the explore page
- Fixes flow where contributors can be added to a contributor insight from the explore page
- Fixes copy for adding contributor insights from explore page
Closes #3671 
Closes https://github.com/open-sauced/app/issues/2857
1. Go to the explore page
2. Login
3. Choose some repositories from the dashboard, click Add to Workspace
4. Follow flow to create a new workspace with the selected repositories
---
Contributor flow
1. Choose the contributors tab
2. Choose some contributors, click Add to Insight
3. Follow flow to add Contributors to new/existing Insight
=> fix: allow repos and contributors to be added to workspaces from explore page

layouts/filter.tsx
Add padding to the explore page's tabs.
Closes #3717 
**Before**
**After**
1. Go to the explore page
2. Check that there is now space on either side of the tabs
=> fix: add padding to explore tabs

components/TabList/tab-list.tsx
This PR fixes the bug where the selected date resets when switching between dashboard tab
Fixes #3657
https://github.com/open-sauced/app/assets/105356967/e7555d41-aea0-40be-bd56-0e4fc3286bc9
1. Go to the Explorer Page
2. Choose any repository
3. Change the date range
4. Then click on Contributors
=> fix: maintain selected date across dashboard tabs

components/StarSearch/Chatbox.tsx, components/StarSearch/StarSearchChat.tsx, components/StarSearch/StarSearchCompactHeader.stories.tsx, components/StarSearch/StarSearchCompactHeader.tsx, components/StarSearch/StarSearchEmbed.tsx, components/StarSearch/SuggestedPrompts.tsx, components/Workspaces/WorkspaceLayout.tsx, components/atoms/Avatar/avatar-hover-card.tsx, components/organisms/TopNav/top-nav.tsx, components/shared/AppSidebar/AppSidebar.tsx, pages/_document.tsx, styles/globals.css
These are all UI/UX improvements from a pairing session I had with @isabensusan today.
- some CSS Tweaks for StarSearch
- added logos to left of repo page URLs
- removed autoscroll after render
- conversation bottom menu scrolls with conversation
- improved scrolling DX
- now bottom fades in
- set fixed sizes for chatboxes
- made input orange border uniform
- added hover effects to suggested prompt cards
- tweaked prompt input styles
- now top gradient in StarSearch is in the background
Fixes #3693
Before and after side by side
https://github.com/user-attachments/assets/5415e231-52c1-4689-bd37-01b69eeeb98a
Very general, but use StarSearch on the StarSearch page and in Workspaces. Note that StarSearch for workspaces only works for workspaces where you're an owner. Future work will let you …
=> fix: fixed several UI/UX issues for StarSearch

components/Repositories/AddToWorkspaceDrawer.tsx, components/Repositories/AddToWorkspaceModal.tsx, pages/s/[org]/[repo]/contributors.tsx, pages/s/[org]/[repo]/index.tsx
Implements PostHog captures throughout the repo pages' headers on both tabs. The events captured in this section are:
- "Add to Workspace": click button and confirm add on modal
- `<DayRangePicker>`: capture chosen range on value change
- `<LanguagePill>`: capture the repo language when going to the explore page 
Closes #3723 
1. Go to any repo page (some repos might not have a language to click)
2. Interact with the listed components
3. Do the listed events
4. Check PostHog events (or the Repo Pages dashboard) to see if events are captured
=> feat: Track Repo Pages (Header)

components/Repositories/LotteryFactorChart.tsx, pages/s/[org]/[repo]/index.tsx
Implements PostHog captures on the Lottery Factor chart in repo pages. The events captured in this component are:
- YOLO banner: capture on click
- YOLO icon: capture on icon click
- User profile: capture on avatar click
Changes involved implementing two new props, `onProfileClick` & `onYoloIconClick`, and passing those `posthog.capture` functions in the repo page. These props are optional and can be customized on implementation (eg. StarSearch, etc.)
Closes #3732 
1. Go to any repo page (some repos might not have YOLO coders)
2. Interact with the listed components
3. Do the listed events
4. Check PostHog events (or the Repo Pages dashboard) to see if events are captured
=> feat: Tracking Repo Pages (Lottery Factor Chart)

lib/utils/server/feature-flags.ts, pages/workspaces/[workspaceId]/activity.tsx, pages/workspaces/[workspaceId]/index.tsx
Removes the `starsearch-workspaces` feature flag from the application source code. Once this PR is merged, remove the `starsearch-workspaces` feature flag from Posthog.
Closes #3729
1. Log in
2. Go to one of your workspaces
3. The StarSearch for Workspaces feature is available to your.
=> feat: removed StarSearch feature flagging

components/Graphs/ForksChart.tsx, components/Graphs/StarsChart.tsx, components/Repositories/ContributorConfidenceChart.tsx, components/Repositories/RossChart.tsx, pages/s/[org]/[repo]/index.tsx
Captures miscellaneous events throughout the repo pages via posthog passed in on optional props for the following components:
- `<RossChart>`: capture filter category and value (eg "internal" + `true`)
- `<ContributorConfidenceChart>`: capture click on "Learn More" docs link
- `<StarsChart>`: capture category click 
- `<ForksChart>`: capture category click
Closes #3738 
Closes #3722 
1. Go to any repo page (some repos might not have YOLO coders)
2. Interact with the listed components
3. Do the listed events
4. Check PostHog events (or the Repo Pages dashboard) to see if events are captured
=> feat: Tracking Repo Pages (Miscellaneous)

components/Repositories/YoloChart.tsx, pages/s/[org]/[repo]/index.tsx
Implements PostHog captures on the YOLO chart in repo pages. The events captured in this component are:
- Hide Bots: capture toggle and it's value
- SHA: capture on SHA link click
- User profile: capture on avatar click
Changes involved implementing two new props, `onProfileClick`, `onShaClick`, and `onHideBotsToggle`, and passing those posthog.capture functions in the repo page. These props are optional and can be customized on implementation (eg. StarSearch, etc.)
Closes #3735 
1. Go to any repo page (some repos might not have YOLO coders)
2. Interact with the listed components
3. Do the listed events
4. Check PostHog events (or the Repo Pages dashboard) to see if events are captured
=> feat: Tracking Repo Pages (YOLO Chart)

components/StarSearch/ChatAvatar.tsx, components/StarSearch/Chatbox.tsx, components/StarSearch/StarSearchButton.tsx, components/StarSearch/StarSearchChat.tsx, components/StarSearch/StarSearchEmbed.tsx, components/StarSearch/StarSearchLogo.tsx, components/Workspaces/WorkspaceWelcomeModal.tsx, components/shared/Drawer.tsx, e2e/workspace-activity.spec.ts, e2e/workspace-dashboard.spec.ts, pages/workspaces/[workspaceId]/activity.tsx, pages/workspaces/[workspaceId]/index.tsx, pages/workspaces/[workspaceId]/issues.tsx
Now if a user is not an editor of a workspace, the tooltip of the StarSearch CTA for workspaces will reflect that along with the button changing to a grey scale. As well, now if logged out, the StarSearch for workspaces CTA will be visible and enabled so you can log in to use it. The button also will be set to `aria-disabled="true"` if they do not have access to StarSearch as well as button text indicating so.
Fixes #3640
https://github.com/user-attachments/assets/35b367df-d08c-4433-9880-630e74211576
**Not an editor**
**Is an editor**
**Logged out**
Logged out
1. Go to a workspace
2. Notice the StarSearch CTA in the bottom right
3. It says in the tooltip that you need to be signed in to use workspaces
4. Click the CTA
5. You're logged in and either have access to StarSearch for workspaces …
=> fix: now StarSearch for workspaces only works for editors

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
Changed invite button OpenSauced text to PascelCase on user profile where user is not part of OpenSauced
fixes #3719 
Before
After
1. Visit any user profile which is not part of OpenSauced
2. Now OpenSauced text of invite button is Pascal cased
=> fix: changed OpenSauced text to proper casing

components/organisms/Dashboard/dashboard.tsx, components/organisms/Repositories/repositories.tsx, pages/workspaces/[workspaceId]/index.tsx, pages/workspaces/[workspaceId]/repository-insights/[insightId]/dashboard.tsx
- Uses the logged in users' personal workspace when creating new repository insights if they are not an owner on the workspace
- Fixes #3740
1. Login
2. Visit a workspace you are an owner of
3. Select some repositories
4. Click `Add to Insight`
5. Click `Create Insight`
6. Note the repository insight is created
=> fix: use personal workspace for creating repository insights from non-owner workspaces

components/Repositories/LotteryFactorChart.tsx
When calculating the 'Other Contributors' percentage, it subtracts the percentage of the top four contributors from 100. It did not account for that difference to be a float, which results in the overflow. This PR rounds the difference to 1 decimal point.
Closes #3575 
**Before**
**After**
1. Go to the `LotteryFactorChart` test in Storybook
2. Set the first four percentage to `90, 1, 1, 0.7` in the raw data
3. See that 'Other Contributors' are rounded to `7.3%`
=> fix: round 'Other Contributors' to avoid overflow

components/Repositories/OssfChart.stories.tsx, components/Repositories/OssfChart.tsx, pages/s/[org]/[repo]/index.tsx
Creates `OssfChart` component, with Storybook testing. To be implemented into repo pages once the score is [implemented in the API](https://github.com/open-sauced/api/issues/962) in a future PR.
Closes #3765 
**Error state changes:**
1. Go to storybook deploy and open `OssfChart` under 'Repository'
2. Change the `totalScore` to a number from 0 to 10 or `null`
3. Toggle the `isLoading` and `isError` booleans
4. See the different states
=> feat: MVP `OssfChart` component

components/molecules/DevCard/dev-card.tsx, next-types.d.ts, pages/u/[username]/card.tsx
Replaces the stats on the front of the DevCard with the user's OSCR score.
Closes #3743 
1. Go to a user's profile and click the pizza card icon (or go to `/u/<username>/card`)
2. Observe the OSCR score on the front
3. See more information changes on the back by clicking the card
=> feat: implement OSCR on devcards

lib/utils/star-search.ts
Improves the suggested prompts for StarSearch for workspaces. @open-sauced/engineering @BekahHW @isabensusan, we can let this sit for a bit while we keep testing some general prompts.
Closes #3778
**Before**
**After**
1. Open up StarSearch for workspaces. Notice the new question
=> feat: updated one of the suggested prompts for workspaces

components/Contributors/Oscr.tsx, components/Contributors/OscrButton.stories.tsx, components/Contributors/OscrPill.stories.tsx, components/Tables/ContributorsTable.tsx, components/molecules/CardProfile/card-profile.tsx, components/molecules/ContributorListTableRow/contributor-list-table-row.tsx, components/molecules/DevProfile/dev-profile.tsx, components/organisms/ContributorCard/contributor-card.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, e2e/user-profile.spec.ts
Adds OSCR to user profile page.
Closes #3772
https://github.com/user-attachments/assets/f0b0b7d7-be42-4ad9-a808-fa4f8f878555
**Logged In**
**Logged Out/Guest**
1. Go to your user profile or any user profile.
2. Notice the OSCR
1. Go to your user profile or any user profile.
2. Notice the Log in to view button under the OSCR heading.
3. Click the button to log in.
4. Notice the OSCR
=> feat: added OSCR to user profile page

pages/_document.tsx
This PR fixes the missing lang attribute mentioned in #3847.
Fixes #3847 
N/A
1. go to `/app/pages/_document.tsx`
2. look for the lang attribute on line 5
=> fix(/app/pages/_document.tsx): add lang attribute to html tag

components/Tables/ContributorsTable.tsx, components/organisms/ContributorProfileTab/contributor-profile-tab.tsx, lib/hooks/api/useContributorList.ts, lib/hooks/api/useFetchMetricStats.ts, lib/hooks/useFetchAllContributors.ts, next-types.d.ts, pages/workspaces/[workspaceId]/contributor-insights/[listId]/activity.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/edit.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/highlights.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx
This PR converts the contributor insight contributor table to the new TanStack table component. It also keeps the contributor grid uniform with information that previously wasn't available in insights, e.g. OSCR, company etc.
~It is good to go, but is blocked by https://github.com/open-sauced/api/issues/1001. For now all that means is you won't see the values in the contributions column.~
There are some responsive issues, but that is a separate issue. See #3809.
Closes #3845
1. Go to any workspace contributor insight that you have access to where there's at least a few users.
2. Notice the grid looks different and that you can sort by OSCR. Try sorting ascending or descending to see the changes reflected in the grid.
=> feat: converted contributor insight contributor table to new table component

components/Workspaces/TrackedRepoWizard/PasteReposStep.tsx, components/molecules/RepoRow/repo-row.tsx, components/organisms/Repositories/repositories.tsx, components/organisms/RepositoriesTable/repositories-table.tsx
- Adds the ability to import a Software Bill of Materials (SBOM) for provided repositories. This would help OSS maintainers in places such as the EU where generated a SBOM will be required in 2025 for open source project dependencies.
**Notes**
- The repositories should have a package.json at the root of the repository to detect dependencies
- We will expand this to cover different types of repository dependencies in the future
- Needs https://github.com/open-sauced/api/pull/999 to be merged/deployed
Closes #3841
1. Login
2. Create a workspace, or edit an existing workspace
3. Click Add Repositories
4. Select import repositories
5. Enter a valid public GitHub Repo with a package.json at the root (open-sauced/app)
6. Click Import SBOM
7. Note the repositories are added to the tracked …
=> feat: add option to import a SBOM of repositories to a workspace

pages/s/[org]/[repo]/index.tsx
Removes gradient on metadata tags on repo pages for mobile view.
Closes #3741
=> fix: remove gradient from metadata tags

components/molecules/NivoScatterChart/nivo-scatter-chart.tsx, e2e/repo-contributor-page.spec.ts
Now the repository page contributor graph defaults to enhance.
Closes #3863
**Before**
**After**
1. Navigate to a repository contributor page, e.g. http://localhost:3000/s/denoland/deno/contributors?range=30
2. Notice the contributor graph has enhance enabled by default.
=> feat: repository page contributor graph defaults to enhance by default now

components/Tables/ContributorsGrid.tsx, components/Tables/ContributorsTable.tsx, components/organisms/ContributorCard/contributor-card.tsx, lib/hooks/api/useRepositoryContributors.ts, lib/utils/sorting.ts, next-types.d.ts, pages/s/[org]/[repo]/contributors.tsx, pages/workspaces/[workspaceId]/activity.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx, pages/workspaces/[workspaceId]/issues.tsx
Now the OSCR appears on the repository page contributor grid view.
Closes #3883
**Before**
**After**
1. Go to any repository contributor page, e.g. http://localhost:3000/s/denoland/deno/contributors?range=30
2. Notice the grid view (default view) displays OSCRs with the lock button for contributors.
3. Log in.
4. Notice the grid view (default view) displays OSCRs for contributors.
1. Go to any repository contributor page, e.g. http://localhost:3000/s/denoland/deno/contributors?range=30
2. Notice the grid view (default view) displays OSCRs for contributors.
=> feat: now OSCR appears on repository page contributor grid view

components/Contributors/Oscr.tsx
Adds the current `OSCR` button's location (`router.pathname`) to the PostHog capture that occurs when the user clicks and logs in to see the OSCR score.
Closes #3886 
1. Go to any page with the `OSCR` button as a non-logged in user
2. Click to see the OSCR score
3. Go to PostHog and look for the event 'OSCR Login Button clicked' and check additional information for the `pathname`
4. Alternatively, go to the 'OSCR' dashboard and check the corresponding graph for data
=> feat: add OSCR's location to PostHog capture

components/Repositories/RossChart.tsx
- Fixes a `NaN` issue when the contributors for the ROSS chart length is 0
Fixes #3699 
1. Visit https://beta.app.opensauced.pizza/s/jpmcb/gopherlogs
2. Note the NaN for Average per week
3. Visit https://deploy-preview-3893--oss-insights.netlify.app/s/jpmcb/gopherlogs
4. Not the 0 for Average per week
=> fix: calculate avergage per week for ross contributors greater than 0

components/organisms/TopNav/top-nav.tsx, components/organisms/UserSettingsPage/user-settings-page.tsx, components/shared/AppSidebar/AppSidebar.tsx, next-types.d.ts
- Fixes a bug where a user can complete onboarding without picking any interests
- This makes the `interests` field options on the user information and adds necessary guards
Fixes #3649
Fixes #3865
1. Login with a new account and go through onboarding without picking interests
2. Navigate to workspaces page
3. Navigate to user profile page
4. Note no errors occur
=> fix: update profile interests type to be optional and add guards

pages/s/[org]/[repo]/contributors.tsx
- Adds a `display=list` query parameter to be able to toggle the list view for contributors on repo pages
1. Go to a repo page
2. Go to the contributors tab
3. Toggle the list view for the contributors
4. Note the `display=list` query param in the URL
5. Refresh the page
6. Note the list view is displayed by default
=> feat: add display query param for toggling repo contributors list view

components/molecules/NewsletterForm/newsletter-form.stories.tsx, components/molecules/NewsletterForm/newsletter-form.tsx, pages/feed/index.tsx, public/__newsletter.html
- Converts newsletter form submission to new form structure for Netlify
Docs: https://docs.netlify.com/frameworks/next-js/overview/#netlify-forms-compatibility
Fixes #3796 
1. Go to `/feed` page
2. Go to newsletter subscribe form
3. Enter an email address
4. Click `Subscribe`
5. Note the form completes successfully
6. Go into the Forms section in Netlify for the app and see the submission
=> fix: re-enable newsletter form on Netlify

lib/hooks/api/useContributorList.ts, pages/workspaces/[workspaceId]/contributor-insights/[listId]/edit.tsx, pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx
Now, the contributor insight contributor grid on the overview page pages data again in the grid. When moving to the new grid, `setPage` on the `useContributorsList` hook was no longer being used, so the data fetching wasn't fetching new data as the page wasn't being updated even though it was updated in the browser URL bar.
Fixes #3944
**Before**
**After**
1. Go to a contributor insight overview page, e.g. https://deploy-preview-3945--oss-insights.netlify.app/workspaces/3432aaf7-55db-4c2b-9fde-f61604471e21/contributor-insights/aaf5ec66-9d3a-456d-b62b-05410e0b2fa4/overview
2. In the grid page selection underneath the grid, click on `2`.
3. Notice the grid updates to the second page of contributors.
=> fix: fixed contributor insight contributor grid not loading paged data

components/organisms/DevCardCarousel/dev-card-carousel.tsx, pages/u/[username]/card.tsx
CSS changes to the `/u/<username>/card` page to ensure users are able to see the socials buttons and create their own dev card buttons.
Closes #3923 
**BEFORE**
https://github.com/user-attachments/assets/c0c26468-d8a2-413d-a0cf-30aa0a58e8cd
**AFTER**
https://github.com/user-attachments/assets/38a0d203-c4a0-4369-8686-197551965688
=> fix: now the Dev Card share buttons appear on all screen sizes

pages/start.tsx
Updates the onboarding flow to authenticate, set your time zone, and share your dev card.
https://github.com/user-attachments/assets/042748e6-c594-43b2-a5c3-8bbea4110fb9
1. Reset your onboarding flag
2. Login
3. Click on `Complete Onboarding` from the nav bar
4. Go through onboarding
=> feat: update onboarding steps to include sharing the DevCard

pages/s/[org]/[repo]/index.tsx
Updates SBOM link to OpenSauced docs
Closes #3956
=> fix: add docs link for SBOM to repository page

pages/u/[username]/card.tsx
Caches the dev card page for one hour. I haven't made it super long yet, as there's a mechanism we need to put in place for profile pages and this page which is leveraging [Netlify's purge of cache keys](https://www.netlify.com/blog/cache-tags-and-purge-api-on-netlify/).
That said, one hour is still solid and stale while revalidate is in place, so it should perform well. The only reason I put an hour is if the bio changes or other stats (related to purge mentioned above).
Deploy Preview compared to Beta App's dev card page
**TLDR;**
**With caching:**
Slowest:      2.6015 secs
Fastest:      0.0161 secs
**Current Beta Site (no caching)**
Slowest:      17.4056 secs
Fastest:      4.4655 secs
```bash
❯ oha --no-tui https://deploy-preview-3968--design-insights.netlify.app/u/nickytonline/card …
```
=> feat: now the dev card page is cached for one hour

netlify.toml
- Adds a redirect for `oscr.me/{username}` to the respective DevCard URL for the username
- Adds default redirect for `oscr.me`
Closes https://github.com/open-sauced/app/issues/3917
=> feat: add redirect for oscr.me to DevCard

pages/s/[org]/[repo]/index.tsx
I accidentally added a file to cee5fa8d that shouldn't have gone in. It will be part of #3966.
Relates to #3977
=> fix: reverted a file that accidentally went in cee5fa8d

components/organisms/SearchDialog/search-dialog.tsx
This PR fixes #3978 
This PR addresses an issue where the `searchOpenSaucedAPI` promise returns an empty response, causing `userData.data` to be undefined. 
1. Added a null check to verify if userData.data is undefined.
2. Initialized userData.data as an empty array if it is undefined.
3. Updated the state management to ensure the application handles empty or undefined responses gracefully.
Fixes #3978 
[screen-capture (24).webm](https://github.com/user-attachments/assets/50b61755-b2fa-48f7-b45d-9fcd490aa0dd)
1. Click on the search bar at top right corner of landing page
2. Search for anything (look for a long string)
=> fix: Searching for a user/repository name throws error and crashes page

npm-shrinkwrap.json, package.json
- Updates PostHog SDK to current latest version to remove dashboard warning
Closes #3994
=> fix: update PostHog SDK to latest version (1.152.7)

components/Workspaces/InsightUpgradeModal.tsx
- Adjusts workspace upgrade modal w/pricing
1. Login
2. Choose a workspace over the limit
3. Go to the workspace upgrade modal
4. Note the new pricing
5. Click the upgrade button to go to the test checkout
=> fix: adjust workspace upgrade pricing modal

components/organisms/Repositories/repositories.tsx
- Always displays `Add to Workspace` button in repositories table
- Logs a Posthog event when the button is clicked with the workspaceId and selected repositories.
1. Go to explore page
2. Note `Add to Workspace` is disabled
3. Select some repositories
4. Note `Add to Workspace` is enabled
5. Click button and navigate to new workspace page with repos selected
=> fix: always show Add to Workspace button on repositories table

pages/s/[org]/[repo]/index.tsx
Wraps the `YoloChart` component with CopyContainer to allow users to copy it as an image with a branding bar on top. Implements PostHog captures for analytics.
Closes #4013 
1. Go to a repository page with YOLO Coders
2. Click the YOLO banner to see the chart
3. Click to copy image by the top-right button
4. Paste the image to ensure the component + branding bar shows with correct info
=> feat: copy repo page YOLO Chart as image

components/Repositories/RossChart.tsx
Uses `toReversed()` function to create a reversed copy of `stats.contributors` instead of using `reversed()` in place, which causes the data to flip on every filter change
Closes #3993
**Before**
https://github.com/user-attachments/assets/c2bc652b-16c2-4b70-9a9e-88aee0f5cff7
**After**
https://github.com/user-attachments/assets/f9c5ce67-a018-430e-b3b4-e6fbde6fb7da
=> fix: `RossChart` order changing on filter

components/organisms/UserRepositoryRecommendations/user-repository-recommendations.tsx
There seems to be a small typo in Recommendations tab of the profile page.
1. Go to Profile page
2. Click on Recommendations
3. If no recommendations show up, the text contains a type
4. It should now be fixed
=> fix: fixed typo for recommendations

components/Repositories/RossChart.tsx, pages/s/[org]/[repo]/index.tsx
Repository page's Contributor `RossChart` can now be copied as an image by clicking a button available on hover. Implemented with `html2canvas-pro` via `CopyContainer`; implements PostHog captures for analytics. 
Closes #4021 
**With filter off (`Internal`)**
1. Go to a repo page and hover over the 'Contributors' chart
2. Click the button that appeared on the top right corner to copy the chart
3. Paste image to GitHub, Twitter, etc. textbox to see image and confirm information
4. Go to PostHog events and check if the click sent the event `Repo Pages: clicked Contributors (ROSS) chart`
=> feat: copy repo page Contributors chart as image

pages/s/[org]/[repo]/index.tsx
Repository page's Stars chart can now be copied as an image by clicking a button available on hover. Implemented with `html2canvas-pro` via `CopyContainer`; implements PostHog captures for analytics.
Closes #4023 
1. Go to a repo page and hover over the 'Stars' chart
2. Click the button that appeared on the top right corner to copy the chart
3. Paste image to GitHub, Twitter, etc. textbox to see image and confirm information
4. Go to PostHog events and check if the click sent the event Repo Pages: clicked Stars chart
=> feat: copy repo page `StarsChart` as image 

pages/s/[org]/[repo]/index.tsx
Repository page's Forks chart can now be copied as an image by clicking a button available on hover. Implemented with `html2canvas-pro` via `CopyContainer`; implements PostHog captures for analytics.
1. Go to a repo page and hover over the 'Forks' chart
2. Click the button that appeared on the top right corner to copy the chart
3. Paste image to GitHub, Twitter, etc. textbox to see image and confirm information
4. Go to PostHog events and check if the click sent the event Repo Pages: clicked Forks chart
=> feat: copy repo page `ForksChart` as image

components/Repositories/AddToWorkspaceDrawer.tsx, components/Workspaces/WorkspaceLayout.tsx, components/atoms/Select/single-select.tsx, components/shared/DayRangePicker.tsx, pages/s/[org]/[repo]/index.tsx
Fixes the repo page overflowing on mobile view. Changes were mainly to the 'controls' section of the page (Add to buttons, share, and day range picker) for both mobile and desktop views.
Closes #4050 
**Before**
**After**
1. Go to repository page on mobile
2. See the width is within screen width
3. Use desktop view to ensure no changes were made to its width
=> fix: repository page width overflow

.sauced.yaml, CODEOWNERS
Adds a .sauced.yaml to the project and a regenerated OWNERS file care of `pizza generate codeowners ./ -c ./.sauced.yaml`
Closes #4037
Check the PR to see if the CODEOWNERS file is value (GitHub lets you know)
=> chore: added .sauced.yaml and newly generated CODEOWNERS file

components/atoms/Select/single-select.tsx, components/shared/AppSidebar/AppSidebar.tsx
a layout issue in the `AppSideBar` component caused by a recent change to the `SingleSelect` component. Specifically, when a tooltip for long titles was added to `SingleSelect`, a width was set that inadvertently disrupted the layout.
Fixes #4031 
Problem :
fixed 💯 :
=> fix: correct width issue caused by tooltip addition in SingleSelect

components/Repositories/LotteryFactorBadge.tsx, components/Repositories/LotteryFactorChart.tsx, components/molecules/RepoRow/repo-row.tsx, components/organisms/Repositories/repositories.tsx
Update the repository table with Lottery Factor, replacing the PR Velocity column. Implements a new `LotteryFactorBadge` that is lifted from `LotteryFactorChart` into its own component.
Closes #4007 
1. Go to the explore or workspace page
2. See the new table; check in mobile as well
=> feat: display lottery factor on Repository Table

components/Contributors/Oscr.tsx
This PR adds feature to open readmore(option displayed on oscr score tooltip) page of OSCR in new tab 
Fixes:#4001
=> feat: OSCR learn more link opens in a new tab now

.github/CODEOWNERS
Removed old CODEOWNERS in favour of root directory one.
Relates to #4037
N/A
=> chore: removed old CODEOWNERS in favour of root directory one

components/Contributors/Oscr.tsx, components/organisms/ContributorCard/contributor-card.tsx
Now, the OSCR pill is aligned with the username
fixes #4034 
Before
After
Desktop
Mobile
1. Go to the repository insights
2. see the grid view of contributor's tab
=> fix: align OSCR pill with the username

.github/workflows/development.yml, .github/workflows/issue.yml, .github/workflows/playwright.yml, .github/workflows/release.yml, .github/workflows/storybook.yml, .github/workflows/triage.yml
Uses a powerful runner for the Playwright tests
Followup to #4064
=> feat: Use powerful self hosted runner for playwright tests

pages/s/[org]/[repo]/index.tsx
Removes the `windowWidth` option on the `CopyContainer` for the Activity and Engagement charts on repo pages.
Closes #4028 
**Mobile (smaller width)**
**Larger desktop view**
=> fix: remove set width for repo pages charts

.github/workflows/pizza.yml
This pull request adds a new GitHub Actions workflow, [pizza-action](https://github.com/open-sauced/pizza-action) to automate stuff for the organization. Currently it updates the CODEOWNERS file.
It runs on a weekly schedule. Sunday at midnight UTC and allows for manual triggering as well.
Closes #4074
N/A
N/A
=> chore: added the OpenSauced GitHub action pizza-action

pages/workspaces/[workspaceId]/contributor-insights/index.tsx
Now contributor insights page has the correct message when there are no insights
fixes #4089 
Before
After
1. Click on the "Contributor insights" button on the sidebar
2. Make sure there are no insights for Contributor insights
3. Now you have the correct message:  "You currently have no contributor insights"
=> fix: correct no insights message on contributor insights

playwright.config.ts
- Updates assertion timeouts to 10 seconds
- Adds `_` as numeric divider
Closes #4072
=> chore: configure assertion timeout for e2e tests

pages/explore/index.tsx
Sets the following workspaces for the `/explore` page's "Discover Workspaces" section.
Closes #4105 
_Note_: The Workspace cards will error out since the deploy preview will be under the Beta DB instead of the Prod DB.
Check these workspaces are public using `app.opensauced.pizza/workspaces/<id>`:
1. **"b355ecef-76a5-4451-972a-281e16ccf2e4"**: // Brandon's "Angular"
2. **"0950814d-ed16-4201-add8-d17479cfdc1f"**: // Zeu's "OSS Companies"
3. **"190972f6-caa8-4a90-a21d-2322259b90c7"**: // Bekah's "CNCF Top 30"
4. **"4835f232-ec69-474d-9b88-b2b779015e08"**: // John's "Go Hotness"
5. **"7b540a5d-a767-4f8f-8295-2eccf31ca568"**: // Brian's "Vite Ecosystem"
6. **"380d1129-cd99-4958-83c7-f5d8c4f778af"**: // Nick's "Daishi's Greatest Hits"
=> fix: set workspaces for `/explore` "Discover Workspaces" section

.github/workflows/pizza.yml
=> chore: update pizza action version

pages/u/[username]/card.tsx
I have fixed the warning by adding a title to the iframe
fix #4134 
Run the `npm run lint`
Run the `npm run lint`
=> fix: a11y rule "iframe-has-title" fails with a warning.
