components/organisms/ToolList/nav.tsx
layouts/filter.tsx

- This pr fixes an overflow bug on the dashboard page by including an `overflow: hidden` property on the `filter.tsx` container
- Fixes: #677 
https://user-images.githubusercontent.com/66219025/209103278-ba0a3c6a-e3e8-4a1e-b173-7c5a987ca8f0.mp4

fix: overflow x bug on dashboard

---

components/molecules/InsightHeader/insight-header.tsx
layouts/hub-page.tsx
lib/hooks/useSupabaseAuth.ts

Adds an Edit Button inside of existing Insight Pages to navigate easily to editing the page from inside.
fixes #685

feat: add Edit Page button to insight pages

---

components/atoms/InsightBadge/insight-badge.tsx
components/molecules/InsightHeader/insight-header.tsx
components/molecules/NivoScatterChart/nivo-scatter-chart.tsx
components/organisms/Dashboard/dashboard.tsx
layouts/hub-page.tsx

This PR: 
- fixes some minor CSS styling bugs in the `InsightsHeader` component
- made the scatter chart hover card display with conditionally
- Adds truncate to insights page name to prevent layout break when the page name is lengthy
The main cause of the layout break was a `min-w-full` class name on the hub layout contain... and change to `w-full` fixed the issue, as `min-w` seems to ignore the parent's container's width in this case
Fixes #769

fix: mobile insights header layout break

---

components/molecules/ContributorProfileInfo/contributor-profile-info.tsx
components/organisms/ContributorProfilePage/contributor-profile-page.tsx
components/organisms/UserSettingsPage/user-settings-page.tsx
lib/hooks/update-user.ts
lib/utils/timezones.ts
next-types.d.ts

This PR:
- Connects `Display Local Time` and `Timezone` to the API for updates

fix: connect more user profile settings to the API

---

components/molecules/HighlightInput/highlight-input-form.tsx
stories/molecules/highlight-input.stories.tsx

This PR: 
- creates a new form UI to enable users post highlights of PRS
- Text area row is expandable with a limit of 5 (felt 5 is a good number of row before overflow scroll triggers)
- The post button is disabled until the `TextBody` has values in it
Note: 
> This is just UI for now, follow up issue will be opened for the implementation
Fixes #828

feat: add highlights input form to design system

---

components/organisms/InsightPage/InsightPage.tsx

This PR fixes the issue where, when editing an insight page, the create page button is disabled even if the page name is there.
Fixes #892
The cursor is not visible :sweat: 
[insights-page-bug.webm](https://user-images.githubusercontent.com/79809121/220359360-408f1652-3907-49f5-a522-a5f7d350bf8e.webm)

fix: disable create page button only if insight page name is empty

---

components/organisms/InsightPage/DeleteInsightPageModal.tsx
components/organisms/InsightPage/InsightPage.tsx

This PR adds the ability to delete the insight page. Once the user clicks on the button "delete page" a confirmation modal will appear and ask the user to write `DELETE` in order to confirm the deletion.
Fixes #853

feat: delete insight page

---

components/organisms/UserSettingsPage/user-settings-page.tsx
lib/hooks/useFetchUser.ts

This PR:
- Only stores the initial user profile settings in the form, and does not refresh when focusing the window again
Fixes #931

fix: keep initial user settings data after being fetched

---

components/molecules/FilterHeader/filter-header.tsx
lib/utils/getInterestOptions.ts
lib/utils/getTopicOptions.ts

This PR:
- Adds Rust back to the options for interests and filtering
Closes #976

fix: add Rust to interests options and combine utility function

---

components/molecules/AlertDialog/alert-dialog.tsx
components/molecules/ContributorHighlight/contributor-highlight-card.tsx
lib/hooks/deleteHighlight.ts
lib/hooks/useFetchUserHighlights.ts
npm-shrinkwrap.json
package.json

This PR:
- Adds delete button to delete a highlight
- Adds alert dialog to prompt a user to confirm delete action or cancel
Fixes #906

feat: Add delete highlights implementation

---

components/organisms/StripeCheckoutButton/stripe-checkout-button.tsx

Centers the  text inside the upgrade access button in the Reports page.
#1024

fix: center text inside upgrade access button

---

pages/feed/index.tsx

This PR intends to fix the avatar misalignment in https://insights.opensauced.pizza/feed.
Closes #1035. 
Before the patch:
After the patch:

fix: update avatar style to remain aligned with the input field

---

layouts/hub-page.tsx
layouts/hub.tsx

This PR fixes the width issue of the insights layout on lager screen sizes
Fixes #1043

fix: insights hub layout inconsistencies on larger screens

---

components/molecules/HeaderLogo/header-logo.tsx

#1063 decreased the size of the "Connect w/ GitHub" button for smaller screen, but also hid the OpenSauced Text Logo for below `xs` breakpoint.
This diff fixes that behavior and shows the logo even for smaller screens.
Fixes #1068
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
- check CI is green and there are no visual defects in UI.
no gif for now ;) but here is my co-author:

fix: show logo in the header for smaller screens

---

pages/start.tsx

This PR redirects the user to the dashboard with repos after onboarding and centers the texts in the buttons.
Fixes #1090 
https://user-images.githubusercontent.com/79809121/231912436-2000eaa7-04e7-4e14-a2a8-886d08f7ef49.mp4
| ------ | ------ |
| ![step-1-before](https://user-images.githubusercontent.com/79809121/231911936-8770a432-e016-4c83-a788-a7481b88ee70.png) | ![step-1-after](https://user-images.githubusercontent.com/79809121/231911954-1745c758-aaee-4a18-9979-9e55c927c35f.png) |
| ![step-2-before](https://user-images.githubusercontent.com/79809121/231911978-f6cfc5e2-5314-40b4-8a44-5b8c76b24bfb.png) | ![step-2-after](https://user-images.githubusercontent.com/79809121/231911992-88540c62-ce92-4609-b405-c5107cdf1ec5.png) |
| …

feat: redirect user to the dashboard with repos after onboarding

---

components/organisms/UserSettingsPage/user-settings-page.tsx

changed  breakpoint for the gap between profile and intrests md:42 and lg:48 that seemed to fix it
fix #1128
changed  breakpoint for the gap between profile and intrests md:42 and lg:48 that seemed to fix it
Fixes #1128

fix: user-setting-page breaks in ipad-mini

---

components/molecules/ContributorHighlight/contributor-highlight-card.tsx

This PR fixes the bug #1078.
Container div element was missing, which caused the icon and the link to misalign.
cursor-pointer class were added to both Copy link and Follow user buttons
Fixes #1078

fix: copy link button alignment

---

pages/_app.tsx

This PR hides the chatbot on non-production environments and on mobile screens.
> **Note**
```tsx
{!isMobile || NODE_ENV === 'production' || hostname === 'insights.opensauced.pizza' && (
<Script id="siteGPT" type="text/javascript">
..
</Script>
```
The code above won't work because:
- if you visit the app on desktop (first load), the chatbot will be there but won't go away when you switch on mobile (using devtools)
- if you visit the app on mobile (first load), the chatbot will be hidden and when you expand to desktop, it will show up. But if you go back to mobile, it will still be there.
The reason why that's happening is that, when the `script` is rendered, it will inject a button in the DOM, so even if you change the view to mobile and the script is hidden (like the code above), that …

feat: hide chatbot on non-prod environment and mobile screens

---

components/molecules/Pagination/pagination.tsx
components/molecules/PaginationGotoPage/pagination-goto-page.tsx
components/molecules/PaginationResults/pagination-result.tsx
pages/feed/index.tsx

Refactor PaginationResults component to display entity count for better readability and user experience. The component UI has been modified to adjust for smaller screens by replacing "block" with "inline-block". The "md:block" class has been changed to "md:inline-block" to maintain visual consistency. The entity count is now displayed with a space before it for improved readability.
_description created by [OpenSauced](https://opensauced-ai.netlify.app/)_
Fixes #1131 
Before:
After:

fix: pagination medium screens

---

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx

Add PostHog tracking to ContributorProfileHeader component. The usePostHog hook is imported and used to capture the event when the user copies the profile URL to the clipboard. The captured event includes the user's username.
Leverage this tutorial as a guide from the posthog documentation
https://posthog.com/tutorials/nextjs-analytics
Need to update posthog live events dashboard to capture data in a shareable dashboard.

feat: add share tracking

---

pages/pages/[userOrg]/[filterName]/[toolName].tsx
pages/pages/[userOrg]/[filterName]/[toolName]/filter/[...selectedFilter].tsx

- Fixes a redirect issue when visiting a public insight page
- Uses insight data returned from server side instead of re-fetching on the client

fix: remove duplicate redirect check and use server props on insight page

---

layouts/filter.tsx
layouts/hub-page.tsx
layouts/hub.tsx
layouts/login.tsx
layouts/profile.tsx

Refactor the layout components so that there are no hard-coded values.
Fixes #175
The layout should not change from this change.

refactor: remove hard-coded height from layouts

---

pages/feed/index.tsx

This PR fixes a bug where the single highlight dialog was not being closed after clicking the close button or the overlay. The `setOpenSingleHighlight` state is now properly updated when the highlight modal is closed.
Fixes #1267 
Before
https://github.com/open-sauced/insights/assets/79809121/9b07f50a-6918-4016-be86-376efe8ac3d5
After
https://github.com/open-sauced/insights/assets/79809121/758f4fdd-9109-4037-a591-25f5515f2c8f

feat: handle close highlight dialog

---

pages/feed/index.tsx

This PR Links the Contributor Info `div` (which contains the contributor's `Avatar` component and **login/username**) on the single highlight `Dialog` component to the contributor's profile on route `/user/[username]`
Code Sample
```javascript
// pages\feed\index.tsx
<Link href={`/user/${singleHighlight.login}`} className="flex items-center gap-3">
<Avatar
alt="user profile avatar"
isCircle
size="sm"
avatarURL={`https://www.github.com/${singleHighlight.login}.png?size=300`}
/>
<strong>{singleHighlight.login}</strong>
</Link>
```
Fixes #1276 
**Before** 
https://github-production-user-asset-6210df.s3.amazonaws.com/25631971/246900915-847f8e76-4f74-4b39-b113-6a0e6cdb3dc6.webm
**After**
https://github-production-user-asset-6210df.s3.amazonaws.com/25631971/246901000-f1e27d4e-e1fe-4b33-bb05-04c3 …

fix: linked single highlight dialog's contributor info div to contributor profile

---

lib/utils/timezones.ts

"fix #1275"
This PR fixes the issue related to local time formatting on the user's profile, the local time is properly formatted on the user's profile. If the minutes are less than 10, then a leading zero will be displayed and time will be properly displayed in 12 hours format.
Fixes #1275

fix: properly format local time displayed on user's profile

---

components/atoms/UserCard/user-card.tsx
stories/atoms/user-card.stories.tsx

Add UserCard component and its story to the project. UserCard is a reusable component that displays user information such as name, username, avatar, followers count, following count, and highlights count. The component uses the getAvatarByUsername function from the lib/utils/github module to get the user's avatar image. The component is designed using Tailwind CSS classes and is responsive. The story file includes two stories, one with activities and one without activities.
Closes #1288

feat: add `UserCard` component to storybook design system

---

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx

This PR implements the ability to Hide Highlight Tabs Content and Trigger components for user Profiles that either haven't connected their GitHub or most notably haven't posted any highlights.
This was done by conditionally rendering the `hidden` utility class on the `TabsTrigger` component item. 
```javascript
<TabsTrigger
key={tab}
className={clsx(
...
user?.user_metadata.user_name !== login && !hasHighlights && tab === "Highlights" && "hidden",
...
)}
value={tab}
>
...
</TabsTrigger>
```
...and conditionally rendering its associated `TabsContent` component
```javascript
{(user?.user_metadata.user_name === login || hasHighlights) && (
<TabsContent>
...
</TabsContent>
)}
```
I also address the case where currently logged in user has no highlights, ensuring the Highlight Tab Components …

feat:  hide highlights tab components on profiles without highlights

---

pages/user/[username]/requests.tsx

- Adds a URL to link to collaboration requests
- Allows direct link to "Requests" tab for the logged in user to see pending collaboration requests
Example URL:
https://deploy-preview-1305--oss-insights.netlify.app/user/bdougie/requests

feat: add URL for collaboration requests

---

components/molecules/DevCard/dev-card.tsx

This PR fixes the date format of the first contribution day on the `DevCard` component. The initial set-up displays the date in `days`.
```javascript
// insights/components/molecules/DevCard/dev-card.tsx
{props.age !== undefined && (
<div className="flex items-center">
...
<div className="flex text-xs">{props.age}d</div>
</div>
)}
```
This fix leverages the `getRelativeDays` date utility function as there's a need to address first contributions that are `day`, `month` up to `year` old
```javascript
// insights/components/molecules/DevCard/dev-card.tsx
{props.age !== undefined && (
<div className="flex items-center">
...
<div className="flex text-xs">
{getRelativeDays(props.age)}
</div>
</div>
)}
```
fixes #1317 
BEFORE
AFTER
NA

fix: DevCard component first contribution date format

---

components/molecules/ContributorHighlight/contributor-highlight-card.tsx
components/molecules/InsightHeader/insight-header.tsx

Added analytics tracking for contributor highlight card and insight header
- Added `usePostHog` hook from `posthog-js/react` library to track user actions
- Implemented tracking for sharing highlights on LinkedIn, Twitter, and copying highlight link to clipboard
- Implemented tracking for copying insight link to clipboard
This PR adds analytics tracking to the contributor highlight card and insight header components, allowing us to gather data on user interactions and engagement.
Fixes #1324

feat: implemented  tracking on every share button

---

components/molecules/LatestPrTableHeader/latest-pr-table-header.tsx

This PR swaps the last commit date icon with a calendar 
Fixes #1346 
Before 
After

feat: changed the last commit date icon with a calender

---

components/molecules/HighlightInput/highlight-input-form.tsx

This PR updates the behaviour of the Title field so that it conditionally hides the Description field only when the Description field has zero content.
Fixes #1354 
Before :
[Screencast from 15-07-23 03:08:39 PM IST.webm](https://github.com/open-sauced/insights/assets/25549935/040a5d88-c562-4cd0-98d4-82068096232e)
After :
[Screencast from 15-07-23 03:09:35 PM IST.webm](https://github.com/open-sauced/insights/assets/25549935/da56d19d-8f3b-4b37-ae45-677d6ab976b8)
:smiley:

fix: Improved the user experience of the highlights input form

---

lib/utils/urls.ts
pages/api/user/[username]/card.png.tsx

I think we're running into this netlify caching issue for the static image endpoint. https://answers.netlify.com/t/netlify-function-with-query-strings-ignores-custom-cache-control-header/15390/1
I can reproduce it if i go to one of these URLs and then the other one.
- https://insights.opensauced.pizza/api/card.png?username=foxyblocks
- https://insights.opensauced.pizza/api/card.png?username=bdougie
This change moves the endpoint so that the username parameter is part of the path so the cache is correctly busted for different users.
I've yet to figure out how to access these parameters from the request other than doing string parsing. `request.nextUrl.searchParams.get('username')` works locally but doesn't work when deploying to netlify, probably due to some difference in runtime …

fix: Move card image api route

---

components/molecules/HighlightInput/highlight-input-form.tsx

This PR Factors in the `pullrequestLink` into `HighlightInput` form `isDivFocused` condition which is in charge of the toggle behaviour triggered by the Title Field of the `HighlightInput`.
Now the Title field conditionally hides the other form fields only when the Description or Pull Request Link field has zero content.
Fixes #1405 
[screencast-localhost_3000-2023.07.22-18_48_13.webm](https://github.com/open-sauced/insights/assets/25631971/716d4e82-c0c7-4347-959c-f22b59290de6)
NA

fix: factor `pullrequestLink` into `HighlightInput` form `isDivFocused` condition

---

components/atoms/FullHeightContainer/full-height-container.tsx
components/molecules/AuthSection/auth-section.tsx
components/molecules/DevCard/dev-card.tsx
components/molecules/TopContributorsPanel/top-contributors-panel.tsx
components/organisms/DevCardWall/dev-card-wall.tsx
img/icons/chevron-left.svg
lib/hooks/useFetchTopContributors.ts
pages/404.tsx
pages/user/[username]/card.tsx
stories/organisms/dev-card-wall.stories.tsx

Adds a new custom 404 page that shows dev cards from various users. 
Closes #910 
https://github.com/open-sauced/insights/assets/555044/61a5cbb4-d3e6-4394-bedb-2e203af2891d

feat: 404 page

---

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx

This PR fixes the issue with tab inconsistency on the user profile page. Before now, when you visit a user profile with no highlights, the Highlights tab is active but hidden, leaving the contributors tab inactive but visible and blank. 
This PR fixes the issue by making the `hasHighlights` variable a state and updating the state with a `useMemo` hook to prevent unnecessary rerenders
Fixes #1402
https://github.com/open-sauced/insights/assets/62995161/65e72666-5731-409a-af03-53ccfbbabc98

fix: tab inconsistency in user profile matching the url

---

styles/globals.css

This PR fixes the issue of the misaligned chat close button icon. I also formatted the globals.css file better.
Fixes #1407

fix: misaligned chat close button icon

---

pages/feed/index.tsx

This PR adds an extra dependency to the `useEffect` dep array that updates the repo filter state after the repos are fetched from the API. before now, the state is not updated on first time visit and as a result, the repoFilter options dont show up.
Fixes #1423 
https://github.com/open-sauced/insights/assets/62995161/7160ca24-01f6-4bcb-942f-42f32b92aaa2

fix: show repo filters on initial `feeds` route visit

---

pages/_document.tsx

This PR fixes the issue of the mismatched selection color.
Update _document.tsx to include a new class for the body element. The new class sets the background color and text color for selected text.
Fixes #1424

fix: mismatched selection color

---

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
lib/hooks/useContributorPullRequestsChart.ts
pages/_app.tsx

This PR fixes a bug with the user profile tab toggle. refer to video and before and after below for more context.
The intention was initially to fix the contributions graph cut in the user's profile. After going through the charts library docs, I found this option https://echarts.apache.org/en/option.html#series-line.clip which is set to true by default and Clips all the overflowed lines. Not sure this fixes the issue, and that can be confirmed in this PR 😅 . I also increased the height of the chart and reduce to margin from top in relation to its siblings.
Fixes #1285 
https://github.com/open-sauced/insights/assets/62995161/2aa11132-e838-4481-9765-5ba5ae1cab31
https://github.com/open-sauced/insights/assets/62995161/4ea8f941-fa43-492c-868e-dd2857a4725a

fix: contributor profile tab click state flicker

---

components/molecules/RepoRow/repo-row.tsx
components/organisms/Repositories/repositories.tsx

This PR fixes the issue of Odd design for large screens #1231
-  Fixes #1231.
**Before**:
**After**:

fix: improve layout design for large screens #1231

---

components/atoms/Checkbox/checkbox.tsx

This PR fixes the similar IDs for the checkboxes in the whole repo, the previous behavior was using the same name for each checkbox, this PR will allow to generate a unique id based on the label.
**Important note:**: The GitHub UI is showing unnecessary changes due to changing spaces in the file, hiding spaces would show a better changes: 
Another option would be going to `github.dev` to review this. 
to go to `github.dev` you need to do one of the next:
- click `.` dot in the keyboard
- change the `.com` in the URL to `.dev`
fixes #1448
The checkbox elements and labels are connected to their related inputs:
To Test you need to do the next: 
- Go to: https://insights.opensauced.pizza/user/settings 
- Click on the check boxes labels one and see if their related check box is …

fix: add checkbox id name if not available based on label

---

components/atoms/TopContributorCard/top-contributor-card.tsx
components/atoms/UserCard/user-card.tsx
components/molecules/AnnouncementCard/announcement-card.tsx
components/molecules/FeaturedHighlightsPanel/featured-highlights-panel.tsx
components/molecules/HighlightInput/highlight-input-form.tsx
components/molecules/HighlightsFeedCard/highlights-filter-card.tsx
components/molecules/NewsletterForm/newsletter-form.tsx
components/molecules/TopContributorsPanel/top-contributors-panel.tsx

This PR fixes general style inconsistency on the feeds page. The changes are not easily noticeable. You can get more context on what has changed [here](https://github.com/open-sauced/insights/issues/1465)
Fixes #1465

fix: feeds page typography and styles improvements

---

components/molecules/AuthSection/auth-section.tsx

- Fixes a bug in the useEffect for getting the user information for the notifications check
- Also updates the copy for unread notifications
BEFORE:
AFTER:

fix: uses session to update user info for notifications check

---

layouts/private-wrapper.tsx

This PR fixes the Insights page redirecting to Dashboard on page reload.
Fixes #1503 
Before :
After :
:smiley:

fix: on page reload Insights page redirecting to Dashboard

---

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
e2e-tests/OpenUserProfile.spec.ts

This Pull Request addresses the browser compatibility issue causing regression on the `/user/[username]` route on some mobile browsers, which arose from the usage of `at` array method in the component below...
https://github.com/open-sauced/insights/blob/c4c56098826f085e5c551e088ac4fc3ada969f34/components/organisms/ContributorProfileTab/contributor-profile-tab.tsx#L67
- Considering the intention was to select the last item on the array returned from `router.pathname.split('/')`, I replaced the usage of `at` array method with a computation of `[array].length - 1` then use the derived value as `index` to access needed item.
```js
const pathnames = router.pathname.split("/");
pathnameRef.current = pathnames[pathnames.length - 1];
```
Fixes #1493 
**Before**
**After** …

fix: `/user/[username]` route/page browser support issue

---

.env
components/atoms/Button/button.tsx
components/organisms/UserSettingsPage/user-settings-page.tsx

This PR adds a subscription management section to the user settings page
Clicking on cancel subscription will open a new stripe page where you can fill in your email to continue the cancellation process. This implementation is subject to change in the future when we add the support to the API
Closes https://github.com/open-sauced/ops-backend/issues/117

feat: add subscription management section to user settings

---

components/organisms/FollowersHighlightWrapper/following-highlight-wrapper.tsx
lib/utils/query-params.ts
pages/feed/index.tsx

- Query params are now being reset on resetting repository filters
- URL is now encoded
Fixes #1589 
Fixes #1589 
| --- | --- |
| ![image](https://github.com/open-sauced/app/assets/27003616/fd677508-fa06-4476-9eb5-b4bd9eb1b786) | <video src="https://github.com/open-sauced/app/assets/27003616/603148ec-e231-41f4-a1bb-ca017a882e18" /> |

fix: query param reset in repo filters & URL encoding

---

components/molecules/ContributorHoverCard/contributor-hover-card.tsx

Miscalculation of first PR age was happening because `new Date()` was receiving a numeric value. Resulting in `1970` year being passed to the next function and hence the `53 years age`.
I have made sure to convert the number to a string type using `toString()` method.
Fixes #1606 
Fixes #1606 
| ---- | ---- |
| ![image](https://github.com/open-sauced/app/assets/27003616/39b5aa03-8b44-4feb-b5a2-f87b371aeda0) | ![image](https://github.com/open-sauced/app/assets/27003616/c5be58ba-922f-45d3-b063-d14ec13df49d) |

fix: "53y" showing up as first PR age in Contributor hover Card for dashboard

---

components/organisms/ContributorProfileTab/contributor-profile-tab.tsx

A `<p>` tag which was a flex column, was getting extended along with the link wrapper on it. This caused a hidden link on profile page. I have wrapped the `Link` itself in a `<div>` which causes the flex column properties to apply over it and the children `Link` and `<p>` tag are not extended. The hidden link is now removed.
Fixes #1618 
Fixes #1618 
[hidden-link.webm](https://github.com/open-sauced/app/assets/27003616/b6aa214a-f499-4e6f-babb-252934261466)

fix: hidden link on profile highlights (1618)

---

components/molecules/HighlightsFeedCard/highlights-filter-card.tsx
pages/feed/index.tsx
stories/molecules/highlights-filter-card.stories.tsx

Highlights - Repo filter query params not filtering on page refresh. The query params was not affecting the filters on page. Now, on page reload, it will select the repo present in the query param.
Fixes #1610 
Fixes #1610 
| ---- | ---- |
| <video src="https://github.com/open-sauced/app/assets/27003616/ddf13341-97d4-488d-8777-8b3b3cc9dfbc" /> | <video src="https://github.com/open-sauced/app/assets/27003616/b179d8b0-d323-45ab-a44a-a6452826bd81" /> |

fix: repo filter query not filtering on page refresh (1610)

---

.husky/pre-commit

This PR fixes the same linting operation happening two times to happen once. It decreases the time it takes to commit changes.
Fixes #1622 
Fixes #1622 
No visual changes

fix: lint check happening two times on commit

---

lib/hooks/useUserCollaborations.ts

This Pull Request handles the `401` error that may occus on User collaboration request feature, due to restriction of the feature to only users with upgraded access to open-sauced. It adds a descriptive message to notify a user of the need of an upgraded access to use the feature.
- Add a check for `statusCode` to error response, then append a new toast that carries required message
- ...and left other error to the default handling in the else block.
```js
// lib\hooks\useUserCollaborations.ts
if (req && req.ok) {
const response = await req.json();
toast({ description: "Collaboration request Sent!", title: "Success", variant: "success" });
} else {
const response = await req?.json();
// Changes From Here <--- 🍕🍕🍕🍕
if (response.statusCode === 401) {
toast({
description: "You require an …
```

fix: handle `401` error on collaboration feature

---

components/atoms/Tabs/tabs.tsx
components/molecules/ListCard/list-card.tsx
layouts/hub-page.tsx
layouts/hub.tsx
layouts/lists.tsx
lib/hooks/useList.ts
next-types.d.ts
pages/hub/index.tsx
pages/hub/insights/index.tsx
pages/hub/lists/index.tsx
pages/hub/lists/new.tsx

This PR:
- fixes the alignment of the CTA button in the list (all thanks to @brandonroberts and @jpmcb for noticing the miss alignment in https://github.com/open-sauced/app/pull/1687)
- adds a type for list contributors and a refactor to replace dummy contributors with live data
- adds fetch hooks for lists and contributors
-  refactors the code to break out pages and adds a loader
- adds a redirect to insights tab when a user visits `/hub` route by default. (This is subject to change in the future)
Closes #1668 
Closes #1666

feat: new insights tab layout for list feature 

---

components/molecules/HighlightsFeedCard/highlights-filter-card.tsx
pages/feed/index.tsx

This PR:
1. fixes the React paint issue by keeping the key props value unique and thus, also handles the vertical expansion of "Repositories" table that was leading to spillage.
2. filters the duplicate repos to  make sure only unique repos are rendered in Highlights "Repositories" table at `/feed`.
Fixes #1779
**Before the change**
https://github.com/open-sauced/app/assets/27571141/d8044fd5-f1ee-4390-a1e2-8a700b756a43
**After the change**
https://github.com/open-sauced/app/assets/27571141/820cbc74-45ee-456b-889a-132a5dfe1413

fix: Fix re-rendering of Highlights "Repositories" table with duplicates

---

components/molecules/ListCard/list-card.tsx

This PR removes `+` icon from list contributors stacked avatar on `/hub/lists` route as currently it's not doing anything.
Fixes #1847
**Before the change:**
**After the change:**

refactor: Remove + icon from list contributors stacked avatar

---

pages/hub/lists/index.tsx

This PR resets input state of delete list dialog box after closing the dialog and deleting the list.
Fixes #1848
**Before the change:**
https://github.com/open-sauced/app/assets/27571141/6c757d2e-b7fb-442d-ac6f-2609d99f080d
**After the change:**
https://github.com/open-sauced/app/assets/27571141/7459e0b2-5462-41c3-8b71-6153c020a4cc

fix: reset input state of delete list dialog box after closing the dialog and deleting the list

---

components/TabList/tab-list.tsx

The tab list had an unnecessary x-scrollbar. "md: px-16" gives an extra space to the right of the list, removing the class resolved the issue.
Fixes #1874 
Before 
After

fix: Unnecesary X-Scrollbar in tablist

---

components/atoms/ToggleOption/toggle-option.tsx
components/atoms/ToggleSwitch/toggle-switch.tsx
components/molecules/HubContributorsHeader/hub-contributors-header.tsx
components/organisms/GitHubImportDialog/github-import-dialog.tsx
components/organisms/GitHubTeamSyncDialog/github-team-sync-dialog.tsx
components/organisms/InsightPage/InsightPage.tsx
pages/hub/lists/new.tsx
stories/atoms/toggle-switch.stories.tsx

Now the `<ToggleSwitch />` component requires a label via either the `ariaLabel` prop or the `ariaLabellebBy` prop.
See the MDN docs on the [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) and [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) attributes.
I came across this fix while working on #1977
Fixes #2036
Relates to #1977
https://github.com/open-sauced/app/assets/833231/8d947222-902e-41f8-b678-d1d132230ca5

fix: ToggleSwitch component has required label via aria-label or aria-labelledby

---

pages/hub/insights/index.tsx
pages/hub/lists/index.tsx

Fixes #2074
**Before**
**After**

fix: removed unnecessary CTAs for creating new lists/insights

---

components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx

The title attribute for items in the Most Active Contributors graph has been replaced with a tooltip that says "Coming soon".
Fixes #2077
**Before**
**After**

fix: added tooltips on legend for most active contributors graph where data is not available yet

---

components/molecules/ContributionsEvolutionByTypeCard/contributions-evolution-by-type-card.tsx
lib/hooks/api/useContributionsByEvolutionType.ts
pages/lists/[listId]/activity.tsx
stories/molecules/contributions-evolution-by-type.stories.tsx

Created the Contributions by type of contributor for the list activity page. It can be filtered by date range. Note the original graph has been reworked to be an average line chart and not a raw line chart.
Closes #1601
https://github.com/open-sauced/app/assets/833231/f739e4df-ed0b-4591-819b-d0a8a4c46331

feat: implemented the Contributions by type of contributor graph for the list activity page

---

components/atoms/Cmd/command.tsx

This PR replaces removes the unused components - `CommandEmpty` and `CommandList` from the codebase - `components/atoms/Cmd/command.tsx` as they are not used anywhere and have no plans to use them anytime soon.
**Suggestion**
If we need it in the future, we can revert the removal.
Closes #2129

fix: Remove the unused components - `CommandEmpty` and `CommandLis`t from the codebase

---

pages/index.tsx

The redirects on the main index page should be handled on the server-side, but for now, a quick win is removing the two second client-side timeout.
Relates to #1918

fix: removed two second timeout for initial page load

---

components/molecules/ContributorHighlight/contributor-highlight-card.tsx

This PR [/fixes/] the [/bug/] #2135 
before
after
Fixes #2135

fix: added orange hearts

---

components/Graphs/MostUsedLanguagesGraph/most-used-languages-graph.tsx
styles/globals.css

While implementing the most used languages graph component, I changed how the base font
weight is set so that the font-weight would cascade instead of get reset on literally every element type.
Allowing the natural CSS cascade for the font-weight caused visual regressions. (see https://github.com/open-sauced/app/pull/2158/files#diff-4ee0e71a2145586038d583d58bcbd7aaa6b42318f417f5b62f2cbee48931861bL11-L17) I'll sync with @isabensusan about this, but we should prefer the change I made instead of setting a font-weight on `*` but it will require some more typography cleanup in the app.
**Note that this is only in beta as my PR for the most used languages graph is not in production yet.**
Relates to #2158
**Before**
**After**

fix: reset base font size in * selector in global.css

---

npm-shrinkwrap.json
package.json
pages/lists/[listId]/contributors.tsx

I've added react-error-boundary to the project that allows us to catch errors at the component level and display a fallback component if an error does occur.
Aside from that, it appears the initial contributor list data was causing issues with the component. This was working before, so not sure why removing it now fixes the issue, but as we get larger lists of contributors, it makes sense to offload this to the client-side only, much like the fix in #2215.
Fixes #2240
**Before**
The before view is running the dev server which is why you get the detailed error. If it was production, it would be the classic Next.js black screen of death.
https://github.com/open-sauced/app/assets/833231/8c65a80a-9853-4566-8b62-599d2bb8ec62
**After** …

fix: fixed crash on list contributor grid when in card view changing page size

---

middleware.ts

The speed improvements in #2439 caused a regression with viewing demo insights as a logged out user. This fixes it. I'm not raising a separate issue as this isn't in production yet.
Relates to #2439
1. All the steps from #2439's QA
2. Navigating to `/hub/insights` as a logged out user should show demo insights.

fix: fixed regression where you couldn't view demo insights as a logged out user

---

components/atoms/Card/card.tsx

Small fix to the types of the Card component. With this change, the children and heading props are now `ReactNode` which allows for strings, numbers etc.
```typescript
type ReactNode = ReactElement | string | number | ReactFragment | ReactPortal | boolean | null | undefined;
```
Fixes #2478
N/A

fix: fixed the types for the <Card /> component

---

lib/hooks/useInsightRepositories.ts
pages/pages/[userOrg]/[pageId]/[toolName].tsx
pages/pages/[userOrg]/[pageId]/[toolName]/filter/[...selectedFilter].tsx

- To improve page load speed, insight repositories are fetched separately from insight page information client-side.
- For larger lists such as CNCF dashboards, this would cause a timeout when loading insight page with repository information attached
- Minimal insight page information is still fetched server-side.
- Loading these repositories client-side prevents timeouts from occurring and allows repositories to load data in parallel.
https://beta.app.opensauced.pizza/pages/bdougie/43/dashboard
https://beta.app.opensauced.pizza/pages/bdougie/172/dashboard
1. Visit https://deploy-preview-2496--oss-insights.netlify.app/pages/bdougie/43/dashboard or https://deploy-preview-2496--oss-insights.netlify.app/pages/bdougie/172/dashboard
2. Note page loads without a timeout

feat: fetch insight repos in parallel on insight pages

---

components/Workspaces/SearchReposTable.tsx
components/Workspaces/TrackedRepoWizard/PickReposOrOrgStep.stories.tsx
components/Workspaces/TrackedRepoWizard/PickReposOrOrgStep.tsx
components/Workspaces/TrackedRepoWizard/SearchByReposStep.stories.tsx
components/Workspaces/TrackedRepoWizard/SearchByReposStep.tsx
components/Workspaces/TrackedRepoWizard/TrackedRepoWizard.tsx
components/Workspaces/TrackedRepoWizard/TrackedRepoWizardLayout.tsx
components/Workspaces/TrackedReposModal.tsx
components/Workspaces/TrackedReposTable.stories.tsx
components/Workspaces/TrackedReposTable.tsx
components/Workspaces/WorkspaceLayout.tsx
components/atoms/Search/search.tsx
components/molecules/Dialog/dialog.tsx
components/shared/AppSidebar/AppSidebar.tsx
components/shared/AppSidebar/InsightsPanel.stories.tsx
components/shared/AppSidebar/InsightsPanel.tsx
components/shared/AppSidebar/sidebar-menu-item.stories.tsx
components/shared/AppSidebar/sidebar-menu-item.tsx
lib/hooks/api/useGetWorkspaceRepositories.ts
lib/hooks/useSearchRepos.ts
lib/utils/github-api-fetcher.ts
lib/utils/workspace-utils.ts
next-types.d.ts
pages/workspaces/[workspaceId]/settings.tsx
pages/workspaces/new.tsx

This is under a feature flag atm. Only the OpenSauced team can see it. There is currently minimal workspace creation/edition in the app. This adds the ability to manage tracked repositories.
The search is finicky sometime when searching for a repository. I thought this was something I introduced, but appears to be happening elsewhere in the app as well, e.g. adding repositories in the new insights page, so that will get addressed in a separate issue.
Note that this PR is only for the search by repos flow. Another pull request will introduce search for repost by org (#2505).
There will probably be some additional polish to the whole epic for tracked repositories, but that will be small PRs coming after.
Relates #2437
Closes #2482
https://github.com/open-sauced/app/assets/833231/786f3872-769 …

feat: workspaces can manage tracked repositories now (search repos flow)

---

components/shared/AppSidebar/InsightsPanel.tsx

Adds a skeleton loader for the insights panel component used in the application sidebar.
Fixes #2525
https://github.com/open-sauced/app/assets/833231/6a8e09f6-44e6-47ef-8056-4e6c822e3dee
N/A. You can [test it out in Storybook](https://deploy-preview-2524--design-insights.netlify.app/?path=/story/components-workspaces-insightspanel--loading).

fix: add missing skeleton loader for insights panel

---

lib/utils/workspace-utils.ts
pages/workspaces/new.tsx

Now workspace creation takes only one call thanks to https://github.com/open-sauced/api/pull/512.
This PR updates the creation flow to reflect that.
Relates to #2502
Relates to https://github.com/open-sauced/api/pull/512
N/A
2. Navigate to [deploy-preview-2522--oss-insights.netlify.app/workspaces/new](https://deploy-preview-2502--oss-insights.netlify.app/workspaces/new)
3. Fill in the required workspace info (name) and add some repositories to track.
4. Create the workspace including adding tracked repositories and you'll be redirected to the workspace settings page.
5. Notice the settings load with the basic workspace information and tracked repositories.

fix: now the workspace creation uses the updated endpoint

---

next-types.d.ts

Small followup to https://github.com/open-sauced/app/issues/2515 which adds the missing data types. This wraps up user list graph work done before the `alpha` --> `beta` merge.
Related to: https://github.com/open-sauced/app/issues/2515
N/a: adds missing data points in API:

feat: Adds missing data points on "most-active-contributors" API hook

---

.env
.vscode/settings.json

Quick-followup to https://github.com/open-sauced/app/pull/2532 and 7fab5eadbac5066f8f7ec16d6804b7d3812ce36b where it looks like the `alpha` API was added as the default env.
Also removes the unnecessary `.vscode` directory that looks to have been added
Followup to: https://github.com/open-sauced/app/pull/2532
Run locally and see `beta.api.opensauced.pizza` being used in network calls

fix: Uses beta default .env for API

---

components/organisms/InsightPage/InsightPage.tsx
lib/hooks/api/useRepositories.ts
pages/hub/insights/[insightId]/edit.tsx

Reverts open-sauced/app#2499
Not sure why the build didn't continue to fail with the type error mentioned, but we need to revisit the usage in the edit page for an insight

Revert "fix: Adding new repos to insights on edit page will trigger another API call"

---

lib/utils/server/feature-flags.ts

Hotfix for production as Posthog is down. This is the same fix as #2640 that got merged to main. This PR cherry picks that commit.
Cherry picked from #2640 prod hotfix
Relates to https://opensauced.sentry.io/issues/4970413146/?project=4505082236960768
2. The app loads.

fix: now if Posthog is down, we return null for feature flags or a user (#2640)

---

components/organisms/TopNav/top-nav.tsx

This PR fixes the Complete onboarding button flashes on mobile screens by preventing it from rendering when `onboarded` is undefined.
Fixes #2324 
1. Navigate to any page on mobile and log in to the app.
2. If you haven't completed the onboarding, go ahead and do that.
3. Reload the page to verify the button doesn't flash.

fix: prevent onboard button from flashing on mobile screens

---

components/Workspaces/RepositoryStatCard.stories.tsx
components/Workspaces/RepositoryStatCard.tsx
next-types.d.ts

The engagement card on the repositories dashboard page of a workspace now shows the activity ration instead of the health.
Fixes #2719
**Before**
**After**
2. Navigate to `/`
3. Your last workspace you used loads
4. Notice the engagement stat card has an activity ratio number on 10 instead of a health score.

fix: replaced health with activity ratio

---

pages/workspaces/[workspaceId]/contributor-insights/index.tsx

The contributor insights page had feature flags being loaded server-side, but they're never used. This PR removes them to avoid unnecessary calls to Posthog.
Fixes #2803
1. Go to the landing page for workspace contributor insights
2. Things should load as they normally do.

fix: removed unused feature flags in contributor insights page

---

components/molecules/ListCard/list-card.tsx
components/molecules/WorkspaceRepositoryInsightRow/workspace-repository-insight-row.tsx
components/shared/AppSidebar/AppSidebar.tsx
lib/hooks/api/useWorkspaces.ts
pages/hub/lists/index.tsx
pages/workspaces/[workspaceId]/contributor-insights/index.tsx
pages/workspaces/[workspaceId]/repository-insights/index.tsx

- Fixes UI elements being displayed when not logged in for contributor/repository insights
- Removes public/private indicators from contributor/repository insights as its handled at the workspace level
- Removes edit/delete buttons from contributor/repository list pages when not authenticated
- Does not load workspaces into the sidebar if not authenticated
- Hides the Home and Create New Insight buttons if not authenticated
Fixes https://github.com/open-sauced/app/issues/2837
1. Go to deploy preview without logging in
2. Navigate to https://deploy-preview-2840--oss-insights.netlify.app//pages/brandonroberts/346/dashboard
3. Get redirected to the public workspace
4. Note empty workspaces list
5. Note no Home button in sidebar
6. Note Repository/contributor insights are listed without …

fix: hide UI elements for public workspaces and insights when not logged in

---

components/Workspaces/WorkspaceLayout.tsx
pages/workspaces/[workspaceId]/settings.tsx
pages/workspaces/new.tsx

Fixes #2924
**Before**
**After**
**Settings Page**
**New Workspace Page**
1. Go to your workspace settings page, e.g. /workspaces/some-worspace-id/settings
2. Scroll through the settings.
3. Notice the Update workspace button remains in a fixed footer and content scrolls underneath it.
4. Do the same thing for the create new workspace page, /workspaces/new, and the same behaviour occurs.

fix: now workspace settings and new page have a fixed footer for CTAs

---

lib/hooks/useFetchAllContributors.ts

Removes the unused `pr_velocity` in the list contribs search as we're removing usage of our first party `pull_request` table - see https://github.com/open-sauced/api/pull/674 for more details
Followup to https://github.com/open-sauced/api/pull/674

chore: removes "pr_velocity" from lists contrib search

---

pages/workspaces/[workspaceId]/settings.tsx
pages/workspaces/new.tsx

Fixes a regression by the submit button for creating and updating workspaces was no longer in the form. The fix leverages the button [form attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#form).
1. Go to `/workspaces/new`
2. Enter a name, description optional.
3. Click on the Create Workspace button.
4. The workspace is created.
1. Go to `/workspaces/some-workspace-id/settings`.
2. Update something about the workspace.
3. Click the Update Workspace button.
4. The workspace updates.

fix: fixed a regression with workspaces not updating/creating

---

components/molecules/HeaderLogo/header-logo.tsx

Removes unnecessary markup from the header logo and removes unnecessary alt text on the logo image.
Fixes #3012
The header logo looks the same so nothing to show.
1. Navigate to `/`.
2. The header logo looks the same as the one on https://app.opensauced.pizza

fix: removed unnecessary alt text on logo and cleaned up JSX

---

components/organisms/TopNav/top-nav.tsx

This PR :
- un-fixes the navbar on mobile version
- makes the top navbar scroll with the rest of the page instead of keeping it fixed (only on mobile).
Fixes  #2995

style: un-fix top-nav on mobile

---

components/Workspaces/InsightUpgradeModal.tsx
components/Workspaces/WorkspaceBanner.tsx

- Fixes error shown when visiting a repository insight that needs to display the upgrade banner
- Correctly tracks when the insight upgrade modal is clicked
- Removes usage of useEffectOnce which was causing a hook rendering order error
Closes https://github.com/open-sauced/engineering/issues/274
1. Login
2. Go a non-upgraded workspace that has over 10 contributors in an contributor or 100 repositories in a repository insight
3. Note the upgrade banner is shown without an error
4. Click on the upgrade button
5. Note the upgrade modal is shown without an error

fix: remove useEffectOnce and check if upgrade modal is open before logging

---

e2e/repo-page.spec.ts
lib/utils/server/feature-flags.ts
pages/s/[org]/[repo]/index.tsx

Removes the `"repo-page"` feature flag from the repository page as well as the requirement to be logged in to view the page.
Fixes #3079
Relates to #2988
1. Logged out, visit `/s/open-sauced/app`.
2. The repository page for the OpenSauced app repository loads.
Remove the feature flag from Posthog once this is deployed to production.

fix: removed repo-page feature flag from repos page and the project

---

components/Graphs/MetricCard.tsx
lib/hooks/api/useFetchMetricStats.ts

Fixes the "flippening" issue that @jpmcb reported.
Fixes #3073
**Before**
**After**
1. Visit https://deploy-preview-3091--oss-insights.netlify.app/s/kubernetes/kubernetes
2. Go to another browser tab
3. Come back to the tab that has https://deploy-preview-3091--oss-insights.netlify.app/s/kubernetes/kubernetes
4. The graphs no longer flip.

fix: fixed issue where stars metric chart was flipping horizontally

---

components/Graphs/MetricCard.tsx
pages/s/[org]/[repo]/index.tsx

Fixes an issues where the metric cards on the repository page were spilling out of their containers.
Fixes #3114
**Before**
**After**
1. Visit http://localhost:3000/s/kubernetes/kubernetes on a small screen.
2. Notice the metric cards no longer have their graphs bleed out.

fix: now repo page charts no longer bleed out of their container

---

.env
next.config.js
sentry.client.config.ts
sentry.edge.config.ts
sentry.server.config.ts

- Adjusts the Sentry configuration for edge and server configurations
- Increase sampling for edge and server configs
- Explicitly set `dsn` from environment variable

chore: adjust Sentry configuration and add explicit DSN

---

pages/s/[org]/[repo]/index.tsx

- Adds a fallback URL in case the repository URL is our data is empty
- Noticed an error when visiting https://app.opensauced.pizza/s/miurla/morphic
- We had repo data but the URL is empty

fix: add fallback for GitHub repository URL if none returned

---

e2e/pizza-new.spec.ts
middleware.ts

- Removes /hub/* pages from being handled by middleware
- These are handled by redirects instead
- Adds E2E test to verify behavior
1. Go to /hub/insights/new as a non-authenticated user
2. Note page is redirected to /workspaces/new

fix: remove /hub/* pages from middleware

---

pages/starsearch.tsx

Implements a basic input output for `/starsearch`, parsing a `ReadableStream` from the API endpoint `/star-search/stream` and displaying it to the UI with a typewriter effect. There are still some issues with parsing since some chunks are part of another word and there's no way we can determine that in the front end (for now). See video for example ("priorit ized" or "maintain ers").
https://github.com/open-sauced/app/assets/20603494/6f76a2c7-895b-4489-868c-8bf832704bb1
1. Log in as user under `star_search` feature flag.
2. Enter a prompt like `What is GitHub pull request used for?`
3. Ensure that the AI returns a response.

feat: basic implementation of StarSearch

---

components/shared/AppSidebar/InsightsPanel.tsx

Updates create new insight CTA link styles.
Fixes #3174
**Before**
**After**
2. Create a new workspace or go to a workspace without repository or contributor insights.
3. Notice the Create links look like links now.

fix: updated styles of create insights links in sidebar

---

components/shared/AppSidebar/AppSidebar.tsx

This PR removes a `console.info` call from the `mutateHandler` function in the AppSidebar component and a comment used to disable eslint's no console rule for the line that had such call. This PR also removes the argument "event" from `mutateHandler` as it was no longer being used after deleting the `console.info` call.
Fixes #3182

fix: remove console.info call from mutateHandler in AppSidebar component

---

pages/s/[org]/[repo]/index.tsx

Now, localhost is only used if `NEXT_PUBLIC_BASE_URL` isn't set for the repository page repo image.
Fixes #3180
Relates to #3117
1. Go to any repository page, e.g. https://deploy-preview-3179--oss-insights.netlify.app/s/open-sauced/app
2. Open the dev tools and expand the `<head>` section.
3. Notice the og:image and twitter:image have base URLs that are the deployment preview.

fix: now repo page OG images are corrext for production

---

lib/utils/contributor-utils.test.ts
lib/utils/contributor-utils.ts
next-types.d.ts

- Fixes sorting of most used languages in the contributors table. The languages for the React Core Team were showing languages incorrectly based on their recent contributions.
- Updates unit tests to reflect new logic
BEFORE:
AFTER:

fix: update logic for most used languages to match contributor profile

---

sentry.client.config.ts

- Lowers the sample rate for capturing replays when an error occurs on the client with Sentry
- Prevents us from going over the threshold for monitoring to quickly.

chore: adjust Sentry sample rate for replays on errors

---

pages/star-search/index.tsx

Now suggestion prompts in StarSearch run immediately.
Fixes #3241
**Before**
**After**
Note the double render is because of React strict mode during dev.
1. Go to `/star-search`
2. Click on a suggestion.
3. The suggestion populates the prompt input and StarSearch begins to respond immediately.

fix: now suggestion prompts run immediately

---

components/Workspaces/RepositoryStatCard.tsx
next-types.d.ts
pages/s/[org]/[repo]/index.tsx

Implements more devstats with `RepositoryStatCards` for PRs and issues in repo pages.
Closes #3165 
https://github.com/open-sauced/app/assets/20603494/6a14fe15-ea16-4168-ba2b-942ed3f80d36
1. Go to any repo page
2. See the new PR and Issue `RepositoryStatCards`
3. Set a different range to change the stats

feat: implement PR and issue devstats to repo pages

---

pages/star-search/index.tsx

Now StarSearch input is not covered by vertical suggestions on small screens
Relates to #3258
**Before**
**After**
1. Go to StarSearch, `/star-search`
2. Resize the screen or use a smaller device.
3. Notice the vertical suggestions no longer cover the prompt input.

fix: now StarSearch input is not covered by vertical suggestions on small screens

---

.github/workflows/playwright.yml
playwright.config.ts

This speeds up the app server running in end to end tests. `npm run dev` is fine for local development, but for CI, we want a production build which runs much more faster than a dev build.
Relates to #3017
N/A
N/A

test: speed up server for playwright tests on CI

---

components/Graphs/ContributorsChart.stories.tsx
components/Graphs/ContributorsChart.tsx
lib/hooks/api/useFetchMetricStats.ts
lib/utils/repo-page-utils.ts
pages/s/[org]/[repo]/index.tsx

Adds a new chart to repo pages that shows the number of contributors in a given range, as a bar graph showing the daily distribution and overview numbers for the total and average.
Closes #3293 
1. Go to repo pages and scroll down to see the Contributor chart card
2. Select different ranges to see change in numbers and graphs

feat: implement `ContributorsChart` for repo pages

---

pages/workspaces/[workspaceId]/index.tsx

- Returns a 404 when a workspace is requested with an invalid workspaceId
- Logs an error to Sentry
- Reduces the number of 500s thrown in the application

fix: return 404 on invalid workspace ID

---

pages/workspaces/[workspaceId]/contributor-insights/[listId]/activity.tsx
pages/workspaces/[workspaceId]/contributor-insights/[listId]/highlights.tsx
pages/workspaces/[workspaceId]/repository-insights/[insightId]/activity.tsx

- Fixes a bug where a workspaces has owners and viewers, which causes an error in `getServerSideProps` when `undefined` is returned in the owners array
1. Navigate to a workspace with an owner and viewer
2. Go to a contributor insight
3. Note the page loads correctly

fix: filter out undefined values for building workspace owners array

---

pages/s/[org]/[repo]/index.tsx

Now cached repository pages vary on the range query parameter. I've also added a cache tag for repository pages and individual repository pages if we ever need to purge them.
Note the actual page loads the correct data for the given day range. It's only OG images that were affected.
Relates to #3278
Fixes #3311
**Before**
30 day range
90 day range
**After**
30 day range
90 day range
1. Go to https://deploy-preview-3310--oss-insights.netlify.app/s/open-sauced/app
2. Open the dev tools and look at the OG image URL. It's for the 30 day range. `https://deploy-preview-3310--oss-insights.netlify.app/og-images/repository/open-sauced/app/30?description=%F0%9F%8D%95+The+path+to+your+next+contribution.`
3. Go to https://deploy-preview-3310--oss-insights.netlify.app/s/open-sauced/app?range=90
4. …

fix: now the page is cached varying on the day range

---

pages/star-search/index.tsx

This adds 2 things primarily to the star-search markdown rendering:
1. Empty `data:` frames are counted as newlines from the model. This is done by making the `\s` spacing capture in the regex optional _and_ not forcing a capture in the `results` capture-group via `.+`: instead, we allow for any captures (including zero) through `.*`.
2. When we get an empty string in the capture group, adds a "&nbsp; \n" which _seems_ to be the way to get react-markdown to render some newlines/spacing correctly. I may be wrong on this, but it seems to work _okay_.
This also changes `Markdown` --> `ReactMarkdown`. This seems to be the way the library recommends rendering "safe" markdown that can't have code injected into it: https://www.npmjs.com/package/react-markdown/v/8.0.6
I also noticed what seems to …

fix: Star-search md rendering renders spacing from LLM

---

pages/star-search/index.tsx
styles/globals.css

Adds some default styles for markdown renderer in StarSearch. It fixes headings and lists. @isabensusan, feel free to tweak my suggestions in globals.css.
Fixes #3337
**Before**
**After**
1. Ask Star-Search a question, e.g. "who is nickytonline and what has he written about recently?"
2. Inspect the HTML
3. See that the markdown was rendered and it has some base styling now (headings, lists)

fix: now markdown has common styles

---

components/TabList/tab-list.stories.tsx
components/TabList/tab-list.tsx

This PR introduces a sub-tabs list component.
Relates to #3322
You can view the component in Storybook at https://deploy-preview-3352--design-insights.netlify.app/?path=/docs/components-shared-subtabslist--docs

feat: implemented the substabs list component

---

components/molecules/HeaderLogo/header-logo.stories.tsx
components/molecules/HeaderLogo/header-logo.tsx
components/organisms/LoginTopNav/login-top-nav.tsx
components/organisms/TopNav/top-nav.tsx
components/organisms/Waitlist/waitlist.tsx
components/shared/AppSidebar/AppSidebar.tsx
pages/404.tsx
pages/500.tsx
pages/user/[username]/card.tsx

Now StarSearch remains visible on smaller screens in the top menu.
Fixes #3371 
**Before**
**After**
1. Go to any page and resize it to a small size.
2. Notice StarSearch remains in the menu.

fix: now StarSearch remains visible on smaller screens in the top menu

---

pages/star-search/index.tsx

Temporarily returning for `event: function_call` in readable stream from StarSearch until #3372.
Relates to #3372
**Before**
**After**
1. Ask StarSearch a question.
2. No `event: function_call` text appears

fix: temporarily returning for event: function_call in readable stream from StarSearch

---

sentry.client.config.ts

- Allows us to adjust the `replaysOnErrorSampleRate` through an environment variable on deploy

chore: make Sentry replaysOnErrorSampleRate configurable through env variable

---

components/Workspaces/WorkspaceWelcomeModal.tsx
components/shared/Drawer.tsx

Now on smaller screens a drawer instead of a modal when welcoming you to workspaces.
Fixes #3368
**Before**
**After**
_The smallest screen (width 320px) has the top cut off a bit, but I'm not going to worry about this right now. If someone is using that size device and reports it, I'll make adjustments._
1. Go to any workspace in the deploy preview on a smaller screen.
2. Notice a drawer component opens instead of a modal.

fix: now on smaller screens a drawer opens for welcome to workspaces

---

pages/star-search/index.tsx

Prompt response had widgets added to them in #3372. Prior to that the prompt response was always a string. Now we concatenate the responses as it may include widgets where we serialize the widget data.
Relates to #3405
N/A

fix: fixed TS error and logic for gathering prompt response

---

pages/star-search/index.tsx

Fixes an issue in the StarSearch UI where chatboxes were expanding outside the viewport on small screens when long words were present in the prompt response.
Fixes #3421
No screenshot atm but we debugged this together in our session @jpmcb @bdougie.
Hard to test at the moment but if you get a response

fix: fix to avoid StarSearch UI breaking when long words are outputted

---

components/StarSearch/StarSearchLoader.tsx
pages/star-search/index.tsx
tailwind.config.js

Now StarSearch has a loading animation before a response is streamed in.
Close #3203
**Before**
**After**
1. Go to StarSearch
2. Click on one of the canned prompts
3. Notice the three dots loader while an anwer is streamed in.

feat: added a loader for StarSearch responses

---

tailwind.config.js

Fixes a change made in #3422 where the usage of the `text-sauced-orange` or `bg-sauced-orange` defaulted to an opacity of 0. Now the default value is an opacity of 1.
Fixes #3436
**Before**
**After**
1. Go to a workspace page.
2. Notice

fix: now sauced-orange colour defaults to 1 for opacity

---

pages/star-search/index.tsx

Now the prompt/response area of StarSearch no longer scrolls when opening or closing the suggestions carousel (or drawer on smaller screens).
Fixes #3447
**Before**
**After**
1. Go to StarSearch, `/star-search`
2. Click on a suggested prompt.
3. A response is returned and scrolls to the bottom of the last response.
4. Scroll up in the prompt/response area.
5. Open the suggestions carousel (or drawer on smaller screens)
6. The prompt/response are no longer scrolls.

fix: now StarSearch prompt/response area no longer scrolls when opening/closing suggestions

---

pages/star-search/index.tsx

Now StarSearch widgets have a max width of 440px and are centered in the StarSearch response card.
Fixes #3452
**Before**
**After**
1. Go to StarSearch
2. Ask about the lotto factor for a project
3. Resize the screen and notice on larger screens the lotto factor widget is centered and no larger than 440px.

fix: now StarSearch widgets have a max width of 440px and are centered in the card

---

pages/star-search/index.tsx

Now in all screen sizes, suggestion boxes have uniform widths.
In the case of Safari they also have uniform heights when in grid view on larger screens.
Fixes #3470
**Before**
StarSearch suggestion promps do not have uniform widths.
Larger Screens
**Safari Only for grid view of suggestions**
**Smaller Screens**
**After**
StarSearch suggestion promps do not have uniform widths.
Larger Screens
**Safari Only for grid view of suggestions**
**Smaller Screens**
1. Go to `/star-search`
2. Resize the window to a medium breakpoint
3. Notice the suggestion boxes are stacked and uniform.
4. Do the same for a small screen where the drawer component opens.

fix: now StarSearch suggestion boxes have uniform widths

---

components/organisms/SearchDialog/search-dialog.tsx

Used ternary operator to switch between w-56 and w-64, did not use w-72 as the header logo gets very small when approaching sm breakpoint.
Fixes #3481
**Before**
**Non-macOS**
**macOS**
**After**
**Non-macOS**
**macOS**
1. Visit the main page from a mac machine.
2. Visit the main page from a windows machine.

fix: now search input is no longer squised on non-macOS devices

---

.github/CODEOWNERS

The triage team no longer exists, so it's been replaced with the engineering team in the CODEOWNERS file.
Closes #3490

chore: added replaced defunct triage team with engineering team in CODEOWNERS

---

components/Repositories/LotteryFactorChart.tsx

Implement a `!isLoading` check when trying to stop the error image from rendering when loading data.
Closes #3466

fix: `LotteryFactorChart` loading state overflow

---

lib/hooks/api/useContributorsByProject.ts

This fixes a change to the DTO in the API for the `v2/lists/{id}/stats/top-project-contributions-by-contributor` endpoint. We should use the `repos` string (which can take 1 repo name, or many)
1. Run API locally (with corresponding changes in the API)
2. Run app locally
3. go to a user list
4. User list works as expected
(note: `useContributorsByProject` doesn't actually look to be used anywhere so this is more or less a no-op change)

fix: Use the "repos" query param in top-project-contributions-by-contributor

---

pages/star-search/index.tsx

Added a `useMemo` to set the user ID based on the session. This fixes the issue where it doesn't render any image if the user starts logged out in the StarSearch page then logs in when prompted.
Closes #3523 
https://github.com/open-sauced/app/assets/20603494/dffdf510-951e-4f78-a045-0161fe8893d9

fix: set `/star-search` user avatar after logging in

---

pages/workspaces/[workspaceId]/contributor-insights/[listId]/activity.tsx

- Fixes an intermittent issue where the list id was not found, causing an error to be reported in Sentry
Resolves: https://opensauced.sentry.io/share/issue/169c46dcdb714d6ca6ad70882e4c5838/

fix: check for valid list id and redirect if invalid

---

components/Repositories/ContributorConfidenceChart.tsx

Fixes the alignment of gauge and percentage text for the contributor confidence chart.
Relates to #3558
**Before**
**After**

fix: fixed contributor confidence percentage text alignment

---

e2e/star-search.spec.ts

Fixes a failing test. The URL for the shared prompt is now a dub.co short link.
From @brandonroberts: Its probably because Dub was getting to the free account limit (25 links), then it stops creating short links. If it fails, it just returns the copied URL. I nuked a bunch of the old ones, and now it doesn't create duplicates anymore.
Relates to #3325

test: fixed failing test for StarSearch share prompt

---

components/StarSearch/StarSearchChat.tsx
e2e/star-search.spec.ts

Now StarSearch chat creation and subsequents question during the same sessions are persisted to a thread. This work is a precursor to #3527 and part of the work in #3551.
Note: Prompt sharing will not work in beta for a short period of time. I will be getting this sorted out in the rest of the work for #3551 in #3563.
Relates to #3551
Relates to #3563
1. Start a StarSearch conversation via a canned suggestion or your own prompt.
2. Things behave like they did before including loading widgets if you ask about the lotto factor.

feat: now StarSearch uses the new StarSearch API endpoints for chat creation/updates

---

lib/hooks/search-users.ts

- Updates the user search utility function to search the GitHub API under separate conditions
- Our primary API fails
- Our primary API returns 0 results
- If the GitHub API fails then we return `false` which indicates no results were found in either. 
1. Go to deploy preview
2. Open the network panel in browser devtools
3. Search for a user that's not in our data
4. See two requests made, one to our API, and one to the GitHub api
5. See results from the searches

fix: update user search to fallback to GitHub API on error and zero results

---

components/StarSearch/ShareChatMenu.tsx
components/StarSearch/StarSearchChat.tsx
e2e/star-search.spec.ts
lib/hooks/api/useGetStarSearchThreadHistory.ts
lib/utils/star-search-utils.ts
lib/validation-schemas.ts
netlify/edge-functions/deno.json
netlify/edge-functions/star-search.tsx
next-types.d.ts
npm-shrinkwrap.json
package.json
pages/star-search/index.tsx

Now you can share an existing thread (conversation in StarSearch). We had a rudimentary version of this previously (see #3324), but it was just sharing the prompt and running it.
These shared conversations are the full conversation that gets replayed and does not hit our AI backend at all.
If you are not logged in, you will only be able to replay it once (unless the page is refreshed in the browser) and any other actions will require you to log in.
One thing to note is if you generate a shared URL, it will generate for beta.app.opensauced.pizza on beta and deploy previews, and one in prod, will be prod links. All that said, you'll just need to replace the beta base URL with the deployment preview URL.
TODO:
- fix flash of content when loading a conversation
~- fix OG image for a shareable …

feat: enabled loading an existing conversation in StarSearch

---

components/StarSearch/StarSearchChat.tsx

Fixes an issue where StarSearch might not have updated the thread title with a summary of the initial StarSearch conversation.
Note that StarSearch will eventually update the title of the thread with the summary. This is a fix in the event that someone shares before that's happened.
Relatest to #3563
**Before**
**After**

fix: now the title of a thread is set to the initial prompt of a StarSearch conversation

---

components/StarSearch/StarSearchCompactHeader.tsx

Now the StarSearch logo is no longer cutt off slightly when StarSearch is embedded somewhere, e.g. a workspace page.
Fixes #3629
**Before**
**After**
1. Go to a workspace page.
2. Click on the StarSearch button at the bottom right.
3. StarSearch opens.
4. Notice the logo is no longer cut off slightly.
5.

fix: now StarSearch compact header no longer cuts off StarSearch logo

---

components/StarSearch/StarSearchWidget.tsx

Now on pages that embed StarSearch, e.g. workspaces, the Lotto Factor widget, or any other future widget will no longer be squished.
Fixes #3625
**Before**
**After**
1. Go to any workspace
2. Open StarSearch by pressing the StarSearch button at the bottom right of the screen.
3. Ask the questions, "What is the lottery factor of some-org/some-repo?"
4. Notice the lottery factor chart is not squished.
5. Go to `/star-search` and ask the same question.
6. The lottery chart should look as it did before (max of 440px wide).

fix: now widgets in StarSearch look good width wise when embedded

---

components/StarSearch/Widgets/LotteryFactorWidget.tsx

Now there is a header that is a link above lottery factor widgets in StarSearch so they can be distinguished from one another when more than one repository lottery factor widget is rendered in StarSearch.
Closes #3631
**Before**
**After**
1. Go to a workspace with multiple tracked repositories.
2. Ask the stock question, "Are there any repositories that have a very high lottery factor?"
3. It's non-deterministic, but more often than not, you will get multiple lottery factor widgets returned.

feat: added the repo name as a link above the lottery factor chart

---

components/molecules/ListCard/list-card.tsx
lib/hooks/api/useContributorList.ts
lib/hooks/useFetchAllListContributors.ts
lib/hooks/useList.ts
next-types.d.ts
pages/workspaces/[workspaceId]/contributor-insights/[listId]/edit.tsx
pages/workspaces/[workspaceId]/contributor-insights/[listId]/overview.tsx

Uses `v2/workspaces/:workspace-id/userLists/:list-id/contributors` endpoint in favor of the deprecated `v2/lists/:id/contributors` endpoint in the API
Related to #3627 
1. Run API locally
2. Run app locally
3. Go to a workspace user list - list is populated correctly

feat: Remove deprecated v2/lists/:id/contributors endpoint

---

components/StarSearch/ShareChatMenu.tsx
components/StarSearch/StarSearchChat.tsx

Now the StarSearch conversation share link button has a loading state so that it does not appear broken when generating a shareable link to a conversation.
Fixes #3615
**Before**
**After**
1. Create a StarSearch conversation from `/star-search`
2. Once the conversation completes, open the share menu just below the last message in the conversation.
3. Click Create share link.
4. Notice there is a loading state before the shareable link and CTAs to share to socials appear.

feat: now StarSearch conversation share link button has a loading state

---

components/StarSearch/StarSearchChat.tsx

Now `isRunning` is reset to `false` when starting a new conversation. This was preventing the stream conversation from beginning when a previous one was cancelled and a new conversation started.
Fixes #3636
**Before**
**After**
1. Go to any workspace and open StarSearch
2. Start a conversation
3. Cancel it by clicking the back button or new conversation buttons in the compact StarSearch header.
4. Start the new conversation.
5. Notice the new conversation streams in.

fix: now a new StarSearch chat can be started if one was in progress

---

components/Contributors/OscrPill.tsx
components/molecules/ContributorListTableRow/contributor-list-table-row.tsx

Now OSCR that are 0 or less are rendered as a dash in the contributors table and on mobile, it is not rendered at all.
Fixes #3661
**Before**
**After**
1. Go to any workspace that has a contributor insight
2. A little tricky to test potentially, but try and add someone who has an OSCR of zero.
3. Notice the rows with OSCR at 0 render a dash in the contributors table and on mobile, it's not rendered at all.

fix: now OSCR that is 0 gets rendered as a dash

---

components/Workspaces/WorkspaceHeader.tsx
pages/workspaces/[workspaceId]/activity.tsx
pages/workspaces/[workspaceId]/index.tsx
pages/workspaces/[workspaceId]/issues.tsx

Fixes some mobile/small screen issues for workspace pages. Note that on some of the activity pages, the StarSearch button is hidden. Since that is currently feature flagged, I'll look into that in a separate PR.
Also note, that for the repository page, I made one notable change. I moved the Add Repositories button with the Share and Edit buttons.
Prior to this PR, it was down below with the filters. This was part of the mobile fix and it looks much better. Also, the share and edit buttons weren't justified to the right. I fixed that as well.
Fixes #3667
**Before**
Repository Page
Activity page (PRs)
Activity page (Issues)
**After**
Repository Page
Activity page (PRs)
Activity page (Issues)
1. Visit any workspace from the deploy preview on your phone
2. Notice the workspace repository page …

fix: now workspace pages on smaller screens keep their layout in bounds

---

components/shared/AppSidebar/sidebar-menu-item.tsx

Now top level app sidebar menu items have the same font weight.
Fixes #3689
Before and then After (subtle)
1. Open any page with the sidebar logged in.
2. Notice the font weights are the same.
3. Wait for @brandonroberts to post this animated GIF in his approval comment.

fix: now app sidebar menu items have the same font weight

---

components/Workspaces/TrackedRepoWizard/TrackedRepoWizardLayout.tsx
components/Workspaces/TrackedReposTable.tsx
components/atoms/Toast/toast.tsx
components/molecules/InsightHeader/insight-header.tsx
components/organisms/Contributors/contributors.tsx

Now the repository insights pages look good on smaller screens. Note that the Add Repositories wizard modal is still not responsive. It will be addressed in a separate PR as the wizard modal is used in a for contributor insights as well as tracked repositories for a workspace.
Fixes #3669
**Before**
**After**
1. Go to a repository insight page from any workspace on your phone
2. Notice the dashboard, contributors and activity pages when navigated to, all look good on mobile.
3. Edit or create a new repository insight.
4. Notice it looks good on smaller screens.

fix: now the repository insights pages header looks good on smaller screens

---

pages/u/[username]/index.tsx

Adds 60 second caching ā la stale while revalidate for user profile pages. On average for beta/this deploy preview, there is almost a 1.5 second speed improvement for user profile pages.
**Beta (before)**
```
❯ oha --no-tui https://beta.app.opensauced.pizza/u/nickytonline
Summary:
Success rate: 100.00%
Total:        14.4306 secs
Slowest:      11.0254 secs
Fastest:      0.5943 secs
Average:      3.4496 secs
Requests/sec: 13.8594
Total data:   879.30 KiB
Size/request: 4.40 KiB
Size/sec:     60.93 KiB
Response time histogram:
0.594 [1]   |
1.637 [124] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
2.681 [15]  |■■■
3.724 [6]   |■
4.767 [4]   |■
5.810 [0]   |
6.853 [1]   |
7.896 [9]   |■■
8.939 [3]   |
9.982 [9]   |■■
11.025 [28]  |■■■■■■■
Response time distribution:
10.00% in 0.9719 secs
25.00% in 1.1526 …
```

feat: now userprofile pages are cached for 60 seconds

---

components/organisms/TopNav/top-nav.tsx

With improvements made in #3692, I had added an unnecessary overflow hidden on the top nav. This PR removes it.
Relates to #3692
**Before**
**After**

fix: now user menu opens in the top nav

---

components/StarSearch/StarSearchChat.tsx
components/StarSearch/StarSearchEmbed.tsx
lib/hooks/useStarSearchFeedback.ts

Adds analytics to see when a user clicks on the StarSearch for workspaces CTA (logged in, logged out, no access) as well as the prompts and response via feedback like standalone StarSearch.
Closes #3747
Logged out
1. Open your dev tools
1. Go to a workspace
1. Click the StarSearch for workspaces CTA in the bottom right.
1. Notice the posthog analytic generated for the `star_search_workspace_cta_click` event with a property called `type` with the value `sign_in`.
Logged in
1. Open your dev tools
1. Go to a workspace
1. Click the StarSearch for workspaces CTA in the bottom right.
1. Notice the posthog analytic generated for the `star_search_workspace_cta_click` event
1. If you're an editor of the workspace, the even's property called `type` with the value `can_access`. If you're not an …

feat: added posthog analytics for StarSearch for Workspaces

---

components/StarSearch/StarSearchChat.tsx
components/StarSearch/StarSearchEmbed.tsx

Now StarSearch for Workspaces resets when changing workspaces. You could still use StarSearch in the new workspace, but it was confusing to see the previous workspace's StarSearch conversation.
Fixes #3755
**Before**
https://github.com/user-attachments/assets/2b97e377-dc0e-4c9a-9326-6daa966d1e42
**After**
https://github.com/user-attachments/assets/ee5850f3-e016-4741-95cb-abf2379b2230
1. Go to any workspace where you have access to StarSearch
2. Ask a question
3. Switch to another workspace (it can be in the middle of running the current prompt/response stream)
4. Notice that StarSearch for workspaces resets to the initial screen.

fix: now StarSearch for Workspaces resets when changing workspaces

---

lib/hooks/api/useGetStarSearchWorkspaceHistory.ts

Now when you switch workspaces, StarSearch history reloads with the current workspace StarSearch history instead of concatenating or staying on the previous workspace's StarSEarch history.
Closes #3776
1. Go to a workspace and open it's StarSearch history.
2. Note some of the StarSearch history items.
3. Switch to another workspace.
4. Open the StarSearch history.
5. Notice the history is different.

fix: now StarSearch history resets if workspace changes

---

components/StarSearch/StarSearchEmbed.tsx
components/Workspaces/WorkspaceIssuesTable.tsx
components/Workspaces/WorkspacePullRequestsTable.tsx
styles/globals.css

Now hover cards appear over the StarSearch for Workspaces panel and are no longer hidden.
Fixes #3773
**Before**
**After**
1. Test this on the two activity pages of workspaces: pull request and issue pages.
2. Ask StarSearch for workspaces a question about contributors.
3. It should return a response with user links that have the hover avatar beside them.
4. Hover over the avatar.
5. Notice the hover card is on top of everything else.

fix: now pinned table columns only get pinned when embedded StarSearch is closed

---

components/molecules/NewsletterForm/newsletter-form.tsx
components/molecules/TeamMembersConfig/team-members-config.tsx
components/organisms/UserSettingsPage/user-settings-page.tsx
lib/utils/validate-email.test.ts
lib/utils/validate-email.ts

This upgrades the valid email regex to the more agnostic HTML5 regex used in webpack. This is a relatively simple email validation regex and _mostly_ looks for a valid `@` preceded by valid email text and followed by a valid address / domain.
_Technically_ only the email provider can actually validate an email. But this at least fixes issues we're having with domains that are valid (like `.me` or `.co`)
Thanks to @Idrinth for the original PR (attribution included in co-author)
Closes: https://github.com/open-sauced/app/issues/3795
Closes: https://github.com/open-sauced/app/issues/3271
Closes: https://github.com/open-sauced/app/pull/3273
Works with `nick@nickyt.co`:
1. Run app
2. Use email form in Highlights
3. Use email form in personal profile

fix: Upgrades email validation regex to the more agnostic HTML5 regex

---

components/Contributors/OscrPill.stories.tsx
components/Contributors/OscrPill.tsx
e2e/workspace-contributor-insight.spec.ts

Now the OSCR component has a CTA to log in if logged out/are a guest,
Closes #3810
Relates to #3802
1. Ensure you're logged out
2. Go to a page that has the OSCR in a grid, e.g. https://deploy-preview-3814--oss-insights.netlify.app/workspaces/3432aaf7-55db-4c2b-9fde-f61604471e21/contributor-insights/aaf5ec66-9d3a-456d-b62b-05410e0b2fa4/overview
3. Tab to a blurred OSCR or hover over it.
4. The tooltip says to login to view the OSCR
5. Click on the blurred score.
6. You're logged in and now the scores are visible.

feat: now OSCR component has a CTA to log in if logged out

---

playwright.config.ts

Increases the number of workers in the Playwright GitHub action to three which should shorten the amount of time for E2E tests to run.
Closes #3815
N/A

chore: set the number of workers to 3 for Playwright GitHub action

---

components/Contributors/Oscr.tsx
e2e/user-profile.spec.ts
e2e/workspace-contributor-insight.spec.ts

Adds the same lock button to the OSCR pill component that the OSCR component on the user profile has.
Relates to #3814
**Before**
**After**
1. Ensure you're logged out.
2. Go to https://deploy-preview-3823--oss-insights.netlify.app/workspaces/3432aaf7-55db-4c2b-9fde-f61604471e21/contributor-insights/aaf5ec66-9d3a-456d-b62b-05410e0b2fa4/overview
3. Notice the lock button over the OSCR ratings.
4. Click on one of the lock buttons.
5. You're logged in an see OSCR ratings now.

fix: updated OSCR login CTA for OSCR pill component

---

components/Contributors/Oscr.tsx

Makes the OSCR math us `math.ceil` for ceiling math. This depends on: https://github.com/open-sauced/api/pull/990 which sets the OSCRs in the API from 0-300 (instead of straight percentages like 0.83)
Depends on: https://github.com/open-sauced/api/pull/990
1. Run app with API running locally or pointed to beta
2. Go to a user's profile, see OSCR is between 0-300

feat: OSCR works with API range 0-300 and uses ceiling math

---

lib/utils/query-params.ts

Now by default, if you use `setQueryParams` to added querystring parameters to the URL, the page no longer jumps. If for some reason you need it to scroll to the top, pass in `true` for `scroll`.
Closes #3836
**Before**
**After**
1. Go to a user profile, e.g. `/u/nickytonline`
2. Resize the window so it scrolls down a bit.
3. Click on one of the tabs, e.g. Recommendations.
4. The page refreshes and no longer scrolls to the top.

fix: now using setQueryParams no longer causes page to jump

---

components/molecules/InsightHeader/insight-header.tsx
pages/workspaces/[workspaceId]/repository-insights/[insightId]/edit.tsx

- User can click the 'Edit' button to go to settings
- previously shows the Upgrade Modal
- Show banner on `/edit` page
Closes #3875

fix: repository insight limited features

---

components/atoms/FilterCard/filterCard.stories.tsx

Small cleanup of hanging hacktoberfest references. This was just a story so replaced with a different filter label in the explore feed.
Closes: https://github.com/open-sauced/app/issues/2514#issuecomment-2270017555
No other hacktoberfest references found (besides the automated changelog):
```
❯ rg -i -l hacktoberfest
CHANGELOG.md
```

chore: Small cleanup of hanging "Hacktoberfest" references

---

components/atoms/LayoutToggle/layout-toggle.tsx
e2e/explore-page.spec.ts

Now the grid layout toggle options are radio buttons. I also added some E2E tests for this.
Fixes #3887
**Before**
**After**
1. Go to any page with the layout toggle, e.g. `/explore/topic/typescript/contributors/filter/recent?range=30`
2. Use the tab key on the page to tab to the focusable elements on the page. Notice each layout option receives focus now.

fix: now layout toggles are radio buttons

---

components/organisms/ContributorCard/contributor-card.tsx
components/organisms/Contributors/contributors.tsx

This PR excludes the OSCR score from the contributor card where the data being rendered does not include OSCR. Currently that is workspace repository insight contributor grids, and the explore page contributor grid.
OSCR will land in those two places with the new TanStack table component in the future. See https://github.com/open-sauced/app/issues/3819 
Relates to #3883
1. Visit a workspace repository insight contributor page
2. Notice the grid does not include the OSCR scores.
3. Visit the explore contributor page.
4. Notice the grid does not include the OSCR scores.

fix: excluded OSCR from old contributor card list component

---

components/molecules/NewsletterForm/newsletter-form.stories.tsx
components/molecules/NewsletterForm/newsletter-form.tsx
pages/feed/index.tsx

Removes the usage of `NewsletterForm` in favor of `NewsletterLink` which is just a sole button that shims to our ghost.io newsletter subscribe page.
~Closes: https://github.com/open-sauced/app/issues/3796~ Quickfix for: https://github.com/open-sauced/app/issues/3796
1. Run app locally
2. Go to localhost:3000/feed
3. Click the "Subscribe" button.
4. See Ghost.io subscribe page open in new tab

fix: Removes NewsletterForm usage in favor of sole link to newsletter

---

.github/workflows/compliance.yml
.github/workflows/development.yml
.github/workflows/playwright.yml

These triggers are associated with enabling the merge queue for this repository.
[From the docs:](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)
> If your repository uses GitHub Actions to perform required checks on pull requests in your repository, you need to update the workflows to include the merge_group event as an additional trigger. Otherwise, status checks will not be triggered when you add a pull request to a merge queue. 
N/a - in an attempt to fix the constant back and forth of back merging beta branches

chore: Requires the merge queue trigger for enabling merge queue checks

---

.github/workflows/compliance.yml

Removes the merge queue group from the compliance check: this is PR specific and really only should be able to run on the `pull_request` trigger
Followup to #3906

chore: Remove merge queue group for compliance checks

---

components/molecules/ListCard/list-card.tsx

Now the contributor insight card orange dot no longer gets squished.
Fixes #3896
**Before**
**After**
1. Go to a contributor insight list, e.g. https://deploy-preview-3912--oss-insights.netlify.app/workspaces/21c5e583-f1fd-4033-9ec9-7801f67ff727/contributor-insights
2. Resize the browser window to shrink it.
3. Notice the orange dot no longer gets squished.

fix: contributor insight card orange dot no longer squished

---

components/Contributors/Oscr.tsx
components/Tables/ContributorsTable.tsx
components/atoms/Tooltip/tooltip.tsx
components/organisms/ContributorProfileTab/contributor-profile-tab.tsx

Adds a link to the OSCR docs in OSCR info tooltips.
Closes #3920
**Before**
**After**
Note that the after screenshot is using our standard tooltip making it uniform with our other tootips.

feat: added a link to OSCR tooltips pointing to the OSCR docs

---

components/Contributors/Oscr.tsx

Fixes PostHog integration to capture the `OscrButton`'s location (pathname) when clicked by a user to log in.
Fixes #3926
1. Go to anywhere `OscrButton` is used (eg `/u/<username>`)
2. Click the button when logged out
3. Go to PostHog and look for the `OSCR Login Button Clicked` events
4. Ensure the `pathname` is not returned as NULL in the event's properties

fix: capture pathname for `OscrButton` when clicked

---

components/molecules/DevCard/dev-card.tsx

Te dev card back and front no longer overlap when flipped on Safari and Firefox
Fixes #3927
**Safari**
**Firefox**
**Chromium**
After
**Safari**
**Firefox**
**Chromium**
I also fixed an issue where the card would get text or images selected within the card.
**Before**
**After**
Test the following in a Chromium based browser, Firefox and Safari.
1. Navigate to a dev card page for a user, e.g. https://deploy-preview-3931--oss-insights.netlify.app/u/nickytonline/card
2. Flip the card using the mouse or touch if on mobile.
3. Notice the dev card back and front no longer overlap when flipped

fix: now the back of the dev card no longer peers through when flipped on Safari and Firefox

---

lib/validation-schemas.ts
pages/u/[username]/card.tsx

Implements a server side check that validates a user with the username in the URL exists, otherwise throws a 404 not found.
Closes #3930 
1. Go to a DevCard page for a non-existent user (eg `/user/zeucapua2/card`)
2. Ensure you are given a 404 page.

fix: validate user exists for `/user/<username>/card` page

---

components/Repositories/AddToWorkspaceDrawer.tsx
components/Repositories/AddToWorkspaceModal.tsx
components/Workspaces/TrackedReposTable.tsx
e2e/repo-page.spec.ts
pages/s/[org]/[repo]/index.tsx
pages/workspaces/new.tsx

Now you can generate a workspace via a repository page based on the repository's [software bill of materials](https://github.blog/enterprise-software/governance-and-compliance/introducing-self-service-sboms/) (SBOM).
Analytics also get sent to PostHog when someone clicks the <kbd>Workspace from SBOM</kbd> button.
Note that @jpmcb is working on SBOM for Go, but that does not block this PR. Once his stuff lands, it'll no longer report that a Go project isn't supported.
Until we have documentation, I'm linking directly to the https://www.cisa.gov/sbom page in the SBOM button tooltip.
Closes #3842
Relates to https://github.com/open-sauced/api/issues/1027
The buttons are different colours now as mentioned in the comments below. Dropping a screenshot here as the video isn't up to date. …

feat: now workspace can be generated from repo page via SBOM

---

pages/feed/index.tsx

Now when logged in, the "See it now" link on the feed page goes to the user's dev card.
Fixes #3952
1. Go to the feed page logged in, `/feed`.
2. Click on the See it now link in the OSCR panel.
3. You're redirected to your dev card page.

fix: now see it now link on feed when logged in goes to the user's dev card

---

lib/utils/copy-to-clipboard.test.ts
lib/utils/copy-to-clipboard.ts
npm-shrinkwrap.json
package.json

This PR implements utility function to copy an HTML element as an image to the clipboard.
Closes #3962
N/A
N/A (not used in the app yet and has unit tests)

feat: implemented utility function to copy an HTML element as an image to the clipboard

---

components/shared/CopyContainer.stories.tsx
components/shared/CopyContainer.tsx
lib/utils/copy-to-clipboard.ts
pages/s/[org]/[repo]/index.tsx

This PR introduces a new component called `<CopyContainer />`. Anything you wrap with this component will be able to be copied as an image (in theory 😅). It's a wrapper component to copy the contents (children) as an image.
If you're curious about the options prop, it's the [same settings at the html2canvas configuration](https://html2canvas.hertzen.com/configuration).
Closes #3974
Relates to #3966
N/A (see the Storybook as it's not used in the codebase yet)

feat: implement the CopyContainer component for copying it's contents as an image

---

components/organisms/UserSettingsPage/user-settings-page.tsx
pages/start.tsx

Makes timezone selection optional when onboarding or updating user settings
Closes #3971

fix: make timezone optional for onboarding and user settings

---

e2e/repo-page.spec.ts
e2e/user-profile.spec.ts
e2e/workspace-contributor-insight.spec.ts
pages/s/[org]/[repo]/index.tsx
playwright.config.ts

- First pass at improving stability of E2E tests
- Removes checks for URLs for external services
- Fixes a hydration issue on repo pages for small screens
- Increases the timeout for local/CI runs
Closes #3946 
Closes #3557

ci: improve stability of E2E tests

---

components/atoms/Select/single-select.tsx

Fixes #3673
This pull request fixes the issue where a long title would overflow from the side drawer. Now, the PR includes truncated labels for long titles, with the full label shown in a tooltip upon hovering. 
This PR fixes issue #3673
[screen-capture (21).webm](https://github.com/user-attachments/assets/daba5015-5958-4acc-ac41-9cf5a0ec9952)
Test cases were not added as I didn't find the corresponding test file for this component. Should I write it from scratch?
1. Go to workspace
2. Create new workspace with a long name
3. See the truncated title and tooltip upon hovering

fix: add tooltip for long titles

---

components/molecules/ContributorListTableRow/contributor-list-table-row.stories.tsx
components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
components/organisms/ContributorCard/contributor-card.stories.tsx
components/organisms/ContributorCard/contributor-card.tsx
components/organisms/ContributorProfilePage/contributor-profile-page.tsx
components/organisms/Contributors/contributors.tsx
components/organisms/ContributorsList/contributors-list.tsx
components/organisms/ContributorsTable/contributors-table.tsx
components/organisms/Dashboard/dashboard.tsx
lib/hooks/api/useContributors.ts
next-types.d.ts
pages/workspaces/[workspaceId]/contributors.tsx

Followup to: https://github.com/open-sauced/api/pull/1039
> [!WARNING]
> Note: this should go in alongside the above API change. The API for `v2/contributor/search` will be returning `DbUser` (which includes the OSCR) now
Related to work in: https://github.com/open-sauced/app/issues/3859 - cc @zeucapua this is relevant to what you're working on with the OSCR in contributor search
Things look good!
1. Run API locally (or wait for the API changes to land on beta)
2. Run App locally
3. Inspect workspaces table, contributor cards, and repo pages contributors still all work

chore: Use DbUser for /contributor/search endpoint

---

components/shared/CopyContainer.tsx
pages/s/[org]/[repo]/index.tsx

Wraps the `OssfChart` component with `CopyContainer` to allow users to copy it as an image with a branding bar on top. The button will not show if the OSSF score is still be calculated.
Closes #3961 
1. Go to a repository page
2. If its score is still being calculated, ensure the copy button doesn't show
3. If the score is available, copy the chart by clicking the button
4. Paste the image on a text box that'll render it (eg GitHub markdown, Twitter post, etc.)

feat: copy OSSF Scorecard as image

---

lib/utils/copy-to-clipboard.ts

Now html2canvas-pro is dynamically imported only when needed and then cached, saving about a 45kb of JS loading on any page that uses it on initial page load.
Closes #4033
1. Go to a repository page, e.g. https://deploy-preview-3966--oss-insights.netlify.app/s/kubernetes/kubernetes
2. Hover over the Contributor Confidence card.
3. Notice the copy button appears in the top right corner.
4. Click it.
5. A toast message says the image was copied.
6. Paste the image in for example GitHub markdown, socials, Slack etc.
7. The image of the given stat/graph appears.

feat: now html2canvas-pro is dynamically imported only when needed and then cached

---

pages/u/[username]/index.tsx

Now if loading user data fails on a user profile page, an error is thrown instead of 404ing as it's misleading if an existing user is said to not be found.
Fixes #4042
Kind of hard to test this atm. The API can 404 if a user isn't found, but then it goes to the stub a user and if that fails it gives a 400.
1. Go to a valid user profile, e.g. /u/brandonroberts
2. Page loads
3. Go to an invalid user profile, e.g. /u/brandonroberts____
4. It doesn't 404, it throws a 400

fix: now if loading user profile fails an error is thrown instead of 404ing

---

components/organisms/SearchDialog/search-dialog.tsx

Now search dialog is always on top of other elements. I'm just going to adjust the overlay to the color it was originally (more white).
Fixes #3614
**Before**
**After**
1. Go to a repository page, e.g. /s/kubernetes/kubernetes
2. Open the search dialog. Notice the logo as well as other graphs no longer bleed through the search bar or the overlay.

fix: now search dialog is always on top of other elements

---

components/organisms/SearchDialog/search-dialog.tsx

This reverts commit 3b4101a30927ac1fbd8ee83180e66cf7a566ca78. Testing in the emulator on mobile seemed fine, but I was testing on my actual phone this morning and there are issues with the fix. This reverts the changes in #4047. I will reopen the issue.
Relates to #3614

fix: Revert "fix: now search dialog is always on top of other elements (#4047)"

---

components/Repositories/OssfChart.tsx

fix #4055 
This PR fixes Bug #4055: Removed the z-index from the OssfChart component's "I want this now!" button JSX and moved the JSX below the ResponsiveContainer component. This achieves the desired effect of the component without any odd z-index behavior.
Fixes #4055 
N/A
No tests written. Look at code on lines 142 - 148 of [OssfChart.tsx](https://github.com/ryandotfurrer/open-sauced_app/blob/bug-fix_remove-unnecessary-z-index-openssf-score-card/components/Repositories/OssfChart.tsx) to see the changed code.

fix(ossfchart.tsx): remove z-index and move "I want this now!" button JSX below ResponsiveContainer

---

.github/workflows/development.yml
.github/workflows/issue.yml
.github/workflows/playwright.yml
.github/workflows/release.yml
.github/workflows/storybook.yml
.github/workflows/triage.yml

Uses GitHub action self hosted runners. These are _slightly_ more powerful runners that should hopefully make it so actions are less painful and the e2e tests don't flake as much.
Related to: #3946

feat: Use self hosted GitHub actions runners

---

.github/workflows/development.yml
.github/workflows/issue.yml
.github/workflows/playwright.yml
.github/workflows/release.yml
.github/workflows/storybook.yml
.github/workflows/triage.yml

- Uses the correct `runs-on` key / value in each action
- Uses the NPM setup action cache for caching dependencies: https://github.com/actions/setup-node?tab=readme-ov-file#caching-global-packages-data
Fast follow to: #4069

fix: Use correct github action yamls

---

components/Workspaces/WorkspaceLayout.tsx
components/atoms/Select/single-select.tsx
components/shared/SplitButton.tsx
e2e/repo-page.spec.ts
pages/s/[org]/[repo]/index.tsx

Implements the `SplitButton` component to combine the 'Add to Workspace' and 'Create Workspace from SBOM' buttons on desktop. Adds a new optional 'icon' prop to `SplitButton`. 
Note: this is only for the desktop view. On mobile we are using the `Drawer` component which requires its own trigger button, so it can't be separated to an external trigger.
Closes #3942 
https://github.com/user-attachments/assets/2db7c732-d72a-48de-8eb7-76414b81734e

feat: use `SplitButton` for repo page Add Workspace buttons

---

.github/workflows/release.yml

Upgrades the upload / download artifact job.
Fixes #4093

chore: updated upload-artifact & download-artifact actions to v4

---

.github/workflows/release.yml

Now hidden files are included in production artifacts because the build output of Next.js is the `.next` folder. This wasn't an issue prior to `actions/upload-artifact@v4`.
Closes #4096
N/A

chore: now hidden files are included in production artifacts

---

components/molecules/DevCard/dev-card.tsx

This PR addresses the bug where a long username in a developer card causes the OSCR score to overflow and pop out of the card's boundary while also address related to it.
- resolve Hydaration error in Devcard component by using useEffect and useState for props.isLoading.
- fix styling in front view of card by limiting its width,text-center and wrapping
- fix styling in back view of card by truncate tailwind utility
- increase font size of oscr  limit  from 0.5 rem to 0.7rem to make it visible
closes #3981

fix: Prevent OSCR score from popping out of dev card with long usernames

---

next.config.js

- Adds redirects to the new explore page from the topic-based pages
Closes #4111 
1. Go to /explore/topic/typescript
2. Go to /typescript
3. Go to /typescript/dashboard
4. Note all should redirect to `/explore`

fix: redirect all explore requests to the new explore page

---

netlify.toml

Now hot.opensauced.pizza/* links redirects to app.opensauced.pizza/explore. Once this is deployed to production, we can change whhich app hot.opensauced.pizza points to in the Netlify dashboard.
Closes #4142
1. This can't be tested until the redirect in this PR is in production.

chore: now hot.opensauced.pizza/* redirects to app.opensauced.pizza/explore

---

components/Tables/ContributorsTable.tsx

Implement a `SplitButton` in the `ContributorsTable` to allow the user to download the data as either JSON or CSV file.
**JSON Output**
```json
{
"brandonroberts": {
"commits": 13,
"prs_created": 6,
"prs_reviewed": 21,
"issues_created": 1,
"commit_comments": 0,
"total_contributions": 41,
"login": "brandonroberts",
"oscr": 271.125,
"company": "@open-sauced",
"location": "Alabama"
},
"nickytonline": {
"commits": 14,
"prs_created": 9,
"prs_reviewed": 30,
"issues_created": 12,
"commit_comments": 0,
"total_contributions": 65,
"login": "nickytonline",
"oscr": 250.98387096774195,
"company": "@open-sauced",
"location": "Montreal, Canada"
},
"jpmcb": {
"commits": 0,
"prs_created": 0,
"prs_reviewed": 12,
"issues_created": 0,
"commit_comments": 0,
"total_contributions": 12,
"login": "jpmcb",
"oscr": …
```

feat: download `ContributorsTable` data as JSON/CSV

---

netlify.toml
public/downtime.html

A temporary downtime page as we do our database migration. It'll get merged to a pretty much empty branch, `downtime`, and we will deploy this branch first to beta to test by pointing the to the `downtime` branch in the Netlify UI, and then prod just before we begin the database migration.
**Once the database migration is complete in production, we'll change the branch production is pointing to in the Netlify UI, and we'll redeploy or rollback to the previous production release.**
Relates to #4156.
To test, navigate to any page and it redirects to `/downtime.html`.
e.g.
https://deploy-preview-4157--oss-insights.netlify.app/ -> https://deploy-preview-4157--oss-insights.netlify.app/downtime.html
https://deploy-preview-4157--oss-insights.netlify.app/u/nickytonline -> …

chore: created a temporary downtime page

---

components/molecules/ContributorProfileHeader/contributor-profile-header.tsx

Fixed the bug by using a tags instead of link tags
Fixes #4108 
https://github.com/user-attachments/assets/2310dc7d-f281-4dd5-ad5f-3629c0309d6b

fix: use a tags instead of link tags

---

components/atoms/Fab/fab.tsx
components/molecules/HighlightInput/highlight-input-form.tsx

This PR fixes the Ally warning caused by jsx-ally, by using buttons to replace p and div elements that have `onClick`
Fixes #4137

fix: a11y rule "no-noninteractive-element-interactions"

---

pages/workspaces/[workspaceId]/settings.tsx

Fixes a regression introduced in #4171
Relates to #4171
1. Log in
2. Navigate to a workspace you own
3. Edit the workspace settings
4. Scroll to the visibility section
5. Click the `Set to private` button
6. Click the `yes, set to private` button in the modal
7. Do the same thing again, but to set it to private.

fix: fixed changing workspaces visibility regression

---

components/molecules/AnnouncementCard/announcement-card.tsx

Removed the image word from the image alt string
fixes #4132

fix: a11y rule "img-redundant-alt" fails with a warning

---

components/StarSearch/StarSearchChat.tsx

Removed the aria-setsize attribute, as the content structure varies and includes different HTML elements.
closes #4128 
1 run `npm run lint` in the root folder and see warnings are not occurring.

fix: resolve a11y warnings for role-supports-aria-props rule

---

middleware.ts
netlify.toml

Fixes #4203
Redirect the app to the Linux Blog and take the product offline.
* **netlify.toml**: Add a redirect from `https://app.opensauced.pizza/*` to `https://opensauced.pizza/blog/opensauced-is-joining-the-linux-foundation`.
* **middleware.ts**: Add a check to redirect all routes to `https://opensauced.pizza/blog/opensauced-is-joining-the-linux-foundation`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/open-sauced/app/pull/4204?shareId=e8ba32d7-7e96-459a-85cb-1f0c6ddef147).

fix: Redirect to Linux Blog
